<!--会員情報編集フォーム-->
<section>
  <div class="x_panel">
    <div class="x_title">
      <h2>CSV登録フォーム</h2>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <!--中身-->
      <form action="<?=BASEURL?>/admin/csv/registrerfinish/" method="post" id="form">
        <table class="table table-striped table-responcive">
          <tbody>
            <tr>
              <th><label for="name" class="required">CSV名</label></th>
              <td class="form-inline">
                <input type="text" name="name" value="<?=$this->detail['name']?>" class=" form-control">
              </td>
            </tr>
            <tr>
              <th><label for="name" class="required">1行目</label></th>
              <td class="form-inline">
                <select name="firstLine" class="form-control">
                  <?php foreach(array("読み込まない","読み込む") as $k=>$v):?>
                    <?php if($k == $this->detail['firstLine']):?>
                      <option value="<?=$k?>" selected><?=$v?></option>
                    <?php else:?>
                      <option value="<?=$k?>"><?=$v?></option>
                    <?php endif;?>
                  <?php endforeach;?>
                </select>
              </td>
            </tr>
            <tr>
              <th>CSVファイル</th>
              <td>
                <?php if($this->detail['csv'] != 1):?>
                  <button type="button" class="btn btn-primary" id="csvuploadbtn">ファイルを参照</button>
                <?php endif;?>
                <div class="row" id="activate">
                  <div class="col-sm-6">
                    <h3>候補</h3>
                    <div id="valid" class="sortable">
                      <?php if($this->detail['csv'] == 1):?>
                        <ul class="invalid sortable2">
                          <?php foreach($this->detail['valid'] as $v):?>
                            <li id="<?=$v["csvColumn"]?>" data-name="<?=$v["name"]?>" data-valid="valid">
                              <i class="fa fa-exchange"></i>
                              <?=$v["name"]?>
                            </li>
                          <?php endforeach;?>
                        </ul>
                      <?php endif;?>
                    </div>
                  </div>
                  <div class="col-sm-6">
                    <h3>使用する項目</h3>
                    <div id="invalid" class="sortable">
                      <?php if($this->detail['csv'] == 1):?>
                        <ul class="invalid sortable2">
                          <?php foreach($this->detail['invalid'] as $v):?>
                            <li id="<?=$v["id"]?>" data-name="<?=$v["name"]?>" data-valid="invalid">
                              <i class="fa fa-exchange"></i>
                              <?=$v["name"]?>
                            </li>
                          <?php endforeach;?>
                        </ul>
                      <?php endif;?>
                    </div>
                  </div>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
        <input type="hidden" name="items" value="">
        <input type="hidden" name="sort" value="">
        <input type="hidden" name="before" value="">
      </form>
      <div style="display:none;">
        <form action="<?=BASEURL?>/admin/csv/upload5" method="post" enctype="multipart/form-data" target="upload" id="csvupload">
          <input type="file" name="userfile" id="userfile" />
          <iframe name="upload" style="width:100%;height:200px"></iframe>
        </form>
      </div>
      <div class="form-actions">
        <button class="btn btn-large btn-block btn-primary" id="sub">登録</button>
      </div>
      <!--中身-->
    </div>
  </div>
</section>
<style>
  .sortable{
    background: #efe;
    padding: 1em;
  }
  #valid.sortable{
    background: #fee;
  }
  .sortable2{
    margin: 0;
    padding: 0;
    list-style: none;
    min-height: 200px;
  }
  .sortable2 li{
    margin-bottom: 0.5em;
    border-radius: 5px;
    border: solid 1px #ccc;
    padding: 1em;
    background-color: #fff;
  }
  .sortable2 li i{
    /*display: table-cell;*/
    display: inline-block;
    height: 100%;
    margin-right: 1em;
  }
</style>
<script src="<?=BASEURL?>/js/validation.js"></script>
<script>
var error =new Array;
var log;
var json;
<?php if($this->detail['csv'] == 1):?>
var invalid = <?=$this->detail['items']?>;
var valid = <?=$this->detail['validA']?>;
var beforeA = <?=$this->detail['before']?>;
var sort = <?=$this->detail['sort']?>;
console.log(invalid);
console.log(valid);
console.log(beforeA);
console.log(sort);
$("[name=items]").val(JSON.stringify(invalid));
$("[name=sort]").val(JSON.stringify(sort));
$("[name=before]").val(JSON.stringify(beforeA));
<?php else:?>
var invalid = new Array();
var valid = new Array();
<?php endif;?>
$(function(){
  $("#csvuploadbtn").on("click",function(){
    $("#userfile").trigger("click");
  });
  $("#userfile").on("change",function(){
    $("#csvupload").submit();
  });
	//バリデーション
	$("[name=name]").on("blur",function(){
		validEmpty("name","CSV名");
	});
	$("#sub").on("click",function(){
		error =new Array;
		validEmpty("name","寺院名");
		if(error.length >0){
			var str = "";
			str+= "入力に誤りがあります。下記の項目を修正して再度ボタンを押してください。\n";
			for(var i =0;i<error.length;i++){
				if(error[i] =="nameEmpty"){
					str+="「CSV名」を入力してください。\n";
				}
      }
			alert(str);
		}else{
			if(window.confirm("CSV登録を行います。内容を変更される場合はキャンセルボタンを押してください。")){
				$("#form").submit();
			}
		}
	});
  activateSortable();
});
function validDisplay(data){
  json = data;
  valid = json;
  $("[name=before]").val(JSON.stringify(json));
  var str = '<ul class="invalid sortable2">';
  for(var i=0;i<valid.length;i++){
    str+= '<li id="'+i+'" data-name="'+valid[i]+'" data-valid="valid">';
    str+= '<i class="fa fa-exchange"></i>';
    str+= valid[i];
    str+= '</li>';
  }
  str+= '</ul>';
  $("#valid").html(str);
  var str = '<ul class="valid sortable2">';
  str+= '</ul>';
  $("#invalid").html(str);
  //高さを揃える
  $("#invalid ul").css("height",$("#valid ul").outerHeight());
  $("#valid ul").css("height",$("#valid ul").outerHeight());
  activateSortable();
  $('.sortable2').disableSelection();
}
function activateSortable(){
  //ドラッグされる要素
  $('.sortable2').sortable( {
    connectWith: '.sortable2',
    update: function(ev, ui) {
      if (this === ui.item.parent()[0]) {
        //log = $(".sortable2.invalid").sortable("toArray");
        var arr = new Array();
        var arr2 = new Array();
        $("#invalid").children().children().each(function(index){
          //console.log($("#invalid").children().children()[index].id);
          arr.push($("#invalid").children().children()[index].id);
          arr2.push({id:$("#invalid").children().children()[index].id,name:$("#invalid").children().children()[index].innerText});
        });
        log = arr;
        invalid = arr2;
        if(ui.item[0].attributes['data-valid'].value != "invalid"){
          ui.item[0].attributes['data-valid'].value = "invalid";
          //var arr = {id:ui.item.attr("id"),name:ui.item[0].getAttribute("data-name")};
          //invalid.push(arr);
        }else{
          ui.item[0].attributes['data-valid'].value = "valid";
        }
        $("[name=items]").val(JSON.stringify(invalid));
        $("[name=sort]").val(JSON.stringify(log));
        <?php if($this->detail['csv'] != 1):?>
        $("[name=before]").val(JSON.stringify(json));
        <?php endif;?>
        console.log(log);

      }
    }
  });
}
</script>
