<!-- 商品詳細情報　-->
<section>
  <div class="x_panel">
    <div class="x_title">
    <h2>コンテンツカテゴリ詳細</h2>
    <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <!--中身-->
      <table class="table table-striped table-responcive">
        <tbody>
          <tr>
            <th>カテゴリ名<span id="l-002"></span></th>
            <td><?=$this->data['name']?></td>
          </tr>
        </tbody>
      </table>
      <div class="form-actions">
        <p><a href="<?=BASEURL?>/editor/content/categoryupdate/?id=<?=$this->data['id']?>" class="btn btn-info btn-primary btn-block">編集</a></p>
        <p>
          <input type="hidden" name="ids" value="<?=$this->data['id']?>">
          <button type="button" class="btn btn-large btn-block btn-danger" id="deleteAll">削除</button>
        </p>
      </div>
      <!--中身-->
    </div>
  </div>
</section>

<script>
	$("#deleteAll").on("click",function(){
		if(window.confirm("本当に削除してもいいですか？")){
			var ck = $('input[name=ids]').val();
			var url = "<?=BASEURL?>/api/content/categorydelete/";
			$.post(url,{ids:ck},function(data){
				if(data == "OK"){
					location.href = "<?=BASEURL?>/editor/content/category";
				}
			});
		}
	});
</script>
