<!--商品情報編集フォーム-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>お知らせカテゴリ登録</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
          <div class="data-table">
            <form action="<?=BASEURL?>/editor/content/categoryregistrerfinish/" method="post" id="form">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                    <th>カテゴリ名</th>
                    <td><input type="text" name="name" value="<?=$this->data['name']?>" class=" required form-control"></td>
                 </tr>
                <!--tr>
                    <th>タイトル<span id="l-005"></span></th>
                    <td><input type="text" name="title" value="<?=$this->data['title']?>" id="f-005" class=" required form-control"></td>
                 </tr>
                <tr>
                    <th>ディスクリプション<span id="l-006"></span></th>
                    <td><input type="text" name="description" value="<?=$this->data['description']?>" id="f-006" class=" required form-control"></td>
                 </tr>
                <tr>
                    <th>本文<span id="l-004"></span></th>
                    <td>
							<script src="<?=BASEURL?>/theme/vendors/ckeditor/ckeditor.js" type="text/javascript"></script>
                        <textarea name="html" class="ckeditor" id="f-006" class=" required form-control"><?=$this->data['body']?></textarea>
                    </td>
                 </tr>
                <tr>
                    <th>表示・非表示<span id="l-010"></span></th>
                    <td>
                <select name="display" class=" required  form-control" id="f-010">
                    <option value="">選択</option>
                <?php
					$arr = array(0=>"表示",1=>"非表示");
					foreach($arr as $k=>$v){
				 		if($this->data['display'] == $k){
							echo '<option value="'.$k.'" selected>'.$v.'</option>';
						}else{
							echo '<option value="'.$k.'">'.$v.'</option>';
						}
					}?>
                    </select></td>
                 </tr>
            	<tr>
                	<td>PC用バナー</td>
                	<td>
                    <span id="preview">
                    <?php if($this->youto['thumb']):?>
                        <img src="<?=BASEURL?><?=$this->data['thumb']?>" style="width:120px;height:auto;">
                        <?php endif;?>
                    </span>
                    <input type="text" name="thumb" value="<?=$this->data['thumb']?>" class="form-control">
                  </td>
               </tr>
            	<tr>
                	<td>スマホ用バナー</td>
                	<td>
                    <span id="preview2">
                    <?php if($this->youto['thumb2']):?>
                        <img src="<?=BASEURL?><?=$this->data['thumb2']?>" style="width:120px;height:auto;">
                        <?php endif;?>
                    </span>
                    <input type="text" name="thumb2" value="<?=$this->data['thumb2']?>" class="form-control">
                  </td>
               </tr-->
                </tbody>
              </table>
                <input type="hidden" name="id" value="<?=$this->data["id"]?>">
            </form>
            </div>
            <!--iframe name="upload" style="display:none;"></iframe>
            <form action="<?=BASEURL?>/admin/youto/upload" method="post" enctype="multipart/form-data" target="upload" id="imageupload">
                 PC用バナーアップローダー：<input type="file" name="userfile" id="userfile" />
                 　　<input type="hidden" name="id" value="<?=$this->data['id']?>">
            </form>
            <iframe name="upload2" style="display:none;"></iframe>
            <form action="<?=BASEURL?>/admin/youto/upload2" method="post" enctype="multipart/form-data" target="upload" id="imageupload2">
                 スマホ用バナーアップローダー：<input type="file" name="userfile2" id="userfile2" />
                 　　<input type="hidden" name="id" value="<?=$this->data['id']?>">
            </form--->
       	　<!--中身-->
            <div class="form-actions">
                <button class="btn btn-large btn-block btn-primary" id="sub">登録</button>
            </div>

		<!--中身-->
        </div>
      </div>
    </div>
</section>
<!--script src="<?=BASEURL?>/js/help-validation.js"></script-->
<script>
$(function(){
	$("#sub").on("click",function(){
		if(window.confirm("コンテンツカテゴリ登録を行います。内容を変更される場合はキャンセルボタンを押してください。")){
			$("#form").submit();
		}
	});
	$("#userfile").change(function(){
		$("#imageupload").submit();
	});
	$("#userfile2").change(function(){
		$("#imageupload2").submit();
	});
});
</script>
