
<!-- 商品詳細情報　-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>コンテンツ登録完了</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <p>下記の内容でコンテンツ登録を行いました。編集及び削除は、コンテンツ管理画面より行えます。</p>
        <p><a href="<?=BASEURL?>/admin/content/" class="btn btn-primary">コンテンツ管理画面へ進む</a></p>
        <p><a href="<?=BASEURL?>/admin/content/register2/?id=<?=$this->data['id']?>" class="btn btn-info">コンテンツ詳細へ進む</a></p>
        <p><a href="<?=BASEURL?>/admin/content/registrer" class="btn btn-success">続けてコンテンツを登録する</a></p>
        <br><br>
        
          <div class="data-table">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                    <th>ページ名<span id="l-001"></span></th>
                    <td><?=$this->data['name']?></td>
                 </tr>
                <tr>
                    <th>カテゴリ<span id="l-001"></span></th>
                    <td>
                            	<?php foreach($this->categorys as $v):?>
                                	<?php if($v['id'] == $this->data['category']):?>
                                    <?=$v['name']?>
                                <?php endif;?>
                             <?php endforeach;?>
                    </td>
                 </tr>
                <tr>
                    <th>ページタイトル<span id="l-002"></span></th>
                    <td><?=$this->data['title']?></td>
                 </tr>
                <tr>
                    <th>ディスクリプション<span id="l-003"></span></th>
                    <td><?=$this->data['description']?></td>
                 </tr>
                <tr>
                    <th>本文<span id="l-004"></span></th>
                    <td><?=$this->data['body']?></td>
                 </tr>
            	<tr>
                	<td>PC用バナー</td>
                	<td>
                    <span id="preview">
                    <?php if($this->data['thumb']):?>
                        <img src="<?=BASEURL?><?=$this->data['thumb']?>" style="width:120px;height:auto;">
                        <?php endif;?>
                    </span>
                  </td>
               </tr>
            	<tr>
                	<td>スマホ用バナー</td>
                	<td>
                    <span id="preview2">
                    <?php if($this->data['thumb2']):?>
                        <img src="<?=BASEURL?><?=$this->data['thumb2']?>" style="width:120px;height:auto;">
                        <?php endif;?>
                    </span>
                  </td>
               </tr>
                </tbody>
              </table>
            </div>
            <div class="form-actions">
                <form action="<?=BASEURL?>/admin/content/detail/" method="get">
                    <input type="hidden" name="id" value="<?=$this->data['id']?>">
                    <button type="submit" class="btn btn-large btn-block btn-info">詳細</button>
                </form>
                <form action="<?=BASEURL?>/admin/content/update/" method="get">
                    <input type="hidden" name="id" value="<?=$this->data['id']?>">
                    <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
                </form>
                <form action="<?=BASEURL?>/admin/content/delete/" method="post">
                    <input type="hidden" name="id" value="<?=$this->data['id']?>">
                    <button type="submit" class="btn btn-large btn-block btn-danger">削除</button>
                </form>
            </div>
        
          
		<!--中身-->
        </div>
      </div>
    </div>
</section>
