<?php if($this->msg):?>
  <div class="alert alert-success"><?=$this->msg?></div>
<?php endif;?>
<!--商品情報編集フォーム-->
<section>
  <div class="x_panel">
    <div class="x_title">
      <h2>お知らせ編集</h2>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <!--中身-->
      <form action="<?=BASEURL?>/editor/content/updatefinish/" method="post" id="form">
        <table class="table table-striped table-responcive">
          <tbody>
            <tr>
              <th width="10%">ページ名</th>
              <td><input type="text" name="name" value="<?=$this->data['name']?>" class="required form-control"></td>
            </tr>
            <tr>
              <th>カテゴリ</th>
              <td class="form-inline">
                <select name="category" class="form-control">
                  <?php foreach($this->category as $v):?>
                    <?php /*
                    */?>
                    <?php if($v['id'] == $this->data['category']):?>
                      <option value="<?=$v['id']?>" selected><?=$v['name']?></option>
                    <?php else:?>
                      <option value="<?=$v['id']?>"><?=$v['name']?></option>
                    <?php endif;?>
                  <?php endforeach;?>
                </select>
              </td>
            </tr>
            <tr>
              <th>本文</th>
              <td>
                <script src="<?=BASEURL?>/theme2/vendors/ckeditor/ckeditor.js" type="text/javascript"></script>
                <textarea name="content" class="ckeditor"><?=$this->data['content']?></textarea>
              </td>
            </tr>
            <tr>
              <td>画像</td>
              <td>
                <p><button type="button" class="btn btn-default" id="uploadBtn">画像をアップロード</button></p>
                <span id="preview">
                  <?php if($this->data['thumb']):?>
                    <img src="<?=BASEURL?><?=$this->data['thumb']?>" style="width:120px;height:auto;">
                  <?php endif;?>
                </span>
                <input type="hidden" name="thumb" value="<?=$this->data['thumb']?>" class="form-control">
              </td>
            </tr>
          </tbody>
        </table>
        <input type="hidden" name="id" value="<?=$this->data["id"]?>">
      </form>
      <div style="display:none;">
        <iframe name="upload"></iframe>
        <form action="<?=BASEURL?>/editor/content/upload" method="post" enctype="multipart/form-data" target="upload" id="imageupload">
          <input type="file" name="userfile" id="userfile" />
          <input type="hidden" name="id" value="<?=$this->data['id']?>">
        </form>
      </div>
      <div class="form-actions">
        <button class="btn btn-large btn-block btn-primary" id="sub">編集</button>
      </div>
      <!--中身-->
    </div>
  </div>
</section>
<script>
$(function(){
	$("#sub").on("click",function(){
		if(window.confirm("お知らせ編集を行います。内容を変更される場合はキャンセルボタンを押してください。")){
			$("#form").submit();
		}
	});
  $("#uploadBtn").on("click",function(){
    $("#userfile").click();
  });
	$("#userfile").change(function(){
		$("#imageupload").submit();
	});
});
</script>
