<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js"></script>
<script type="text/javascript">
<?php if($this->success):?>
var success = true;
<?php else:?>
var success = false;
<?php endif;?>
$(function(){
	if(success){
		var filename = "<?=$this->filename?>";
		var html = '';
		if(/\.(jpg|jpeg|png|gif)$/i.test(filename)){
			html = '<img src="<?=BASEURL?>' + filename + '" style="width:120px">';
		}else if(/\.pdf$/i.test(filename)){
			html = '<img src="<?=BASEURL?>/image/icon/pdf.png" style="width:80px;height:auto">';
		}else if(/\.(xlsx|xls)$/i.test(filename)){
			html = '<img src="<?=BASEURL?>/image/icon/xls.png" style="width:80px;height:auto">';
		}else{
			html = '<img src="<?=BASEURL?>/image/noImage.png" style="width:80px;height:auto">';
		}
		parent.$('#preview').empty().html(html);
		parent.$('input[name="thumb"]').val(filename);
	}else{
    		parent.$('#preview').empty().html("同じ名前のファイルがあります。");
	}
});
</script>