<section>
  <div class="x_panel">
    <div class="x_title">
      <h2>部門一覧</h2>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <!--中身-->
      <form action="<?=BASEURL?>/editor/division/" method="get">
        <div class="row">
          <p class="col-sm-4"><input type="text" name="keyword" value="" class="form-control search_keyword" placeholder="&#xf002; キーワード"></p>
          <p class="col-sm-1">件数</p>
          <p class="col-sm-2">
          <select name="limit" class="form-control">
          <option value="10">10件</option>
          <option value="25">25件</option>
          <option value="50">50件</option>
          <option value="75">75件</option>
          <option value="100">100件</option>
          </select>
          </p>
          <p class="col-sm-1">
          <button type="submit" class="btn btn-warning">検索</button>
          </p>
          <p class="col-sm-4 text-right">
          <a href="<?=BASEURL?>/editor/division/registrer/" class="btn btn-success">部門登録</a>
          </p>
        </div>
      </form>
      <?=$this->pager?>
      <table class="table table-striped responsive-utilities jambo_table bulk_action">
        <thead>
          <tr class="headings">
            <th><input type="checkbox" id="allcheck" class="flat ck"></th>
            <th class="column-title">部門名 </th>
            <th class="column-title">詳細 </th>
          </tr>
        </thead>
        <tbody>
          <?php foreach($this->users as $vv):?>
            <tr class="even pointer">
              <td class="a-center ">
                <input type="checkbox" class="ck" name="ck[]" value="<?=$vv['id']?>">
              </td>
              <td class=" "><?=$vv['name']?><?=$vv['room']?></td>
              <td class="">
              <form action="<?=BASEURL?>/editor/division/update/" method="get">
                <input type="hidden" name="id" value="<?=$vv['id']?>">
                <button type="submit" class="btn btn-primary">詳細</button>
              </form>
              </td>
            </tr>
          <?php endforeach;?>
        </tbody>
      </table>
      <div class="profile_title">
        <div class="row">
          <div class="col-sm-12">
          <button class="btn btn-danger" type="button" id="deleteAll">チェックしたものを削除</button>
        </div>
        </div>
      </div>
      <?=$this->pager?>
      <!--中身-->
    </div>
  </div>
</section>
<script>
$(function(){
	$('input[type=checkbox]').click(function() {
	  var t = $(this).prop;
		if(t('checked'))
			t('checked', '');
		else
			t('checked', 'checked');
	});

	$('table tr').click(function() {
	  var c = $(this).children('td').children('input[type=checkbox]');
		if(c.prop('checked'))
			c.prop('checked', '');
		else
			c.prop('checked', 'checked');
	});
	//checkboxを全て同時に選択
	$("#allcheck").on("click",function(){
		if($(this).is(':checked')){
			$(".ck").prop('checked', true);
		}else{
			$(".ck").prop('checked', false);
		}
	});
	$("#deleteAll").on("click",function(){
		if(window.confirm("本当に削除してもいいですか？")){
			var ck = $('[class="ck"]:checked').map(function(){
				return $(this).val();
			}).get();
			var url = "<?=BASEURL?>/api/division/delete/";
			$.post(url,{ids:ck},function(data){
				if(data = "OK"){
					location.href = "<?=BASEURL?>/editor/division/";
				}
			});
		}
	});
});
</script>
