<!--会員情報編集フォーム-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>部門登録フォーム</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
          <p><?=$this->detail['name']?>を登録しました。詳細情報は下記のリンクより確認してください。</p>
          <p><a href="<?=BASEURL?>/editor/division/detail?id=<?=$this->detail['id']?>"><?=$this->detail['name']?>の詳細</a></p>

          <div class="data-table">
              <table class="table table-striped table-responcive">
                <tbody>
                  <tr>
                    <th><label for="name" class="required">部門名</label></th>
                    <td class="form-inline"><?=$this->detail['name']?></td>
                  </tr>
                  <tr>
                    <th><label for="name" class="required">スキル</label></th>
                    <td class="form-inline">
                    <div id="rest">
                    <?php foreach($this->skil as $v):?>
                     <p><?=$v["name"]?></p>
                    <?php endforeach;?>
                    </div>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div class="form-actions">
                <form action="<?=BASEURL?>/editor/division/detail/" method="get">
                    <input type="hidden" name="id" value="<?=$this->detail['id']?>">
                    <button type="submit" class="btn btn-large btn-block btn-success">詳細</button>
                </form>
                <form action="<?=BASEURL?>/editor/division/update/" method="get">
                    <input type="hidden" name="id" value="<?=$this->detail['id']?>">
                    <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
                </form>
            </div>
			<!--中身-->
        </div>
      </div>
    </div>
</section>
