<?php if($_GET['finish'] == 1):?>
  <div class="alert alert-warning">更新しました。</div>
<?php endif;?>
<!--部門情報編集フォーム-->
<p><a href="<?=BASEURL?>/editor/division/" class="btn btn-success">部門一覧へ</a></p>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>部門編集フォーム</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
          <div class="data-table">
          	<form action="<?=BASEURL?>/editor/division/updatefinish" method="post" id="form">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                  <th><label for="name" class="required">部門名</label></th>
                  <td class="form-inline">
                  	<input type="text" name="name" value="<?=$this->detail['name']?>" class=" form-control">
                  </td>
                </tr>
                <tr>
                  <th><label for="name" class="required">スキル</label></th>
                  <td class="form-inline">
                    <p>登録されているスキルを削除する場合は、スキル名を削除してください。</p>
                    <div id="rest">
                      <?php $i=0;foreach($this->skil as $v):?>
                        <p>
                          <input type="text" name="skil[<?=$i?>]" value="<?=$v["name"]?>" class="form-control">
                          <input type="hidden" name="skilId[<?=$i?>]" value="<?=$v["id"]?>">
                        </p>
                      <?php $i++;endforeach;?>
                    </div>
                    <button type="button" class="btn btn-primary" id="restAdd">スキルを追加</button>
                  </td>
                 </tr>
                </tbody>
              </table>
              <input type="hidden" name="id" value="<?=$this->detail['id']?>">
              </form>
            </div>
            <div class="form-actions">
                <button class="btn btn-large btn-block btn-primary" id="sub">編集</button>
            </div>
			<!--中身-->
        </div>
      </div>
    </div>
</section>
<script src="<?=BASEURL?>/js/validation.js"></script>
<script>
//スキル
$("#restAdd").on("click",function(){
  var str = '';
  str+= '<p>';
  str+= '<input type="text" name="skil[]" value="" class="form-control">';
  str+= '</p>';
  $("#rest").append(str);
});
//バリデーション
var error =new Array;
$(function(){
	$("[name=name]").on("blur",function(){
		validEmpty("name","部門名");
	});

	$("#sub").on("click",function(){
		validEmpty("name","部門名");
		if(error.length >0){
			var str = "";
			str+= "入力に誤りがあります。下記の項目を修正して再度ボタンを押してください。\n";
			for(var i =0;i<error.length;i++){
				if(error[i] =="nameEmpty"){
					str+="「部門名」を入力してください。\n";
				}
			}
			alert(str);
		}else{
			if(window.confirm("部門登録を行います。内容を変更される場合はキャンセルボタンを押してください。")){
				$("#form").submit();
			}
		}
	});
});
</script>
