<!-- Search section -->
<div class="section">
  <div class="container">
    <form action="<?=BASEURL?>/index/index/list" method="get">
      <div class="border_02 padding-30 border-radius-05">
      <!-- Etc section -->
      <div class="text-center">
        <h4>地域<span class="atention">チェックしない場合には全町が対象となります</span></h4>
        <div class="divider-width-70px divider-height-2px margin-bottom-30">
          <hr class="bg_yellow">
        </div>
      </div>
      <div class="row col-spacing-20">
        <?php foreach(array("東彼杵町","川棚町","波佐見町") as $v):?>
            <div class="col-12 col-sm-6 col-md-4 col-lg-4">
              <div class="form-check margin-bottom-10">
                <label class="form-check-label">
                  <input class="form-check-input" type="checkbox" value="<?=$v?>" id="<?=$v?>" name="area[]">
                  <?=$v?>
                </label>
              </div>
            </div>
        <?php endforeach;?>
      </div>
      <!-- emd:Etc section -->
      <hr class="bg-black-02 margin-top-30 margin-bottom-30">
        <!-- Type of facility section -->
        <div class="text-center">
        <h4>施設の種類</h4>
        <div class="divider-width-70px divider-height-2px margin-bottom-30">
        <hr class="bg_yellow">
        </div>
        </div>
        <div class="row col-spacing-20">
        <?php foreach($this->class as  $v):?>
          <div class="col-12 col-sm-6 col-md-4 col-lg-4">
          <div class="form-check margin-bottom-10">
          <label class="form-check-label">
            <input class="form-check-input" type="checkbox" value="<?=$v['id']?>" id="<?=$v['id']?>" name="class[]">
            <?=$v['name']?>
          </label>
          </div>
          </div>
        <?php endforeach;?>
        </div>
        <!-- end:Type of facility section -->
      </div>
      <div class="text-center margin-top-30">
        <button type="submit" class="button button-lg button-radius button-dark margin-top-20" ><i class="ti-search"></i> 検索する</button>
      </div>
    </form>
  </div>
</div>
<!-- end:Search section -->
