<?php if(!empty($this->html[0]['html']) || !empty($this->html[0]['thumb'])):?>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_content">
		<!--中身-->
        <?php if(!empty($this->html[0]['thumb'])):?>
            <div class="banner">
            <div class="hidden-xs">
            <p class="text-center"><img src="<?=BASEURL.$this->html[0]['thumb']?>" alt="<?=$this->html[0]['page']?>"></p>
            </div>
            <div class="visible-xs">
            <p class="text-center"><img src="<?=BASEURL.$this->html[0]['thumb2']?>" alt="<?=$this->html[0]['page']?>"></p>
            </div>
            </div>
        	
		<?php endif;?>
        <?=htmlspecialchars_decode($this->html[0]['html'])?>
       	　<!--中身-->
        </div>
      </div>
    </div>
</section>
<?php endif;?>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>お問い合わせフォーム</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        	<form action="<?=BASEURL?>/index/index/mailconfurm/" method="post" id="Form">
            	<div class="data-table">      
        <table class="table table-striped table-responcive">
        <tbody>
            <tr>
            <th>会社名</th>
            <td>
            	例：株式会社南福花園<br>
			<input type="text" name="company" value="<?=$this->data['company']?>" class="form-control" placeholder="日本語・英数字で入力">
			</td>
            </tr>
            <tr>
            <th>部署/役職</th>
            <td>例：総務部、代表取締役など<br>
			<input type="text" name="division" value="<?=$this->data['division']?>" class="form-control" placeholder="日本語・英数字で入力">
			</td>
            </tr>
            <tr>
            <th><label for="name" class="required">お名前</label></th>
            <td>例：荒瀬　健<br>
			<input type="text" name="name" value="<?=$this->data['name']?>" class="form-control required" placeholder="日本語・英数字で入力">
			</td>
            </tr>
            <tr>
            <th><label for="kana" class="required">フリガナ</label></th>
            <td>例：アラセタケシ<br>
			<input type="text" name="kana" value="<?=$this->data['kana']?>" class="form-control required" placeholder="カタカナで入力">
			</td>
            </tr>
            <tr>
            <th><label for="mail" class="required">メールアドレス</label></th>
            <td>例：support@nanpuku.co.jp<br>
            	<input type="text" name="mail" value="<?=$this->data['mail']?>" class="form-control required" placeholder="半角英数字・記号で入力">
			</td>
            </tr>
            <tr>
            <th><label for="mail" class="required">内容</label></th>
            <td>
            	<textarea name="body" class="form-control" rows="15"><?=$this->data['body']?></textarea>
			</td>
            </tr>
         </tbody>
        </table>        
        </div>
        <p class="text-center"><button class="btn btn-success btn-lg" id="formSubmit" type="button">確認</button></p>
            </form>
       	　<!--中身-->
        </div>
      </div>
    </div>
</section>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>即日発送対応商品</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="row">
        <?php foreach($this->soku as $vv):?>
        <div class="col-md-55">
          <div class="thumbnail">
            <div class="image view view-first">
            	<?php if($vv['imagen']):?>
					<?php if($vv['realtimeFlug'] ==0 && $vv['orderToDeli'] <= 1):?>
                    <img src="<?=BASEURL."/api/image/?size=400&url=".$vv['imagen']?>" alt="<?=$vv['name']?>" style="width: 100%; display: block;">
                    <?php else:?>
                    <img src="<?=BASEURL."/".$vv['imagen']?>" alt="<?=$vv['name']?>" style="width: 100%; display: block;">
                    <?php endif;?>
				<?php endif;?>
              <div class="mask">
                <p><a href="<?=BASEURL?>/item/detail/?id=<?=$vv['id']?>" style="color:#F5F5F5">【<?=$vv['number']?>】<?=$vv['name']?></a></p>
                <div class="tools tools-bottom">
                  <a href="<?=BASEURL?>/item/detail/?id=<?=$vv['id']?>">詳細</a>
                </div>
              </div>
            </div>
            <div class="caption">
             <p><?=number_format($vv['price'])?>円</p>
              <p><?=$vv['name']?></p>
            </div>
          </div>
        </div>
        <?php endforeach;?>
        </div>
       	　<!--中身-->
        </div>
      </div>
    </div>
</section>

<script>
	var error = new Array();
$(function(){
	//バリデーション
	$("[name=name]").on("blur",function(){
		validEmpty("name","お名前");
	});
	$("[name=kana]").on("blur",function(){
		validEmpty("kana","フリガナ");
	});
	$("[name=body]").on("blur",function(){
		validEmpty("body","お問い合わせ内容");
	});
	$("[name=mail]").on("blur",function(){
		validEmptyAndMailFormat("mail","メールアドレス");
	});
	$("#formSubmit").on("click",function(){
		validEmpty("name","お名前");
		validEmpty("kana","フリガナ");
		validEmpty("body","お問い合わせ内容");
		validEmptyAndMailFormat("mail","メールアドレス");
		if(error.length >0){
			//console.log(error);
			alert("入力に誤りがあります。修正して再度ボタンを押してください。");
		}else{
			$("#Form").submit();
		}
	});
});


function validEmpty(name,description){
	var thisis = $("[name="+name+"]");
	if($("[name="+name+"]").val() ==""){
		$("#"+name+"Valid").remove();
		var cusName = $("<span id=\""+name+"Valid\" class=\"error\">"+description+"が入力されていません.</span>");
		thisis.after(cusName);
		thisis.parent(thisis).removeClass("has-success");
		thisis.parent(thisis).addClass("has-error");
		thisis.css("background-color","#fee");
		error.push(name+"Empty");
	}else{
		$("#"+name+"Valid").remove();
		thisis.parent(thisis).removeClass("has-error");
		thisis.parent(thisis).addClass("has-success");
		thisis.css("background-color","#efe");
		for(var i=0;i<error.length;i++){
			if(name+"Empty" == error[i]){
				error.splice(i,1) ;
			}
		}
	}
}
function validEmptyAndMailFormat(name,description){
	var thisis = $("[name="+name+"]");
	if($("[name="+name+"]").val() ==""){
		$("#"+name+"Valid").remove();
		var cusName = $("<span id=\""+name+"Valid\" class=\"error\">"+description+"が入力されていません.</span>");
		thisis.after(cusName);
		thisis.parent(thisis).removeClass("has-success");
		thisis.parent(thisis).addClass("has-error");
		thisis.css("background-color","#fee");
		error.push(name+"Empty");
	}else{
		for(var i=0;i<error.length;i++){
			if(name+"Empty" == error[i]){
				error.splice(i,1) ;
			}
		}
		if($("[name="+name+"]").val().match(/^([a-zA-Z0-9])+([a-zA-Z0-9¥._-])*@([a-zA-Z0-9_-])+([a-zA-Z0-9¥._-]+)+$/) ===null){
			$("#"+name+"Valid").remove();
			var cusName = $("<span id=\""+name+"Valid\" class=\"error\">"+description+"が正しく入力されていません。</span>");
			thisis.after(cusName);
			thisis.parent(thisis).removeClass("has-success");
			thisis.parent(thisis).addClass("has-error");
			thisis.css("background-color","#fee");
			error.push(name+"MailFormat");
		}else{
			$("#"+name+"Valid").remove();
			thisis.parent(thisis).removeClass("has-error");
			thisis.parent(thisis).addClass("has-success");
			thisis.css("background-color","#efe");
			for(var i=0;i<error.length;i++){
				if(name+"MailFormat" == error[i]){
					error.splice(i,1) ;
				}
			}
		}
	}
}
</script>