<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>お問い合わせフォーム送信完了</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <p>お問い合わせありがとうございます。お問い合わせ内容の送信が完了しました。お問い合わせの控えを<?=$this->data['mail']?>宛てに送信しています。弊社にてお問い合わせ内容を確認して、改めてご返信をさせていただきますので、今しばらくお待ち下さい。</p>
        <div class="data-table">      
        <table class="table table-striped table-responcive">
        <tbody>
            <tr>
            <th>会社名</th>
            <td><?=$this->data['company']?>
			</td>
            </tr>
            <tr>
            <th>部署/役職</th>
            <td><?=$this->data['division']?>
			</td>
            </tr>
            <tr>
            <th><label for="name" class="required">お名前</label></th>
            <td><?=$this->data['name']?>
			</td>
            </tr>
            <tr>
            <th><label for="kana" class="required">フリガナ</label></th>
            <td><?=$this->data['kana']?>
			</td>
            </tr>
            <tr>
            <th><label for="mail" class="required">メールアドレス</label></th>
            <td><?=$this->data['mail']?>
			</td>
            </tr>
            <tr>
            <th><label for="cus_mail" class="required">内容</label></th>
            <td><?=str_replace("\n","<br>",$this->data['body'])?>
			</td>
            </tr>
         </tbody>
        </table>              
        </div>
       	　<!--中身-->
        </div>
      </div>
    </div>
</section>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>即日発送対応商品</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="row">
        <?php foreach($this->soku as $vv):?>
        <div class="col-md-55">
          <div class="thumbnail">
            <div class="image view view-first">
            	<?php if($vv['imagen']):?>
					<?php if($vv['realtimeFlug'] ==0 && $vv['orderToDeli'] <= 1):?>
                    <img src="<?=BASEURL."/api/image/?size=400&url=".$vv['imagen']?>" alt="<?=$vv['name']?>" style="width: 100%; display: block;">
                    <?php else:?>
                    <img src="<?=BASEURL."/".$vv['imagen']?>" alt="<?=$vv['name']?>" style="width: 100%; display: block;">
                    <?php endif;?>
				<?php endif;?>
              <div class="mask">
                <p><a href="<?=BASEURL?>/item/detail/?id=<?=$vv['id']?>" style="color:#F5F5F5">【<?=$vv['number']?>】<?=$vv['name']?></a></p>
                <div class="tools tools-bottom">
                  <a href="<?=BASEURL?>/item/detail/?id=<?=$vv['id']?>">詳細</a>
                </div>
              </div>
            </div>
            <div class="caption">
             <p><?=number_format($vv['price'])?>円</p>
              <p><?=$vv['name']?></p>
            </div>
          </div>
        </div>
        <?php endforeach;?>
        </div>
       	　<!--中身-->
        </div>
      </div>
    </div>
</section>
