<!--ユーザー情報編集フォーム-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>ユーザー登録フォーム</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
          <div class="data-table">
            <form action="<?=BASEURL?>/admin/user/registrerfinish/" method="post" id="form">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                    <th style="width:25%">会社名/部署・役職</th>
                    <td class="form-inline">
                    会社名：<input type="text" name="company" value="<?=$this->detail['company']?>" class=" form-control">
                    部署・役職：<input type="text" name="division" value="<?=$this->detail['division']?>" class=" form-control">
                    </td>
                 </tr>
                <tr>
                    <th>お名前</th>
                    <td class="form-inline">
                    <input type="text" name="name" value="<?=$this->detail['name']?>" class=" form-control" style="width:5em;">
                    <input type="text" name="name2" value="<?=$this->detail['name2']?>" class=" form-control" style="width:5em;">
                    </td>
                 </tr>
                <tr>
                    <th>フリガナ</th>
                    <td class="form-inline">
                    <input type="text" name="kana" value="<?=$this->detail['kana']?>" class=" form-control kana" style="width:5em;">
                    <input type="text" name="kana2" value="<?=$this->detail['kana2']?>" class=" form-control kana" style="width:5em;">
                    </td>
                 </tr>
                <tr>
                    <th>メール</th>
                    <td><input type="text" name="mail" value="<?=$this->detail['mail']?>" id="f-004" class="required form-control email"></td>
                 </tr>
                <tr>
                    <th>性別</th>
                    <td class="form-inline">
                    	<select name="sex" class="form-control">
                        <?php foreach(array(1=>"女性",2=>"男性") as $k=>$v):?>
                        	<?php if($k == $this->detail['sex']):?>
                        		<option value="<?=$k?>" selected><?=$v?></option>
                          <?php else:?>
                        		<option value="<?=$k?>"><?=$v?></option>
                        	<?php endif;?>
                        <?php endforeach;?>
                      </select>
                    </td>
                 </tr>
                <tr>
                    <th>生年月日</th>
                    <td class="form-inline">
                    <select name="birthY"  class=" form-control" style="width:4em;">
                    	<?php
                        $y = array("0"=>"選択してください");
					  for($i = 1900;$i<(date("Y")+1);$i++){
						$y[] = $i;
					  }
					  foreach($y as $v){
						if($v==date("Y")-36){
							echo '<option value="'.$v.'" selected>'.$v.'</option>';
						}else{
							echo '<option value="'.$v.'">'.$v.'</option>';
						}
					  }
					?>
                    </select>年
                    <select name="birthM"  class=" form-control" style="width:4em;">
                    	<?php
                        $y = array("0"=>"選択してください");
					  for($i = 1;$i<13;$i++){
						$y[$i] = $i;
					  }
					  foreach($y as $v){
						echo '<option value="'.$v.'">'.$v.'</option>';
					  }
					?>
                    </select>月
                    <select name="birthD"  class=" form-control" style="width:4em;">
                    	<?php
                        $y = array("0"=>"選択してください");
					  for($i = 1;$i<32;$i++){
						$y[$i] = $i;
					  }
					  foreach($y as $v){
						echo '<option value="'.$v.'">'.$v.'</option>';
					  }
					?>
                    </select>日
                    </td>
                 </tr>
                <tr>
                    <th>電話番号</th>
                    <td class="form-inline">
                    <input type="text" name="tel" value="<?=$this->detail['tel']?>" class=" form-control" style="width:4em;">-
                    <input type="text" name="tel2" value="<?=$this->detail['tel2']?>" class=" form-control" style="width:4em;">-
                    <input type="text" name="tel3" value="<?=$this->detail['tel3']?>" class=" form-control" style="width:4em;">
                    </td>
                 </tr>
                <tr>
                    <th>携帯電話</th>
                    <td class="form-inline">
                    <input type="text" name="mtel" value="<?=$this->detail['mtel']?>" class=" form-control" style="width:4em;">-
                    <input type="text" name="mtel2" value="<?=$this->detail['mtel2']?>" class=" form-control" style="width:4em;">-
                    <input type="text" name="mtel3" value="<?=$this->detail['mtel3']?>" class=" form-control" style="width:4em;">
                    </td>
                 </tr>
                <tr>
                    <th>住所</th>
                    <td>
                      <p class="form-inline">〒<input type="text" name="zip" value="<?=$this->detail['zip']?>" id="" class=" form-control" style="width:4em;">-
                    	   <input type="text" name="zip2" value="<?=$this->detail['zip2']?>" id="" class=" form-control" style="width:4em;">
                      </p>
                    	<p class="form-inline"><select name="pref" class="span3 required form-control">
                        	<option value="">選択</option>
                    	<?php foreach($this->pref as $v):?>
                        <?php if($v['id'] == $this->detail['pref']):?>
                        	<option value="<?=$v['id']?>" selected><?=$v['name']?></option>
                        <?php else:?>
                        	<option value="<?=$v['id']?>"><?=$v['name']?></option>
                        <?php endif;?>
                        <?php endforeach;?>
                        </select></p>
                        <p><input type="text" name="addr" value="<?=$this->detail['addr']?>" class="form-control"></p>
                        <p><input type="text" name="addr2" value="<?=$this->detail['addr2']?>" class="form-control"></p>
                        <input type="hidden" name="demand" value="1" class="form-control">
                    </td>
                <tr>
                    <th>ステータス</th>
                    <td class="form-inline">
                    <select name="active" class="span6 required form-control">
                    <option value="">選択</option>
        						<?php
        							$arr = array(0=>"無効",1=>"有効");
        							foreach($arr as $k=>$v){
        								if($this->detail['active'] == $k){
        									echo "<option value=\"{$k}\" selected>".$v."</option>";
        								}else{
        									echo "<option value=\"{$k}\">".$v."</option>";
        								}
        							}
        						?>
                    </select>
                   </td>
                 </tr>
                  <tr>
                    <th>プラン</th>
                    <td class="form-inline">
                      <select name="plan" class="form-control">
                        <option value="">選択</option>
                        <?php foreach($this->plan as $v):?>
                        <?php if($v['id'] == $this->detail['plan']):?>
                        <option value="<?=$v['id']?>" selected><?=$v['name']?></option>
                        <?php else:?>
                        <option value="<?=$v['id']?>"><?=$v['name']?></option>
                        <?php endif;?>
                        <?php endforeach;?>
                      </select>
                    </td>
                  </tr>
                  <tr>
                    <th>パスワード</th>
                    <td>
                    <p><input type="password" name="pw" value="<?=$this->detail['pw']?>" class=" form-control"></p>
                   </td>
                 </tr>
                </tbody>
              </table>
              </form>
            </div>
            <div class="form-actions">
                <button class="btn btn-large btn-block btn-primary" id="sub">編集</button>
            </div>
			<!--中身-->
        </div>
      </div>
    </div>
</section>
<script src="<?=BASEURL?>/js/validation.js"></script>
<script>
var error =new Array;
$(function(){
	//バリデーション
	$("[name=name]").on("blur",function(){
		validEmpty("name","お名前:姓");
	});
	$("[name=name2]").on("blur",function(){
		validEmpty("name2","お名前：名");
	});
	$("[name=kana]").on("blur",function(){
		validEmptyKana("kana","フリガナ：セイ");
	});
	$("[name=kana2]").on("blur",function(){
		validEmptyKana("kana2","フリガナ：メイ");
	});
	$("[name=sex]").on("blur",function(){
		validEmpty("sex","性別");
	});
	$("[name=birthY]").on("blur",function(){
		validEmptyAndNumeric("birthY","生年月日：年");
	});
	$("[name=birthM]").on("blur",function(){
		validEmptyAndNumeric("birthM","生年月日：月");
	});
	$("[name=birthD]").on("blur",function(){
		validEmptyAndNumeric("birthD","生年月日：日");
	});
	/*
	$("[name=mail]").on("blur",function(){
		validEmptyAndMailFormatAndSame("mail","メールアドレス");
	});
	*/
	$("[name=tel]").on("blur",function(){
		validEmptyAndZero("tel","電話番号");
	});
	$("[name=tel2]").on("blur",function(){
		validEmptyAndZero("tel2","電話番号2");
	});
	$("[name=tel3]").on("blur",function(){
		validEmptyAndTel("tel3","電話番号3","tel","tel2");
	});
	$("[name=zip]").on("blur",function(){
		validEmptyAndZero("zip","郵便番号");
	});
	$("[name=zip2]").on("blur",function(){
		validEmptyAndZip("zip2","郵便番号2","zip");
	});
	$("[name=pref]").on("blur",function(){
		validEmpty("pref","都道府県");
	});
	$("[name=addr]").on("blur",function(){
		validEmpty("addr","市区町村、番地");
	});
	/*
	$("[name=pw]").on("blur",function(){
		validEmpty("pw","パスワード");
	});
	*/
	$("#sub").on("click",function(){
		validEmpty("name","お名前：姓");
		validEmpty("name2","お名前：名");
		validEmptyKana("kana","フリガナ：セイ");
		validEmptyKana("kana2","フリガナ：メイ");
		/*
		validEmptyAndMailFormatAndSame("mail","メールアドレス");
		*/
		validEmptyAndZero("tel","電話番号1");
		validEmptyAndZero("tel2","電話番号2");
		validEmptyAndTel("tel3","電話番号3","tel","tel2");
		validEmptyAndZero("zip","郵便番号1");
		validEmptyAndZip("zip2","郵便番号2","zip");
		validEmpty("pref","都道府県");
		validEmpty("addr","市区町村、番地");
		/*
		validEmpty("pw","パスワード");
		*/
		validEmptyAndNumeric("birthD","生年月日：日");
		validEmptyAndNumeric("birthM","生年月日：月");
		validEmptyAndNumeric("birthY","生年月日：年");
		validEmpty("sex","性別");
		if(error.length >0){
			var str = "";
			str+= "入力に誤りがあります。下記の項目を修正して再度ボタンを押してください。\n";
			for(var i =0;i<error.length;i++){
				if(error[i] =="nameEmpty"){
					str+="「お名前：姓」を入力してください。\n";
				}
				if(error[i] =="name2Empty"){
					str+="「お名前：名」を入力してください。\n";
				}
				if(error[i] =="nameEmpty"){
					str+="「フリガナ：姓」を入力してください。\n";
				}
				if(error[i] =="kanaNotKana"){
					str+="「フリガナ：姓」は全角カタカナで入力してください。\n";
				}
				if(error[i] =="kana2Empty"){
					str+="「フリガナ：名」を入力してください。\n";
				}
				if(error[i] =="kana2NotKana"){
					str+="「フリガナ：名」は全角カタカナで入力してください。\n";
				}
				if(error[i] =="mailEmpty"){
					str+="「メールアドレス」を入力してください。\n";
				}
				if(error[i] =="mailMailFormat"){
					str+="「メールアドレス」の形式を正しく入力してください。\n";
				}
				if(error[i] =="mailMailSame"){
					str+="この「メールアドレス」はすでに登録されています。\n";
				}
				if(error[i] =="mail2Empty"){
					str+="「メールアドレス確認用」を入力してください。\n";
				}
				if(error[i] =="mail2MailDiff"){
					str+="「メールアドレス」と「メールアドレス確認用」が一致しません\n";
				}
				if(error[i] =="mail2MailFormat"){
					str+="「メールアドレス確認用」の形式を正しく入力してください。\n";
				}
				if(error[i] =="sexEmpty"){
					str+="「性別」を選択してください。\n";
				}
				if(error[i] =="birthYEmpty"){
					str+="「生年月日：年」を入力してください。\n";
				}
				if(error[i] =="birthYNumeric"){
					str+="「生年月日：年」が半角数字ではありません\n";
				}
				if(error[i] =="birthMEmpty"){
					str+="「生年月日：月」を入力してください。\n";
				}
				if(error[i] =="birthMNumeric"){
					str+="「生年月日：月」が半角数字ではありません\n";
				}
				if(error[i] =="birthDEmpty"){
					str+="「生年月日：日」を入力してください。\n";
				}
				if(error[i] =="birthDNumeric"){
					str+="「生年月日：日」が半角数字ではありません\n";
				}
				if(error[i] =="telEmpty"){
					str+="「電話番号1」を入力してください。\n";
				}
				if(error[i] =="telZero"){
					str+="「電話番号1」はゼロのみの入力は出来ません。\n";
				}
				if(error[i] =="tel2Empty"){
					str+="「電話番号2」を入力してください。\n";
				}
				if(error[i] =="telZero"){
					str+="「電話番号1」はゼロのみの入力は出来ません。\n";
				}
				if(error[i] =="tel3Empty"){
					str+="「電話番号3」を入力してください。\n";
				}
				if(error[i] =="tel3NotTel"){
					str+="電話番号として正しくありません\n";
				}
				if(error[i] =="tel3Zero"){
					str+="「電話番号3」はゼロのみの入力は出来ません。\n";
				}
				if(error[i] =="zipEmpty"){
					str+="「郵便番号１」を入力してください。\n";
				}
				if(error[i] =="zipZero"){
					str+="「郵便番号１」はゼロのみの入力は出来ません。\n";
				}
				if(error[i] =="zipNumeric"){
					str+="「郵便番号1」が半角数字ではありません\n";
				}
				if(error[i] =="zip2Empty"){
					str+="「郵便番号2」を入力してください。\n";
				}
				if(error[i] =="zip2NotZip"){
					str+="「郵便番号2」を入力してください。\n";
				}
				if(error[i] =="zip2Numeric"){
					str+="「郵便番号2」が半角数字ではありません\n";
				}
				if(error[i] =="prefEmpty"){
					str+="「都道府県」を選択してください。\n";
				}
				if(error[i] =="addrEmpty"){
					str+="「市区町村、番地」を入力してください。\n";
				}
				/*
				if(error[i] =="pwEmpty"){
					str+="「パスワード」を入力してください。\n";
				}
				if(error[i] =="pwConfurmEmpty"){
					str+="「パスワード確認用」を入力してください。\n";
				}
				if(error[i] =="pwConfurmDiff"){
					str+="「パスワード」と「パスワード確認用」が一致しません。\n";
				}
				*/
			}
			alert(str);
		}else{
			if(window.confirm("ユーザー登録を行います。内容を変更される場合は「OK」ボタンを押してください。")){
				$("#form").submit();
			}
		}
	});
});
</script>
