<!--ユーザー情報-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>編集後のユーザー情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
    		<p>下記の内容でユーザー情報の編集を行いました。編集及び削除は、ユーザー管理画面より行えます。</p>
        <p><a href="<?=BASEURL?>/admin/user/detail?id=<?=$this->data['id']?>" class="btn btn-success"><?=$this->data['name']?>様のユーザー詳細へ進む</a></p>
        <p><a href="<?=BASEURL?>/admin/user/" class="btn btn-primary">ユーザー管理画面へ進む</a></p>
        <br><br>
          <div class="data-table">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                    <th style="width:25%">会社名/部署・役職</th>
                    <td><?=$this->data['company']?> <?=$this->data['division']?></td>
                 </tr>
                <tr>
                    <th style="width:25%">お名前</th>
                    <td><?=$this->data['name']?> <?=$this->data['name2']?></td>
                 </tr>
                <tr>
                    <th>フリガナ</th>
                    <td><?=$this->data['kana']?> <?=$this->data['kana2']?></td>
                 </tr>
                <tr>
                    <th>メール</th>
                    <td><?=$this->data['mail']?></td>
                 </tr>
                <tr>
                    <th>性別</th>
                    <td><?php foreach(array(1=>"女性",2=>"男性") as $k=>$v){
							if($this->data['sex'] == $k){
								echo $v;
							}
						}?></td>
                 </tr>
                <tr>
                    <th>生年月日</th>
                    <td><?=$this->data['birthY']?>年<?=$this->data['birthM']?>月<?=$this->data['birthD']?>日</td>
                 </tr>
                <tr>
                    <th>電話番号</th>
                    <td><?=$this->data['tel']?>-<?=$this->data['tel2']?>-<?=$this->data['tel3']?></td>
                 </tr>
                <tr>
                    <th>携帯電話</th>
                    <td><?=$this->data['mtel']?>-<?=$this->data['mtel2']?>-<?=$this->data['mtel3']?></td>
                 </tr>
                <tr>
                    <th>住所</th>
                    <td>〒<?=$this->data['zip']?>-<?=$this->data['zip2']?><br><?=$this->data['prefName']?><?=$this->data['addr']?><br>
							<?=$this->data['addr2']?>
                    </td>
                 </tr>
                <tr>
                    <th>ステータス</th>
                    <td>
                		<?php
					$arr = array(0=>"無効",1=>"有効");
					foreach($arr as $k=>$v){
				 		if($this->data['active'] == $k){
							echo $v;
						}
					}?>
                   </td>
                 </tr>
                </tbody>
              </table>
            </div>
            <div class="form-actions">
                    <form action="<?=BASEURL?>/admin/order/registrer/" method="post">
                        <input type="hidden" name="member_no" value="<?=$this->data['id']?>">
                        <button type="submit" class="btn btn-large btn-block btn-info">新しい注文をする</button>
                    </form>
                    <form action="<?=BASEURL?>/admin/user/update/" method="get">
                        <input type="hidden" name="id" value="<?=$this->data['id']?>">
                        <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
                    </form>
                    <input type="hidden" name="ids" value="<?=$this->data['id']?>">
                    <button type="button" class="btn btn-large btn-block btn-danger" id="deleteAll">削除</button>
            </div>
			<!--中身-->
        </div>
      </div>
    </div>
</section>