<?php if($this->msg):?>
  <div class="alert alert-success"><?=$this->msg?></div>
<?php endif;?>
<?php if($this->detail['stop'] != "0000-00-00 00:00:00"):?>
  <div class="alert alert-danger">強制停止中</div>
<?php endif;?>
<p><a href="<?=BASEURL?>/admin/user" class="btn btn-primary">一覧へ</a></p>

<!--ユーザー情報編集フォーム-->
<section>
  <div class="x_panel">
    <div class="x_content">
      <!--中身-->
      <p><code><?=BASEURL?>/login/?m=<?=$this->detail['space']?></code> <br><br><button class="copy_code btn btn-warning">クリップボードにコピー</button></p>
      <!--中身-->
    </div>
  </div>
</section>
<div class="" role="tabpanel" data-example-id="togglable-tabs">
  <div style="overflow:scroll;max-width:100%;">
    <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist" style="width:900px;">
      <li role="presentation" class="active"><a href="#tab_content3" role="tab" id="profile-tab3" data-toggle="tab" aria-expanded="false">アクティビティ</a>
      </li>
      <li role="presentation" class=""><a href="#tab_content5" role="tab" id="profile-tab5" data-toggle="tab" aria-expanded="true">請求・入金</a>
      </li>
      <li role="presentation" class=""><a href="#tab_content1" id="profile-tab" role="tab" data-toggle="tab" aria-expanded="true">詳細</a>
      </li>
      <li role="presentation" class=""><a href="#tab_content2" role="tab" id="profile-tab2" data-toggle="tab" aria-expanded="true">特権管理者</a>
      </li>
      <li role="presentation" class=""><a href="#tab_content4" role="tab" id="profile-tab4" data-toggle="tab" aria-expanded="true">強制停止</a>
      </li>
    </ul>
  </div>
  <div id="myTabContent" class="tab-content">
    <div role="tabpanel" class="tab-pane fade" id="tab_content1" aria-labelledby="home-tab">
      <section>
        <div class="x_panel">
          <div class="x_title">
            <h2>詳細</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <!--中身-->
            <form action="<?=BASEURL?>/admin/user/updatefinish" method="post" id="form">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                  <th style="width:25%">容量</th>
                  <td class="form-inline">
										<?php
										if($this->detail['size'] <50){
											$addClass=" progress-bar-success";
										}elseif($this->detail['size'] >50 && $this->detail['size'] <80){
											$addClass=" progress-bar-warning";
										}elseif($this->detail['size'] >80){
											$addClass=" progress-bar-danger";
										}
										?>
										<div class="progress">
										<div class="progress-bar<?=$addClass?>" data-realsize="<?=$this->detail['realsize']?>" data-transitiongoal="<?=$this->detail['size']?>" aria-valuenow="<?=$this->detail['size']?>" style="width: <?=$this->detail['size']?>%;"></div>
										<?=$this->detail['size']?>% (<?php echo round($this->detail['realsize']/1000000000,2);?>GB)
										</div>
										最大<?php echo round($this->detail['max_size']/1000000000,2);?>GB
                  </td>
                </tr>
                <tr>
                  <th style="width:25%">会社名</th>
                  <td>
                    <input type="text" name="company" value="<?=$this->detail['company']?>" class=" form-control">
                  </td>
                </tr>
                <tr>
                  <th>ステータス</th>
                  <td class="form-inline">
                    <select name="active" class="form-control" id="f-011">
                      <option value="">選択</option>
                      <?php
                        $arr = array(0=>"無効",1=>"有効");
                        foreach($arr as $k=>$v){
                          if($this->detail['active'] == $k){
                            echo "<option value=\"{$k}\" selected>".$v."</option>";
                          }else{
                            echo "<option value=\"{$k}\">".$v."</option>";
                          }
                        }
                      ?>
                    </select>
                  </td>
                </tr>
                <tr>
                  <th>プラン</th>
                  <td class="form-inline">
                    <select name="plan" id="plan" class="span3 required form-control">
                      <option value="">選択</option>
                      <?php foreach($this->plan as $v):?>
                      <?php if($v['id'] == $this->detail['plan']):?>
                      <option value="<?=$v['id']?>" selected><?=$v['name']?></option>
                      <?php else:?>
                      <option value="<?=$v['id']?>"><?=$v['name']?></option>
                      <?php endif;?>
                      <?php endforeach;?>
                    </select>
                  </td>
                </tr>
              </tbody>
              </table>
              <input type="hidden" name="id" value="<?=$this->detail['id']?>">
            </form>
            <div class="form-actions">
              <button class="btn btn-large btn-block btn-primary" id="sub">編集</button>
            </div>
            <!--中身-->
          </div>
        </div>
      </section>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
      <section>
        <div class="x_panel">
          <div class="x_title">
            <h2>特権管理者</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <!--中身-->
            <form action="<?=BASEURL?>/admin/user/updatefinish" method="post" id="form2">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                  <th style="width:25%;">お名前</th>
                  <td class="form-inline">
                    <input type="text" name="name" value="<?=$this->special['name']?>" class=" form-control" style="width:6em;">
                    <input type="text" name="name2" value="<?=$this->special['name2']?>" class=" form-control" style="width:6em;">
                  </td>
                </tr>
                <tr>
                  <th>フリガナ</th>
                  <td class="form-inline">
                    <input type="text" name="kana" value="<?=$this->special['kana']?>" class=" form-control kana" style="width:6em;">
                    <input type="text" name="kana2" value="<?=$this->special['kana2']?>" class=" form-control kana" style="width:6em;">
                  </td>
                </tr>
                <tr>
                  <th>メール</th>
                  <td><input type="text" name="mail" value="<?=$this->special['mail']?>" class=" form-control email"></td>
                </tr>
                <tr>
                  <th>性別</th>
                  <td class="form-inline">
                    <select name="" class="form-control">
                    <?php foreach(array(1=>"女性",2=>"男性") as $k=>$v):?>
                    <?php if($k == $this->special['sex']):?>
                    <option value="<?=$k?>" selected><?=$v?></option>
                    <?php else:?>
                    <option value="<?=$k?>"><?=$v?></option>
                    <?php endif;?>
                    <?php endforeach;?>
                    </select>
                  </td>
                </tr>
                <tr>
                  <th>生年月日</th>
                  <td class="form-inline">
                    <select name="birthY"  class=" form-control" style="width:4em;">
                      <?php
                      $y = array("0"=>"選択してください");
                      for($i = 1900;$i<(date("Y")+1);$i++){
                        $y[] = $i;
                      }
                      foreach($y as $v){
                        if($v == $this->special['birthY']){
                          echo '<option value="'.$v.'" selected>'.$v.'</option>';
                        }elseif($v==date("Y")-36){
                        echo '<option value="'.$v.'" selected>'.$v.'</option>';
                          }else{
                        echo '<option value="'.$v.'">'.$v.'</option>';
                        }
                      }
                      ?>
                    </select>年
                    <select name="birthM"  class=" form-control" style="width:4em;">
                      <?php
                      $y = array("0"=>"選択してください");
                      for($i = 1;$i<13;$i++){
                        $y[$i] = $i;
                      }
                      foreach($y as $v){
                        if($v == $this->special['birthM']){
                          echo '<option value="'.$v.'" selected>'.$v.'</option>';
                        }else{
                          echo '<option value="'.$v.'">'.$v.'</option>';
                        }
                      }
                      ?>
                    </select>月
                    <select name="birthD"  class=" form-control" style="width:4em;">
                      <?php
                      $y = array("0"=>"選択してください");
                      for($i = 1;$i<32;$i++){
                        $y[$i] = $i;
                      }
                      foreach($y as $v){
                        if($v == $this->special['birthD']){
                          echo '<option value="'.$v.'" selected>'.$v.'</option>';
                        }else{
                          echo '<option value="'.$v.'">'.$v.'</option>';
                        }
                      }
                      ?>
                    </select>日
                  </td>
                </tr>
                <tr>
                  <th>電話番号</th>
                  <td class="form-inline">
                    <input type="text" name="tel" value="<?=$this->special['tel']?>" class=" form-control" style="width:4em;">-
                    <input type="text" name="tel2" value="<?=$this->special['tel2']?>" class=" form-control" style="width:4em;">-
                    <input type="text" name="tel3" value="<?=$this->special['tel3']?>" class=" form-control" style="width:4em;">
                  </td>
                </tr>
                <tr>
                  <th>携帯電話</th>
                  <td class="form-inline">
                    <input type="text" name="mtel" value="<?=$this->special['mtel']?>" class=" form-control" style="width:4em;">-
                    <input type="text" name="mtel2" value="<?=$this->special['mtel2']?>" class=" form-control" style="width:4em;">-
                    <input type="text" name="mtel3" value="<?=$this->special['mtel3']?>" class=" form-control" style="width:4em;">
                  </td>
                </tr>
                <tr>
                  <th>住所<span id="l-008"></span></th>
                  <td>
                    <p class="form-inline">
                      〒<input type="text" name="zip" value="<?=$this->special['zip']?>" class=" form-control" style="width:4em;">-
                      <input type="text" name="zip2" value="<?=$this->special['zip2']?>" class=" form-control" style="width:4em;">
                    </p>
                    <p class="form-inline">
                      <select name="pref" class="span3 required form-control">
                        <option value="">選択</option>
                        <?php foreach($this->pref as $v):?>
                        <?php if($v['id'] == $this->special['pref']):?>
                        <option value="<?=$v['id']?>" selected><?=$v['name']?></option>
                        <?php else:?>
                        <option value="<?=$v['id']?>"><?=$v['name']?></option>
                        <?php endif;?>
                        <?php endforeach;?>
                      </select>
                    </p>
                    <p><input type="text" name="addr" value="<?=$this->special['addr']?>" id="f-008" class="required form-control"></p>
                    <p><input type="text" name="addr2" value="<?=$this->special['addr2']?>" class="form-control"></p>
                    <input type="hidden" name="demand" value="1" />
                  </td>
                </tr>
                <!--tr>
                  <th>ステータス</th>
                  <td class="form-inline">
                    <select name="active" class="form-control" id="f-011">
                      <option value="">選択</option>
                      <?php
                        $arr = array(0=>"無効",1=>"有効");
                        foreach($arr as $k=>$v){
                          if($this->special['active'] == $k){
                            echo "<option value=\"{$k}\" selected>".$v."</option>";
                          }else{
                            echo "<option value=\"{$k}\">".$v."</option>";
                          }
                        }
                      ?>
                    </select>
                  </td>
                </tr-->
                <tr>
                  <th>パスワード</th>
                  <td>
                    <p><input type="password" name="pw" value="<?=$this->special['pw']?>" id="f-013" class="required form-control" disabled></p>
                    <div class="checker" id="uniform-optionsCheckbox">
                      <label class="uniform">
                        <span><input class="uniform_on" type="checkbox" name="pwactive" id="pwactive" value="1"></span>パスワードを編集する場合は、このチェックボックスにチェックしてください。
                      </label>
                    </div>
                    <p>※パスワードは暗号化されて保存されています。</p>
                  </td>
                </tr>
              </tbody>
              </table>
              <input type="hidden" name="id" value="<?=$this->special['id']?>">
              <input type="hidden" name="parent" value="<?=$this->special['parent']?>">
            </form>
            <div class="form-actions">
              <button class="btn btn-large btn-block btn-primary" id="sub2">編集</button>
            </div>
            <!--中身-->
          </div>
        </div>
      </section>
    </div>
    <div role="tabpanel" class="tab-pane fade active in" id="tab_content3" aria-labelledby="profile-tab">
      <section>
        <div class="x_panel">
          <div class="x_title">
            <h2>アクティビティ</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <!--中身-->
            <div id="log"></div>
            <!--中身-->
          </div>
        </div>
      </section>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="tab_content5" aria-labelledby="profile-tab">
      <section>
        <div class="x_panel">
          <div class="x_title">
            <h2>請求・入金</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <!--中身-->
						<?php $i=0; foreach($this->order as $v):$i++;?>
						<div class="row" <?php if($i%2==1) echo " style=\"background-color:#f9f9f9;line-height:50px;\""?>>
							<div class="col-xs-6">
								<label><?=$v['year']?>年<?=$v['month']?>月分</label>
                <?php if($v['check_payment_end']):?>
                  <span class="label label-danger label-sm">入金済み</span>
                <?php endif;?>
							</div>
							<div class="col-xs-6 text-right">
                <form action="<?=BASEURL?>/admin/order/paper" method="post" target="_blank">
                  <input type="hidden" name="id" value="<?=$v['id']?>">
                  <input type="hidden" name="kind" value="5">
                  <input type="hidden" name="date" value="<?=date("Y-m-d")?>">
                  <input type="hidden" name="camp" value="1">
                  <input type="submit" class="btn btn-primary btn-sm" value="請求書">
                </form>
							</div>
						</div>
						<?php endforeach;?>
            <!--中身-->
          </div>
        </div>
      </section>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="tab_content4" aria-labelledby="profile-tab">
      <section>
        <div class="x_panel">
          <div class="x_title">
            <h2>強制停止</h2>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            <!--中身-->
						<?php if($this->detail['stop'] == "0000-00-00 00:00:00"):?>
            <button type="button" class="btn btn-danger" id="stopAcount">
							このアカウントを強制停止する
						</button>
						<?php else:?>
            <button type="button" class="btn btn-danger" id="restartAcount">
							強制停止を解除する
						</button>
						<?php endif;?>
            <!--中身-->
          </div>
        </div>
      </section>
    </div>
  </div>
</div>
<input type="hidden" id="taxratio" value="<?=$this->tax[0]['ratio']?>">
<input type="hidden" id="taxrule" value="<?=$this->tax[0]['rule']?>">
<script>
var date = new Date();
var year = date.getFullYear();
var month = date.getMonth()+1;
var lastDayOfMonth = new Date(year,month,0).getDate();

var prev = new Date(year,date.getMonth()-1,1);
var prevyear = prev.getFullYear();
var prevmonth = prev.getMonth()+1;

var next = new Date(year,date.getMonth()+1,1);
var nextyear = next.getFullYear();
var nextmonth = next.getMonth()+1;

$(function(){
	//強制停止
	$("#stopAcount").on("click",function(){
	  var id = $("[name=parent]").val();
		if(window.confirm("本当に停止してよろしいですか？")){
			$.post("<?=BASEURL?>/api/user/stop/",{id:id},function(data){
				console.log(data);
				alert("停止しました。");
				location.reload();
			});
		}
	});
	//強制停止の解除
	$("#restartAcount").on("click",function(){
	  var id = $("[name=parent]").val();
		if(window.confirm("強制停止を解除してよろしいですか？")){
			$.post("<?=BASEURL?>/api/user/restart/",{id:id},function(data){
				console.log(data);
				alert("停止しました。");
				location.reload();
			});
		}
	});
  //アクティビティログ
  parseDailyreport(year,month);

	$("#sub").on("click",function(){
		if(window.confirm("アカウント編集を行います。内容を変更される場合はキャンセルボタンを押してください。")){
			$("#form").submit();
		}
	});
	$("#sub2").on("click",function(){
		if(window.confirm("ユーザー情報編集を行います。内容を変更される場合はキャンセルボタンを押してください。")){
			$("#form2").submit();
		}
	});
	$("#pwactive").on("click",function(){
		if($(this).attr("checked",true)){
			$("[name=pw]").attr("disabled",false).val("").focus();
		}else{
			$("[name=pw]").attr("disabled",true);
		}
	});
  $('.copy_code').click(function() {
    var clipboard = $('<textarea></textarea>');
    clipboard.addClass('clipboard');
    clipboard.html( $(this).prev('code').html() );
    $(this).append(clipboard);
    clipboard.select();
    document.execCommand('copy');
    clipboard.remove();
    alert("コピーしました");
  });
});

function parseDailyreport(year,month){
  var id = $("[name=parent]").val();
  $.post("<?=BASEURL?>/api/outsource/calc",{id:id,year:year,month:month},function(data){
    var data = JSON.parse(data);
    var str = "";
    str+= '<div class="row form-actions">';
    //前へはお試し終了日より前は表示しない
    var TrialEnd = new Date(data[1][2]);
    var ym = TrialEnd.getFullYear()+""+zeroPadding(TrialEnd.getMonth()+1,2);
    var thisym = year+""+zeroPadding(month,2);
    var today = new Date();
    var todayYm = today.getFullYear()+""+zeroPadding(today.getMonth()+1,2);
		/*
    if(ym < thisym){
      str+= '<p class="col-sm-4 text-left"><a href="javascript:void(0);" class="getDailyreport btn btn-default" data-year="'+prevyear+'" data-month="'+prevmonth+'" data-date="1"> '+prevyear+'/'+prevmonth+'</a></p>';
    }else{
      str+= '<p class="col-sm-4 text-left"></p>';
    }
		*/
    str+= '<h4 class="col-sm-4 text-center"><strong>'+year+'年'+month+'月の現在の請求予定額</strong></h4>';
    if(thisym < todayYm){
      str+= '<p class="col-sm-4 text-right"><a href="javascript:void(0);" class="getDailyreport btn btn-default" data-year="'+nextyear+'" data-month="'+nextmonth+'" data-date="1">'+nextyear+'/'+nextmonth+'</a></p>';
    }else{
      str+= '<p class="col-sm-4 text-left"></p>';
    }
    str+= '</div>';
    str+= '<h4>人数集計：';
    var total = 0;
    for(var i =0;i<data[0].length;i++){
      if(data[0][i]['trial'] == null){
        data[0][i]['trial'] = 0;
      }
      if(data[0][i]['lastlast'] == null){
        data[0][i]['lastlast'] = 0;
      }
      if(data[0][i]['last'] >0){
        data[0][i]['last'] = 1;
      }else if(data[0][i]['last'] == null){
        data[0][i]['last'] = 0;
      }else{
        data[0][i]['last'] = 0;
      }
      total = total+(data[0][i]['trial']*1)+(data[0][i]['lastlast']*1)+data[0][i]['last'];
    }
    str+= "一般："+total+"人";
    var total2 = 0;
    for(var i =0;i<data[2].length;i++){
      if(data[2][i]['trial'] == null){
        data[2][i]['trial'] = 0;
      }
      if(data[2][i]['lastlast'] == null){
        data[2][i]['lastlast'] = 0;
      }
      if(data[2][i]['last'] >0){
        data[2][i]['last'] = 1;
      }else if(data[2][i]['last'] == null){
        data[2][i]['last'] = 0;
      }else{
        data[2][i]['last'] = 0;
      }
      total2 = total2+(data[2][i]['trial']*1)+(data[2][i]['lastlast']*1)+data[2][i]['last'];
    }
    str+= "　外注："+total2+"人";
    str+= '</h4>';
    str+= '<h3>基本料金</h3>';
		var plan = $("#plan").val();
		$.post("<?=BASEURL?>/api/user/plan",{plan:plan},function(data){
			var planArr = JSON.parse(data);
			planArr['staffUnit'] = planArr['staffUnit']*1;
			console.log(planArr['staffUnit']);
			var staffTotal = total*planArr['staffUnit'];
			var outsourseTotal = total2*(planArr.outsourceUnit*1);
			var TotalTotal = staffTotal+outsourseTotal;
			var taxRatio = $("#taxratio").val();
			var taxRule = $("#taxrule").val();


			str+='<table class="table table-striped table-responcive">';
			str+='<tbody>';
			str+='<tr>';
			str+='<th>';
			str+='一般スタッフ';
			str+='</th>';
			str+='<td class="text-right">';
			str+=+number_format(total)+'人';
			str+='</td>';
			str+='<td class="text-right">';
			str+=+planArr['staffUnit']+'円';
			str+='</td>';
			str+='<td class="text-right">';
			str+=number_format(staffTotal)+'円';
			str+='</td>';
			str+='</tr>';
			str+='<tr>';
			str+='<th>';
			str+='外注スタッフ';
			str+='</th>';
			str+='<td class="text-right">';
			str+=+number_format(total2)+'人';
			str+='</td>';
			str+='<td class="text-right">';
			str+=+number_format(planArr.outsourceUnit)+'円';
			str+='</td>';
			str+='<td class="text-right">';
			str+= number_format(outsourseTotal) + '円';
			str+='</td>';
			str+='</tr>';
			str+='<tr>';
			str+='<th>';
			str+='基本料金 小計';
			str+='</th>';
			str+='<td class="text-right" colspan="3">';
			str+=number_format(TotalTotal)+'円';
			str+='</td>';
			str+='</tr>';
			var itemTotal = TotalTotal;
			str+='</tbody>';
			str+='</table>';
			str+='<h3>オプション</h3>';
      var optionTotal = 0;
			$.post("<?=BASEURL?>/api/user/opt",{id:id},function(data){
				var opt = JSON.parse(data);
				console.log(opt);
				//オプションを表示
				var arra = new Array();
				for(var i=0;i<opt.length;i++){
					if(opt[i]['user'] == 1){
						arra.push(opt[i]);
					}
				}
				if(arra.length ==0){
					//申込済みのオプションがない場合
					str+='オプションの申し込みはありません';
				}else{
					console.log(arra.length);
					//申込済みのオプションがある場合
					str+='<table class="table">';
					str+='<tbody>';
					for(var i=0;i<arra.length;i++){
            var optionAmount = 0;
						str+='<tr>';
						str+='<th>'+arra[i]['name']+'<th>';
						var t = arra[i]['first'].split(/[- :]/);
						if(year == t[0] && month+1 == t[1]*1){
							str+='<td class="text-right">初期費用</td>';
							str+='<td colspan="3" class="text-right">'+arra[$i]['initialCost']+'円</td>';
              TotalTotal = TotalTotal+arra[$i]['initialCost']*1;
              optionAmount = optionAmount+arra[$i]['initialCost']*1;
						}else{
							str+='<td colspan="3"></td>';
						}
						str+='</tr>';
						if(arra[i]['staffUnit'] >0 ){
							str+='<tr>';
							str+='<th><th>';
							str+='<td colspan="2">一般スタッフ</td>';
							str+='<td class="text-right">＠'+number_format(arra[i]['staffUnit'])+'円</td>'
							str+='<td class="text-right">'+total+'人</td>'
							str+='<td class="text-right">'+number_format(total*arra[i]['staffUnit'])+'円</td>';
              TotalTotal = TotalTotal+(total*arra[i]['staffUnit']*1);
              optionAmount = optionAmount+(total*arra[i]['staffUnit']*1);
							str+='</tr>';
						}
						if(arra[i]['outsourceUnit'] >0 ){
							str+='<tr>';
							str+='<th><th>';
							str+='<td colspan="2">外注スタッフ</td>';
							str+='<td class="text-right">＠'+number_format(arra[i]['outsourceUnit'])+'円</td>'
							str+='<td class="text-right">'+total2+'人</td>'
							str+='<td class="text-right">'+number_format(total2*arra[i]['outsourceUnit'])+'円</td>';
              TotalTotal = TotalTotal+(total2*arra[i]['outsourceUnit']*1);
              optionAmount = optionAmount+(total2*arra[i]['outsourceUnit']*1);
							str+='</tr>';
						}
						if(arra[i]['fee'] >0 ){
							str+='<tr>';
							str+='<th><th>';
							str+='<td colspan="2">月額費用</td>';
							str+='<td colspan="3" class="text-right">'+number_format(arra[i]['fee'])+'円</td>';
              TotalTotal = TotalTotal+(arra[i]['fee']*1);
              optionAmount = optionAmount+(arra[i]['fee']*1);
							str+='</tr>';
						}
						str+='<tr>';
						str+='<td colspan="3" class="text-right">'+arra[i]['name']+'合計</td>';
						str+='<td colspan="3" class="text-right">'+number_format(optionAmount)+'円</td>';
						str+='</tr>';

					}
					str+='</tbody>';
					str+='</table>';
				}
				console.log(TotalTotal);
				str+='<h3>合計</h3>';
				str+='<table class="table">';
				str+='<tbody>';
				str+='<tr>';
				str+='<th>';
				str+='小計';
				str+='</th>';
				str+='<td class="text-right" colspan="3">';
				str+=number_format(TotalTotal)+'円';
				str+='</td>';
				str+='</tr>';
				str+='<tr>';
				str+='<th>';
				str+='消費税';
				str+='</th>';
				str+='<td class="text-right" colspan="3">';
				if(taxRule == 0){
					//四捨五入
					var taxAmount = Math.round(TotalTotal*taxRatio/100);
				}else if(taxRule == 1){
					var taxAmount = Math.ceil(TotalTotal*taxRatio/100);
				}else if(taxRule == 2){
					var taxAmount = Math.floor(TotalTotal*taxRatio/100);
				}
				str+=number_format(taxAmount)+'円';
				str+='</td>';
				str+='</tr>';
				str+='<tr>';
				str+='<th>';
				str+='合計';
				str+='</th>';
				str+='<td class="text-right" colspan="3">';
				str+=number_format(taxAmount+TotalTotal)+'円';
				str+='</td>';
				str+='</tr>';
				str+='</tbody>';
				str+='</table>';
				$("#log").empty().append(str);
			});
		});



  });
}
$(document).on("click",".getDailyreport",function(){
  var thisYear = $(this).data("year");
  var thisMonth = $(this).data("month");
  var thisDate = $(this).data("date");
  var date = new Date(thisYear,thisMonth-1,thisDate);
  year = date.getFullYear();
  month = date.getMonth()+1;
  prev = new Date(year,date.getMonth()-1,1);
  prevyear = prev.getFullYear();
  prevmonth = prev.getMonth()+1;
  next = new Date(year,date.getMonth()+1,1);
  nextyear = next.getFullYear();
  nextmonth = next.getMonth()+1;
  parseDailyreport(year,month);
});
function zeroPadding(num,length){
    return ('0000000000' + num).slice(-length);
}
function number_format(num) {
	return num.toString().replace(/([0-9]+?)(?=(?:[0-9]{3})+$)/g , '$1,');
}
</script>
