<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <title>ログイン</title>
    <!-- Bootstrap -->
    <link href="<?=BASEURL?>/theme/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="<?=BASEURL?>/theme/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
    <link href="<?=BASEURL?>/theme/assets/styles.css" rel="stylesheet" media="screen">
     <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="<?=BASEURL?>/theme/vendors/modernizr-2.6.2-respond-1.1.0.min.js"></script>
  </head>
  <body id="login">
    <div class="container">
    <?php echo $this->layout()->content; ?>
    </div> <!-- /container -->
    <script src="<?=BASEURL?>/theme/vendors/jquery-1.9.1.min.js"></script>
    <script src="<?=BASEURL?>/theme/bootstrap/js/bootstrap.min.js"></script>
  </body>
</html>