<li><a href="<?=BASEURL?>/login/index/logout/"><i class="fa fa-sign-out pull-right"></i>ログアウト</a></li>
<li><a href="<?=BASEURL?>/admin/settings/company/"><i class="fa fa-building"></i>　会社設定</a></li>
<li><a href="<?=BASEURL?>/admin/settings/global/"><i class="fa fa-building"></i>　グローバル設定</a></li>
<li><a href="<?=BASEURL?>/admin/settings/mail/"><i class="fa fa-building"></i>　メール設定</a></li>
<li><a href="<?=BASEURL?>/admin/settings/payment/"><i class="fa fa-building"></i>　決済方法設定</a></li>
