<ul class="nav side-menu">
    <li><a href="<?=BASEURL?>/admin/"><i class="fa fa-tachometer"></i>　ダッシュボード</a></li>
    <li><a href="<?=BASEURL?>/admin/user/"><i class="fa fa-user"></i>　ユーザー管理</a></li>
    <li><a href="<?=BASEURL?>/admin/plan/"><i class="fa fa-user"></i>　プラン管理</a></li>
    <li>
        <a><i class="fa fa-gift"></i>　ヘルプ管理<span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu" style="display: none">
            <li><a href="<?=BASEURL?>/admin/help/">　ヘルプ一覧</a></li>
            <li><a href="<?=BASEURL?>/admin/help/category/">　ヘルプページ</a></li>
        </ul>
    </li>
</ul>