

		<footer>
			<div class="section-sm bg_yellow">
				<div class="container">
					<div class="row col-spacing-20">
						<div class="col-12 col-sm-8 col-md-6 col-lg-6">
							<h5>一般社団法人 東彼杵郡医師会</h5>
                            <p>〒859-3615<br>
                            長崎県東彼杵郡川棚町下組郷17番地7<br>
                            TEL：0956-82-5700</p>
						</div>
						<div class="col-12 col-sm-4 col-md-6 col-lg-3">
							<ul class="list-dash">
								<li><a href="<?=BASEURL?>/content">お知らせ</a></li>
                                <li><a href="../contents/00_faq.html">よくある質問</a></li>
								<li><a href="../contents/00_link.html">リンク集</a></li>
							</ul>
						</div>
						<div class="col-12 col-sm-6 col-md-4 col-lg-3">
                            <a class="button button-lg button-outline-dark-2 button-fullwidth" href="<?=BASEURL?>/mail"><i class="far fa-paper-plane"></i> お問い合わせ</a>
                            <a class="button button-lg button-outline-dark-2 button-fullwidth margin-top-20" href="<?=BASEURL?>/signin/"><i class="fas fa-user margin-right-10"></i> 会員ログイン</a>
						</div>
					</div><!-- end row(1) -->

					<hr class="margin-top-30 margin-bottom-30">

					<div class="row col-spacing-10">
						<div class="col-12 text-center">
							<p>&copy; Touhi Medical Association.<br>このサイトの推奨ブラウザ：Google Chrome、Safari、Firefox、Microsoft Edge</p>
						</div>
					</div><!-- end row(2) -->
				</div><!-- end container -->
			</div>
		</footer>

		<!-- Scroll to top button -->
		<div class="scrolltotop">
			<a class="button-circle button-circle-sm button-circle-dark" href="#"><i class="ti-arrow-up"></i></a>
		</div>
		<!-- end Scroll to top button -->

		<!-- ***** JAVASCRIPTS ***** -->
		<script src="../assets/plugins/jquery.min.js"></script>
		<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"></script>
		<script src="../assets/plugins/plugins.js"></script>
		<script src="../assets/js/functions.js"></script>
	<?=$this->add_script?>
	</body>
</html>
