<!DOCTYPE html>
<html lang="ja">
	<head>

		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=G-JE1PVB5EYF"></script>
		<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'G-JE1PVB5EYF');
		</script>

		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
        <meta name="keywords" content="">
				<base href="https://www.touhi-ishikai.jp/search/">
		<title><?=strip_tags($this->title)?></title>
		<script>var baseurl = 'https://www.touhi-ishikai.jp/search';</script>

		<!-- Favicon -->
        <link href="../assets/images/favicon.png" rel="shortcut icon">
		<!-- CSS -->
		<link href="../assets/css/custom.css" rel="stylesheet">
        <link href="../assets/plugins/bootstrap/bootstrap.min.css" rel="stylesheet">
		<link href="../assets/plugins/owl-carousel/owl.carousel.min.css" rel="stylesheet">
		<link href="../assets/plugins/owl-carousel/owl.theme.default.min.css" rel="stylesheet">
		<link href="../assets/plugins/magnific-popup/magnific-popup.min.css" rel="stylesheet">
		<link href="../assets/plugins/sal/sal.min.css" rel="stylesheet">
		<link href="../assets/css/theme.css" rel="stylesheet">
		<!-- Fonts/Icons -->
		<link href="../assets/plugins/font-awesome/css/all.css" rel="stylesheet">
		<link href="../assets/plugins/themify/themify-icons.min.css" rel="stylesheet">
		<link href="../assets/plugins/simple-line-icons/css/simple-line-icons.css" rel="stylesheet">
	</head>
	<body data-preloader="2">

		<header class="">
			<div class="bg_yellow padding-y-10">
				<div class="container">
					<div class="row">
						<div class="col-6">
							<span><i class="fas fa-phone margin-right-10"></i>0956-82-5700</span>
						</div>
						<div class="col-6 text-right">
							<ul class="list-inline">
								<li><i class="fas fa-user margin-right-10"></i><a href="<?=BASEURL?>/signin/">ログイン</a></li>
							</ul>
						</div>
					</div><!-- end row -->
				</div><!-- end container -->
			</div>

			<nav class="navbar navbar-sticky">
				<div class="container">
					<a class="navbar-brand" href="../index.html">
					<img src="../assets/images/logo.png" alt="一般社団法人 東彼杵郡医師会"/>
                    </a>
					<ul class="nav">
						<li class="nav-item">
							<a class="nav-link" href="../index.html">HOME</a>
						</li>
						<li class="nav-item nav-dropdown">
							<a class="nav-link" href="#">概 要</a>
				        	<ul class="dropdown-menu">
								<li><a href="../contents/01_message.html"><i class="fas fa-arrow-right txt_lg"></i> 会⾧挨拶</a></li>
								<li><a href="../contents/01_map.html"><i class="fas fa-arrow-right txt_lg"></i> 事務局マップ</a></li>
								<!--li><a href="../assets/data/touban.pdf" target="_blank"><i class="fas fa-arrow-right txt_lg"></i> 当番医のご案内</a></li-->
								<li><a href="<?=BASEURL?>/content"><i class="fas fa-arrow-right txt_lg"></i> お知らせ</a></li>
								<li><a href="../assets/data/touban.pdf"><i class="fas fa-arrow-right txt_lg"></i> 休日在宅当番医</a></li>
							</ul>
						</li>
						<li class="nav-item nav-dropdown">
							<a class="nav-link" href="#">たんぽぽ</a>
				        	<ul class="dropdown-menu">
								<li><a href="../contents/02_message.html"><i class="fas fa-arrow-right txt_lg"></i> センター⾧挨拶</a></li>
								<li><a href="../contents/02_about_tanpopo.html"><i class="fas fa-arrow-right txt_lg"></i> たんぽぽとは</a></li>
							</ul>
						</li>
						<li class="nav-item nav-dropdown">
							<a class="nav-link" href="#">講座・研修</a>
				        	<ul class="dropdown-menu">
								<li><a href="../contents/03_activities.html"><i class="fas fa-arrow-right txt_lg"></i> 活動報告</a></li>
								<li><a href="../contents/03_seminar.html"><i class="fas fa-arrow-right txt_lg"></i> セミナーのご案内</a></li>
							</ul>
						</li>
						<!--li class="nav-item">
							<a class="nav-link" href="../contents/04_insurance.html">介護保険</a>
						</li-->
						<li class="nav-item nav-dropdown dropdown-active">
							<a class="nav-link" href="#">医療・介護</a>
							<ul class="dropdown-menu dropdown-menu-show">
								<li><a href="../assets/data/yoboujigyou.pdf" target="_blank"><i class="fas fa-arrow-right txt_lg"></i> 介護事業（サロン一覧）</a></li>
								<li><a href="../05_hospital.html"><i class="fas fa-arrow-right txt_lg"></i> 近隣の総合病院</a></li>
								<li><a href="../05_insurance.html"><i class="fas fa-arrow-right txt_lg"></i> 介護保険の流れ</a></li>
							</ul>
						</li>
						<li class="nav-item	">
							<a class="nav-link" href="../contents/06_download.html">様式ダウンロード</a>
						</li>

						<!--li class="nav-item">
							<a class="nav-link" href="<?=BASEURL?>/mail">お問い合わせ</a>
						</li-->
					</ul><!-- end nav -->
					<!-- Nav Toggle button -->
					<button class="nav-toggle-btn">
			            <span class="lines"></span>
			        </button><!-- toggle button will show when screen resolution is less than 992px -->
				</div><!-- end container -->
			</nav><!-- end navbar -->
		</header>

        <!-- Title section -->
		<div class="section-xs title_back bg-image" data-bg-src="../assets/images/titleback.png">
			<div>
				<div class="container text-center">
					<h1 class="font-weight-light margin-0"><?=$this->title?></h1>
          <ul class="list-inline-dash">
						<?=$this->bread?>
					</ul>
				</div><!-- end container -->
			</div>
		</div>
        <!-- end:Title section -->
