                <div class="span3" id="sidebar">
                    <ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
                        <li<?php if($this->controller == "index") echo ' class="active"'?>>
                            <a href="<?=BASEURL?>/member/">ダッシュボード</a>
                        </li>
                        <li<?php if($this->controller == "image") echo ' class="active"'?>>
                            <a href="<?=BASEURL?>/member/image/">画像管理</a>
                        </li>
                    </ul>
                </div>