<!-- 商品詳細情報　-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>商品カテゴリ詳細</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        
        <p>下記の内容でヘルプページ登録を行いました。編集及び削除は、ヘルプページ管理画面より行えます。</p>
        <p><a href="<?=BASEURL?>/admin/help/category" class="btn btn-primary">ヘルプページ管理画面へ進む</a></p>
        <p><a href="<?=BASEURL?>/admin/help/categorydetail/?id=<?=$this->data['id']?>" class="btn btn-info">ヘルプページ詳細へ進む</a></p>
        <br><br>
        
          <div class="data-table">
            <form action="<?=BASEURL?>/admin/help/categoryregistrerfinish/" method="post" id="form">
              <table class="table table-striped table-responcive">
                <tbody>
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                    <th>ページ名<span id="l-002"></span></th>
                    <td><?=$this->data['name']?></td>
                 </tr>
                <!--tr>
                    <th>タイトル<span id="l-005"></span></th>
                    <td><?=$this->data['title']?></td>
                 </tr-->
                <tr>
                    <th>ディスクリプション<span id="l-006"></span></th>
                    <td><?=$this->data['description']?></td>
                 </tr>
                <tr>
                    <th>親カテゴリ</th>
                    <td><?php foreach($this->category as $v):?>
                    		<?php if($v['id'] == $this->data['p']) echo $v['name'];?>
                    	<?php endforeach;?>
                    </td>
                 </tr>
                <!--tr>
                    <th>本文<span id="l-004"></span></th>
                    <td>
                    		<?=$this->data['html']?>
                    </td>
                 </tr>
                <tr>
                    <th>表示・非表示<span id="l-010"></span></th>
                    <td>
                <?php
					$arr = array(0=>"表示",1=>"非表示");
					foreach($arr as $k=>$v){
				 		if($this->data['display'] == $k){
							echo $v;
						}
					}?>
                    </td>
                 </tr>
            	<tr>
                	<td>PC用バナー</td>
                	<td>
                    <span id="preview">
                    <?php if($this->data['thumb']):?>
                        <img src="<?=BASEURL?><?=$this->data['thumb']?>" style="width:120px;height:auto;">
                        <?php endif;?>
                    </span>
                  </td>
               </tr>
            	<tr>
                	<td>スマホ用バナー</td>
                	<td>
                    <span id="preview2">
                    <?php if($this->data['thumb2']):?>
                        <img src="<?=BASEURL?><?=$this->data['thumb2']?>" style="width:120px;height:auto;">
                        <?php endif;?>
                    </span>
                  </td>
               </tr-->
                </tbody>
              </table>
            </form>
            </div>
        
              <div class="form-actions">
                <form action="<?=BASEURL?>/admin/help/categorydetail/" method="get">
                    <input type="hidden" name="id" value="<?=$this->data['id']?>">
                    <button type="submit" class="btn btn-large btn-block btn-success">詳細</button>
                </form>
                <form action="<?=BASEURL?>/admin/help/categoryupdate/" method="get">
                    <input type="hidden" name="id" value="<?=$this->data['id']?>">
                    <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
                </form>
                <form action="<?=BASEURL?>/admin/help/delete/" method="post">
                    <input type="hidden" name="ids" value="<?=$this->data['id']?>">
                    <button type="button" class="btn btn-large btn-block btn-danger" id="deleteAll">削除</button>
                </form>
              </div>
		<!--中身-->
        </div>
      </div>
    </div>
</section>

<script>
	$("#deleteAll").on("click",function(){
		if(window.confirm("本当に削除してもいいですか？")){
			var ck = $('input[name=ids]').val();
			var url = "<?=BASEURL?>/api/help/catedelete/";
			$.post(url,{ids:ck},function(data){
				if(data = "OK"){
					location.href = "<?=BASEURL?>/admin/help/category";
				}
			});
		}
	});
</script>     