<!-- ヘルプ詳細情報　-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>ヘルプ詳細情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_help">
		<!--中身-->
        
          <div class="data-table">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                    <th>ヘルプ名</th>
                    <td><?php foreach($this->category as $v):?>
                    		<?php if($v['id'] == $this->data['name']) echo $v['name'];?>
                    	<?php endforeach;?></td>
                 </tr>
                <tr>
                    <th>タイトル</th>
                    <td><?=$this->data['title']?></td>
                 </tr>
                <tr>
                    <th>コード</th>
                    <td><?=$this->data['code']?></td>
                 </tr>
                <tr>
                    <th>本文</th>
                    <td><?=$this->data['html']?></td>
                 </tr>
            	<!--tr>
                	<td>PC用バナー</td>
                	<td>
                    <span id="preview">
                    <?php if($this->data['thumb']):?>
                        <img src="<?=BASEURL?><?=$this->data['thumb']?>" style="width:120px;height:auto;">
                        <?php endif;?>
                    </span>
                  </td>
               </tr>
            	<tr>
                	<td>スマホ用バナー</td>
                	<td>
                    <span id="preview2">
                    <?php if($this->data['thumb2']):?>
                        <img src="<?=BASEURL?><?=$this->data['thumb2']?>" style="width:120px;height:auto;">
                        <?php endif;?>
                    </span>
                  </td>
               </tr-->
                </tbody>
              </table>
            </div>
            <div class="form-actions">
                <form action="<?=BASEURL?>/admin/help/update/" method="get">
                    <input type="hidden" name="id" value="<?=$this->data['id']?>">
                    <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
                </form>
                <form>
                    <input type="hidden" name="ids" value="<?=$this->data['id']?>">
                    <button type="button" class="btn btn-large btn-block btn-danger" id="deleteAll">削除</button>
                </form>
            </div>
        
          
		<!--中身-->
        </div>
      </div>
    </div>
</section>


<script>
	$("#deleteAll").on("click",function(){
		if(window.confirm("本当に削除してもいいですか？")){
			var ck = $('input[name=ids]').val();
			var url = "<?=BASEURL?>/api/help/delete/";
			$.post(url,{ids:ck},function(data){
				if(data = "OK"){
					location.href = "<?=BASEURL?>/admin/help/";
				}
			});
		}
	});
	/*
	//HTMLを追加
	$("#htmlAdd").on("click",function(){
		if(window.confirm("記載された内容でHTMLを登録します。よろしいですか？")){
			$("form[name=html]").submit();
		}
	});
	*/
</script>     
