
<!-- 商品詳細情報　-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>ヘルプ登録完了</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_help">
		<!--中身-->
        <p>下記の内容でヘルプ登録を行いました。編集及び削除は、ヘルプ管理画面より行えます。</p>
        <p><a href="<?=BASEURL?>/admin/help/" class="btn btn-primary">ヘルプ管理画面へ進む</a></p>
        <p><a href="<?=BASEURL?>/admin/help/detail/?id=<?=$this->data['id']?>" class="btn btn-info">ヘルプ詳細へ進む</a></p>
        <p><a href="<?=BASEURL?>/admin/help/registrer" class="btn btn-success">続けてヘルプを登録する</a></p>
        <br><br>
        
          <div class="data-table">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                    <th>ヘルプ名</th>
                    <td><?php foreach($this->category as $v):?>
                    		<?php if($v['id'] == $this->data['name']) echo $v['name'];?>
                    	<?php endforeach;?></td>
                 </tr>
                <tr>
                    <th>タイトル</th>
                    <td><?=$this->data['title']?></td>
                 </tr>
                <tr>
                    <th>コード</th>
                    <td><?=$this->data['code']?></td>
                 </tr>
                <tr>
                    <th>本文</th>
                    <td><?=$this->data['html']?></td>
                 </tr>
            	<!--tr>
                	<td>PC用バナー</td>
                	<td>
                    <span id="preview">
                    <?php if($this->data['thumb']):?>
                        <img src="<?=BASEURL?><?=$this->data['thumb']?>" style="width:120px;height:auto;">
                        <?php endif;?>
                    </span>
                  </td>
               </tr>
            	<tr>
                	<td>スマホ用バナー</td>
                	<td>
                    <span id="preview2">
                    <?php if($this->data['thumb2']):?>
                        <img src="<?=BASEURL?><?=$this->data['thumb2']?>" style="width:120px;height:auto;">
                        <?php endif;?>
                    </span>
                  </td>
               </tr-->
                </tbody>
              </table>
            </div>
            <div class="form-actions">
                <form action="<?=BASEURL?>/admin/help/detail/" method="get">
                    <input type="hidden" name="id" value="<?=$this->data['id']?>">
                    <button type="submit" class="btn btn-large btn-block btn-info">詳細</button>
                </form>
                <form action="<?=BASEURL?>/admin/help/update/" method="get">
                    <input type="hidden" name="id" value="<?=$this->data['id']?>">
                    <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
                </form>
                <form action="<?=BASEURL?>/admin/help/delete/" method="post">
                    <input type="hidden" name="id" value="<?=$this->data['id']?>">
                    <button type="submit" class="btn btn-large btn-block btn-danger">削除</button>
                </form>
            </div>
        
          
		<!--中身-->
        </div>
      </div>
    </div>
</section>
