<!--配達日時設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>配達日時設定</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
    <?php if($this->Msg):?>
    <!--メッセージ表示部-->
    <div class="alert alert-success">
    	<?=$this->Msg?>
    </div>
    <?php endif;?>
    
    
    <!--設定項目表示部-->
    <form action="<?=BASEURL?>/admin/settings/delivery/" method="post">
    <p>お客様による配達日時の選択に関する設定です。</p>
        <table class="table table-striped table-responcive">
            <tbody>
                <tr>
                    <th>配達日指定可否</th>
                    <td>
                        <select name="shippingdate" class="form-control">
                            <?php foreach(array(0=>"配達日指定可能",1=>"配達日指定不能") as $k=>$v):?>
                            <?php if($k == $this->data['shippingdate']):?>
                                <option value="<?=$k?>" selected><?=$v?></option>
                            <?php else:?>
                                <option value="<?=$k?>"><?=$v?></option>
                            <?php endif;?>
                            <?php endforeach;?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th>配達日指定範囲</th>
                    <td>
                    <p>※配達日を当日から受付する場合は、最短選択日数を0としてください。(上記項目にて「配達日指定可能」を選択した場合のみ有効）</p>
                       <p class="form-inline">本日から<input type="text" class="form-control" name="shippingstart" value="<?=$this->data['shippingstart']?>">
                        日後～<input type="text" class="form-control" name="shippingend" value="<?=$this->data['shippingend']?>">日後
                        </p>
                    </td>
                </tr>
                <tr>
                    <th>配達時間指定の可否</th>
                    <td>
                        <select name="shippingtime" class="form-control">
                            <?php foreach(array(0=>"配達時間指定可能",1=>"配達時間指定不能") as $k=>$v):?>
                            <?php if($k == $this->data['shippingtime']):?>
                                <option value="<?=$k?>" selected><?=$v?></option>
                            <?php else:?>
                                <option value="<?=$k?>"><?=$v?></option>
                            <?php endif;?>
                            <?php endforeach;?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <th>配達時間指定選択項目</th>
                    <td>
                        <p>1行に1項目を入力してください。</p>
                        <p><textarea name="shippingselection" class="form-control" rows="5"><?=$this->data['shippingselection']?></textarea></p>
                    </td>
                </tr>
                <tr>
                    <th>配達日繰り上げタイミング</th>
                    <td>
                        <select name="shippingtiming" class="form-control">
                            <?php for($i=0;$i<25;$i++):?>
                            <?php if($i == $this->data['shippingtiming']):?>
                                <option value="<?=$i?>" selected><?=$i?>:00</option>
                            <?php else:?>
                                <option value="<?=$i?>"><?=$i?>:00</option>
                            <?php endif;?>
                            <?php endfor;?>
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="form-actions">
            <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
        </div>
    </form>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>