<!--新規追加-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>新規追加</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
		<?php if($this->Msg):?>
        <!--メッセージ表示部-->
        <div class="alert alert-success">
            <?=$this->Msg?>
        </div>
        <?php endif;?>
    	<div class="panel-group" id="accordion">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                   <a data-toggle="collapse" data-parent="#accordion" href="#collapse_add" class="collapsed">
                   <i class="fa fa-caret-square-o-down"></i> 新規追加
                  </a>
                </h4>
              </div>
              <div id="collapse_add" class="panel-collapse collapse" style="height: 0px;">
                <div class="panel-body">
                    <form action="<?=BASEURL?>/admin/settings/plan/" method="post">
                    <table class="table table-striped table-responcive">
                        <tbody>
                            <tr>
                                <th>プラン名</th>
                                <td><input type="text" name="name" value="" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <th>説明</th>
                                <td><textarea name="description"  rows="5" class="form-control"></textarea>
                                </td>
                            </tr>
                            <tr>
                                <th>システム利用料</th>
                                <td><input type="text" name="fee" class="form-control" value="<?=$v['fee']?>">
                                </td>
                            </tr>
                            <tr>
                                <th>容量</th>
                                <td><input type="text" name="size" value="<?=$v['size']?>" class="form-control">
                                </td>
                            </tr>
                            <tr>
                                <th>表示・非表示</th>
                                <td>
                                    <select name="activate" class="form-control">
                                        <?php foreach(array("1"=>"表示","2"=>"非表示") as $k=>$v):?>
                                            <option value="<?=$k?>"><?=$v?></option>
                                        <?php endforeach;?>
                                    </select>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="form-actions">
                        <input type="hidden" name="mode" value="insert">
                        <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
                    </div>
                    </form>
            </div>
          </div>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>



<!--リスト-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>登録済みプラン</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
		<?php if($this->Msg2):?>
        <!--メッセージ表示部-->
        <div class="alert alert-success">
            <?=$this->Msg2?>
        </div>
        <?php endif;?>
            <div class="panel-group" id="accordion">
                <?php foreach($this->data as $v):?>
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h4 class="panel-title">
                           <a data-toggle="collapse" data-parent="#accordion" href="#collapse<?=$v['id']?>" class="collapsed">
                           <i class="fa fa-caret-square-o-down"></i> <?=$v['name']?>
                            <?php if($v['gmoFlug']  ==1):?>
                            	（GMOクレジットカード決済）
                            <?php elseif($v['gmoFlug']  ==2):?>
                            	（GMOコンビニ決済）
                            <?php endif;?>
                          </a>
                        </h4>
                      </div>
                      <div id="collapse<?=$v['id']?>" class="panel-collapse collapse" style="height: 0px;">
                        <div class="panel-body">
                            <form action="<?=BASEURL?>/admin/settings/plan/" method="post">
                            
                                <table class="table table-striped table-responcive">
                                    <tbody>
                                        <tr>
                                            <th>決済方法名</th>
                                            <td><input type="text" name="name" value="<?=$v['name']?>" class="form-control">
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>説明</th>
                                            <td><textarea name="description"  rows="5" class="form-control"><?=$v['description']?></textarea>
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>システム利用料</th>
                                            <td><input type="text" name="fee" value="<?=$v['fee']?>" class="form-control">
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>容量</th>
                                            <td><input type="text" name="size" value="<?=$v['size']?>" class="form-control">
                                            </td>
                                        </tr>
                                        <tr>
                                            <th>表示・非表示</th>
                                            <td>
                                                <select name="activate" class="form-control">
                                                    <?php foreach(array("1"=>"表示","2"=>"非表示") as $k=>$vv):?>
                                                    <?php if($vv == $this->data['activate']):?>
                                                        <option value="<?=$k?>" sselected><?=$vv?></option>
                                                    <?php else:?>
                                                        <option value="<?=$k?>"><?=$vv?></option>
                                                    <?php endif;?>
                                                    <?php endforeach;?>
                                                </select>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="form-actions">
                                    <input type="hidden" name="id" value="<?=$v['id']?>">
                                     <input type="hidden" name="mode" value="update">
                                    <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
                                    <button type="button" class="btn btn-large btn-block btn-danger delete" name="<?=$v['id']?>">削除</button>
                                </div>
                        </form>
                    </div>
                  </div>
                </div>
    			<?php endforeach;?>
    		</div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<script>
$(function(){
	$(".delete").on("click",function(){
		if(window.confirm("本当に削除してもいいですか？")){
			var id = $(this).attr("name");
			$.post("<?=BASEURL?>/api/settings/plan",{"id": id},function(data){
				console.log(data);
				if(data == "OK"){
					location.reload();
				}
			});
		}
	});
});
</script>