<!--サイト設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>ポイント情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
    <?php if($this->Msg):?>
    <!--メッセージ表示部-->
    <div class="alert alert-success">
    	<?=$this->Msg?>
    </div>
    <?php endif;?>
    
    
    <!--設定項目表示部-->
    <form action="<?=BASEURL?>/admin/settings/point/" method="post">
        <table class="table table-striped table-responcive">
            <tbody>
                <tr>
                    <th>ポイントを使用する</th>
                    <td>
                    <select name="pointuse" class="form-control">
                        <?php foreach(array(0=>"使用する",1=>"使用しない") as $k=>$v):?>
                        <?php if($k == $this->data['pointuse']):?>
                            <option value="<?=$k?>" selected><?=$v?></option>
                        <?php else:?>
                            <option value="<?=$k?>"><?=$v?></option>
                        <?php endif;?>
                        <?php endforeach;?>
                    </select>
                    </td>
                </tr>
                <tr>
                    <th>ポイント還元率</th>
                    <td>
                    <p>以下は、ポイントを使用する場合のみに設定</p>
                    <input type="text" class="form-control" name="pointrate" value="<?=$this->data['pointrate']?>">％<br>
                     (1% = 100円で1ポイント　1ポイント＝1円)
                    </td>
                </tr>
                <tr>
                    <th>ポイント有効期限</th>
                    <td><input type="text" class="form-control" name="pointlimit" value="<?=$this->data['pointlimit']?>">日</td>
                </tr>
                <tr>
                    <th>会員登録時発行ポイント数</th>
                    <td><input type="text" class="form-control" name="pointfirst" value="<?=$this->data['pointfirst']?>">ポイント</td>
                </tr>
                <tr>
                    <th>ポイント名称</th>
                    <td><input type="text" class="form-control" name="pointname" value="<?=$this->data['pointname']?>"></td>
                </tr>
            </tbody>
        </table>
        <div class="form-actions">
            <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
        </div>
    </form>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>