<!--新規追加-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>新規追加</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
		<?php if($this->Msg):?>
        <!--メッセージ表示部-->
        <div class="alert alert-success">
            <?=$this->Msg?>
        </div>
        <?php endif;?>
    	<div class="panel-group" id="accordion">
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4 class="panel-title">
                   <a data-toggle="collapse" data-parent="#accordion" href="#collapse_add" class="collapsed">
                   <i class="fa fa-caret-square-o-down"></i> 新規追加
                  </a>
                </h4>
              </div>
              <div id="collapse_add" class="panel-collapse collapse" style="height: 0px;">
                <div class="panel-body">
                		<div class="form-inline">
                        <input type="text" id="alljapan" class="form-control">円
                        <button type="button" class="btn btn-warning" id="all">全て同じ送料を指定</button>
                      </div>
                    <form action="<?=BASEURL?>/admin/settings/shipping/" method="post">
                    <p><label for="name">送料設定名：</label><input type="text" name="name" value="" class="form-control"></p>
                    <table class="table table-striped table-responcive">
                        <tbody>
                        		<tr>
						<?php for($i=0;$i<count($this->pref);$i++):?>
                            <th><?=$this->pref[$i]['name']?></th>
                            <td class="form-inline"><input type="text" class="fields form-control" name="s<?=$this->pref[$i]['id']?>" value="">円</td>
                            <?php if(($i+1)%3 == 0):?>
                            </tr>
                        		<tr>
                            <?php endif;?>
                        <?php endfor;?>
                            </tr>
                    		</tbody>
                     </table>
                    <div class="form-actions">
                        <input type="hidden" name="mode" value="insert">
                        <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
                    </div>
                    </form>
            </div>
          </div>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>



<!--リスト-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>登録済み決済方法</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
		<?php if($this->Msg2):?>
        <!--メッセージ表示部-->
        <div class="alert alert-success">
            <?=$this->Msg2?>
        </div>
        <?php endif;?>
            <div class="panel-group" id="accordion">
                <?php foreach($this->data as $v):?>
                    <div class="panel panel-default">
                      <div class="panel-heading">
                        <h4 class="panel-title">
                           <a data-toggle="collapse" data-parent="#accordion" href="#collapse<?=$v['id']?>" class="collapsed">
                           <i class="fa fa-caret-square-o-down"></i> <?=$v['name']?>
                          </a>
                        </h4>
                      </div>
                      <div id="collapse<?=$v['id']?>" class="panel-collapse collapse" style="height: 0px;">
                        <div class="panel-body">
                		<p class="form-inline">
                        <input type="text" id="alljapan<?=$v['id']?>" class="form-control">円
                        <button type="button" class="btn btn-warning" id="all<?=$v['id']?>">全てに同じ送料を指定する</button></p>
                    <form action="<?=BASEURL?>/admin/settings/shipping/" method="post">
                    <p>送料設定名：<input type="text" name="name" value="<?=$v['name']?>"></p>
                    <table class="table table-striped table-responcive">
                        <tbody>
                        		<tr>
						<?php for($i=0;$i<count($this->pref);$i++):?>
                            <th><?=$this->pref[$i]['name']?></th>
                            <td class="form-inline"><input type="text" class="fields<?=$v['id']?>　form-control" name="s<?=$this->pref[$i]['id']?>" value="<?=$v["s".$this->pref[$i]['id']]?>">円</td>
                            <?php if(($i+1)%3 == 0):?>
                                </tr>
                                <tr>
                            <?php endif;?>
                        <?php endfor;?>
                            </tr>
                    		</tbody>
                     </table>
                    <div class="form-actions">
                        <input type="hidden" name="id" value="<?=$v['id']?>">
                        <input type="hidden" name="mode" value="update">
                        
                        <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
                        <button type="button" class="btn btn-large btn-block btn-danger delete" title="<?=$v['id']?>">削除</button>
                    </div>
                    </form>
                    </div>
                  </div>
                </div>
				<script>
                $(function(){
                    $('#all<?=$v['id']?>').on("click",function(){
                        $(".fields<?=$v['id']?>").val($("#alljapan<?=$v['id']?>").val());
                    });
                });
                </script>
    			<?php endforeach;?>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<script>
$(function(){
	$(".delete").on("click",function(){
		if(window.confirm("本当に削除してもいいですか？")){
			var id = $(this).attr("title");
			console.log(id);
			$.post("<?=BASEURL?>/api/settings/shipping",{"id": id},function(data){
				console.log(data);
				if(data == "OK"){
					location.reload();
				}
			});
		}
	});
});
$(function(){
	$('#all').on("click",function(){
		$(".fields").val($("#alljapan").val());
	});
});
</script>