<section>
  <div class="x_panel">
    <div class="x_title">
      <div class="row">
        <div class="col-xs-8"><h2>プラン一覧</h2></div>
        <div class="col-xs-4 text-right"><a href="<?=BASEURL?>/admin/plan/registrer/" class="btn btn-success">プラン登録</a></div>
      </div>
    </div>
    <div class="x_content">
    <!--中身-->
    <form action="<?=BASEURL?>/admin/plan/" method="get" class="row">
      <p class="col-sm-4"><input type="text" name="keyword" value="<?=$_GET['keyword']?>" class="form-control" placeholder="キーワード"></p>
      <p class="col-sm-1">件数：</p>
      <p class="col-sm-1">
        <select name="limit" class="form-control">
          <option value="10">10件</option>
          <option value="25">25件</option>
          <option value="50">50件</option>
          <option value="75">75件</option>
          <option value="100">100件</option>
        </select>
      </p>
      <p class="col-sm-6 text-right"><button type="submit" class="btn btn-warning">検索</button></p>
    </form>
    <table class="table table-striped responsive-utilities jambo_table bulk_action">
      <thead>
        <tr class="headings">
          <th>
        		<input type="checkbox" id="allcheck" class="flat ck">
          </th>
          <th class="column-title">お名前</th>
          <th class="column-title">区分</th>
          <th class="column-title">ステータス </th>
          <th class="column-title">詳細 </th>
        </tr>
      </thead>
      <tbody>
      <?php foreach($this->users as $vv):?>
        <tr class="even pointer">
          <td class="a-center ">
            <input type="checkbox" class="ck" name="ck[]" value="<?=$vv['id']?>">
          </td>
          <td class=" "><?=$vv['name']?></td>
          <td class=" "><?php $kind = array(0=>"オプション",1=>"メイン"); echo $kind[$vv['kind']];?></td>
    			<td class=" ">
            <?php
    				if($vv['activate'] ==1){
    					echo "有効";
    				}else{
    					echo "無効";
    				}
    				?>
      	  </td>
          <td class="a-right a-right ">
            <a href="<?=BASEURL?>/admin/plan/update/?id=<?=$vv['id']?>" class="btn btn-primary">詳細</a>
          </td>
        </tr>
      <?php endforeach;?>
      </tbody>
    </table>
    <div class="profile_title">
      <div class="row">
        <div class="col-sm-12">
          <button class="btn btn-danger" type="button" id="deleteAll" data-table="plan">チェックしたものを削除</button>
       </div>
      </div>
    </div>
    <?=$this->pager?>
    <!--中身-->
    </div>
  </div>
</section>


<form action="<?=BASEURL?>/admin/plan/postcard" method="post" id="postcardform" target="_blank">
<input type="hidden" name="ids" value="">
</form>
<script>
$(function(){
	$('input[type=checkbox]').click(function() {
	  var t = $(this).prop;
		if(t('checked'))
			t('checked', '');
		else
			t('checked', 'checked');
	});

	$('table tr').click(function() {
	  var c = $(this).children('td').children('input[type=checkbox]');
		if(c.prop('checked'))
			c.prop('checked', '');
		else
			c.prop('checked', 'checked');
	});
	//checkboxを全て同時に選択
	$("#allcheck").on("click",function(){
		if($(this).is(':checked')){
			$(".ck").prop('checked', true);
		}else{
			$(".ck").prop('checked', false);
		}
	});
	$("#deleteAll").on("click",function(){
		if(window.confirm("本当に削除してもいいですか？")){
			var ck = $('[class="ck"]:checked').map(function(){
				return $(this).val();
			}).get();
      var table = $(this).data("table");
			$.post("<?=BASEURL?>/api/delete/",{ids:ck,table:table},function(data){
				if(data = "OK"){
					location.href = "<?=BASEURL?>/admin/"+table+"/";
				}
			});
		}
	});
});
</script>
