<a href="<?=BASEURL?>/admin/plan/" class="btn btn-warning">一覧へ</a>
<!--プラン情報編集フォーム-->
<section>
  <div class="x_panel">
    <div class="x_title">
      <h2>プラン編集</h2>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <!--中身-->
      <form action="<?=BASEURL?>/admin/plan/registrerfinish" method="post" id="form">
        <table class="table table-striped table-responcive">
          <tbody>
            <tr>
              <th>お名前</th>
              <td class="form-inline">
                <input type="text" name="name" value="<?=$this->detail['name']?>" class="form-control">
              </td>
            </tr>
            <tr>
              <th>種類</th>
              <td class="form-inline">
                <select class="form-control" name="kind">
                  <?php foreach(array(0=>"オプション",1=>"メイン") as $k=>$v):?>
                    <?php if($k==$this->detail['kind']):?>
                      <option value="<?=$k?>" selected><?=$v?></option>
                    <?php else:?>
                      <option value="<?=$k?>"><?=$v?></option>
                    <?php endif;?>
                  <?php endforeach;?>
                </select>
              </td>
            </tr>
            <tr>
              <th>説明</th>
              <td>
                <textarea class="form-control" name="description" rows="4"><?=$this->detail['description']?></textarea>
              </td>
            </tr>
            <tr>
              <th>月額</th>
              <td class="form-inline">
                <input type="text" name="fee" value="<?=$this->detail['fee']?>" class="form-control text-right">円(税抜)
              </td>
            </tr>
            <tr>
              <th>請求不可</th>
              <td class="form-inline">
                <select class="form-control" name="notInvoice">
                  <?php foreach(array(0=>"請求可",1=>"請求不可") as $k=>$v):?>
                    <?php if($k==$this->detail['kind']):?>
                      <option value="<?=$k?>" selected><?=$v?></option>
                    <?php else:?>
                      <option value="<?=$k?>"><?=$v?></option>
                    <?php endif;?>
                  <?php endforeach;?>
                </select>
                ※請求不可となっている場合は、料金を請求しません。
              </td>
            </tr>
            <tr>
              <th>初期費用</th>
              <td class="form-inline">
                <input type="text" name="initialCost" value="<?=$this->detail['initialCost']?>" class="form-control text-right">円(税抜)
              </td>
            </tr>
            <tr>
              <th>一般スタッフ単価</th>
              <td class="form-inline">
                <input type="text" name="staffUnit" value="<?=$this->detail['staffUnit']?>" class="form-control text-right">円(税抜)
              </td>
            </tr>
            <tr>
              <th>外注スタッフ単価</th>
              <td class="form-inline">
                <input type="text" name="outsourceUnit" value="<?=$this->detail['outsourceUnit']?>" class="form-control text-right">円(税抜)
              </td>
            </tr>
            <tr>
              <th>追加容量</th>
              <td class="form-inline">
                <input type="text" name="size" value="<?=$this->detail['size']?>" class="form-control text-right">バイト(1GB=1000000000バイト)
              </td>
            </tr>
            <tr>
              <th>個別解約</th>
              <td class="form-inline">
                <select name="downgrade" class="form-control">
                  <?php
                  $arr = array(0=>"可能",1=>"不可");
                  foreach($arr as $k=>$v){
                  if($this->detail['downgrade'] == $k){
                     echo "<option value=\"{$k}\" selected>".$v."</option>";
                   }else{
                     echo "<option value=\"{$k}\">".$v."</option>";
                   }
                  }
                  ?>
                </select>
              </td>
            </tr>
            <tr>
              <th>ステータス</th>
              <td>
                <select name="activate" class="form-control">
                  <?php
                  $arr = array(0=>"無効",1=>"有効");
                  foreach($arr as $k=>$v){
                  if($this->detail['activate'] == $k){
                     echo "<option value=\"{$k}\" selected>".$v."</option>";
                   }else{
                     echo "<option value=\"{$k}\">".$v."</option>";
                   }
                  }
                  ?>
                </select>
              </td>
            </tr>
          </tbody>
        </table>
        <input type="hidden" name="id" value="<?=$this->detail['id']?>">
      </form>
      <div class="form-actions">
        <button class="btn btn-large btn-block btn-primary" id="sub">登録</button>
      </div>
    <!--中身-->
    </div>
  </div>
</section>
<script>
$(function(){
	$("#sub").on("click",function(){
		if(window.confirm("プラン情報編集を行います。内容を変更される場合はキャンセルボタンを押してください。")){
			$("#form").submit();
		}
	});
});
</script>
