<?php if($this->images):?>
<!DOCTYPE html>
<html class='no-js' lang='ja'>
<head>
<meta charset='utf-8' />
<meta content='IE=edge,chrome=1' http-equiv='X-UA-Compatible' />
<title><?=$this->title?></title>
<meta name="language" content="ja" />
<meta content='width=device-width, initial-scale=1.0' name='viewport' />
<style type="text/css">
html{
  height:100%;
}
body {
  height:100%;
  margin:0;
  padding:0;
}
.bgsw{
	height: auto !important;
	height: 100%;
	min-height: 100%;
}
</style>
<script type="text/javascript" src="<?=BASEURL?>/lib/js/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="<?=BASEURL?>/lib/js/jqslide.js"></script>
<script type="text/javascript">
$(document).ready(function(){
	$(function($) {
		$('.bgsw').bgSwitcher({
			images: [<?php for($i=0;$i<count($this->images);$i++){
				 if($i!=0){
					echo ",\n";
				 }
			 	echo "\"".BASEURL."/".$this->images[$i]["url"]."\"";
			 }?>],
			interval: 5000,
			effect:"fade",
			duration:1000
		});
	});
});
</script>
</head>
<body>
<div class="bgsw"></div>
</body>
</html>
<?php else:?>
	<p>画像はアップロードされていません。</p>
<?php endif;?>