<?php if($this->reg || $this->update):?>
  <div class="alert alert-success"><?=$this->msg?></div>
<?php endif;?>
<!--スタッフ情報編集フォーム-->
<p>
  <a href="<?=BASEURL?>/editor/userclass/">会員分類一覧へ戻る</a>
</p>
<section class="row">
  <div class="x_panel">
    <div class="x_title">
      <h2>会員分類編集</h2>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <!--中身-->
      <form action="<?=BASEURL?>/editor/userclass/updatefinish" method="post" id="form">
        <table class="table table-striped table-responcive">
          <tbody>
            <tr>
              <th style="width:25%;">分類名</th>
              <td class="form-inline">
                <input type="text" name="name" value="<?=$this->detail[0]['name']?>" class=" form-control" style="width:20em;">
              </td>
            </tr>
          </tbody>
        </table>
        <input type="hidden" name="id" value="<?=$this->detail[0]['id']?>">
      </form>
      <div class="form-actions">
        <button class="btn btn-large btn-block btn-primary" id="sub">編集</button>
      </div>
      <!--中身-->
    </div>
  </div>
</section>
<section class="row">
  <div class="x_panel">
    <div class="x_title">
      <h2>使用する会員の項目設定</h2>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <!--中身-->
      <div id="facility"></div>
      <!--中身-->
    </div>
  </div>
</section>

<script src="<?=BASEURL?>/js/validation.js"></script>
<script>
var facilityArr = new Array();
var origin;
$(function(){
  $("#pwactive").on("click",function(){
    if($(this).attr("checked",true)){
      $("[name=pw]").attr("disabled",false).val("").focus();
    }else{
      $("[name=pw]").attr("disabled",true);
    }
  });
  $(document).on("click",".facilitySubmit",function(){
    var ids = facilityArr;
    if(ids.length ==0){
      alert("設定が行われていません");
    }else{
      if(window.confirm("設定を保存します。修正する場合はキャンセルしてください。")){
        var arr = new Object();
        for(var i=0;i<facilityArr.length;i++){
          var id = facilityArr[i];
          arr[id] = $("#inp-"+id).val();
        }
        arr.userclass = getParam().id;
        $.post('<?=BASEURL?>/api/user/facilityupdate',arr,function(data){

          console.log(data);
          if(data == "OK"){
            alert("保存しました");
          }
        });
      }
    }


  });
  if(getParam().id != ""){
    classid = getParam().id;
  }else{
    classid = "";
  }
  $.get("<?=BASEURL?>/api/user/facility?id="+classid,function(data){
    $("#facility").html('<div class="row"><div class="col-sm-6 sortable" id="use"></div><div class="col-sm-6 sortable" id="unuse"></div></div>');
    $("#facility").before('<p><button type="button" class="btn btn-success btn-block facilitySubmit">項目の設定を保存</button></p>');
    $("#facility").after('<br><p><button type="button" class="btn btn-success btn-block facilitySubmit">項目の設定を保存</button></p>');


    var json = JSON.parse(data);
    var str = '';
    for(var k in json['unuse']){
      str+= '<div id="'+k+'">';
      str+= json['unuse'][k]['origin'];
      str+= '</div>';
    }
    $("#unuse").html(str);
    if(Object.keys(json['use']).length >0){
      var str = '';
      for(var k in json['use']){
        str+= '<div id="'+k+'">';
        str+= json['use'][k]['origin'];
        str+= '<input id="inp-'+k+'" type="text" name="name['+k+']" value="'+json['use'][k]['name']+'" class="form-control">';
        str+= '</div>';
        facilityArr.push(k);
      }
      $("#use").html(str);
    }
    Object.assign(json['unuse'], json['use']);
    $( ".sortable" ).sortable({
      connectWith: '.sortable',

      update: function(ev, ui) {
        //var log = $(this).sortable("toArray");
        if (this === ui.item.parent()[0]) {
          if(ui.item.parent().attr("id") == "use"){
            var arr = new Array();
            var arr2 = new Array();
            $("#use div").each(function(i,e){
              var id = $(this).attr("id");
              if($("#inp-"+id).length ==0){
                //facilityArr.push(id);
                $(this).append('<input id="inp-'+id+'" type="text" name="name['+id+']" value="'+json['unuse'][id]['origin']+'" class="form-control">');
              }
              arr.push(id);
              facilityArr = arr;
            });
            console.log(facilityArr);
            /*
            for(var i=0;i<facilityArr.length;i++){
              for(var i=0;i<facilityArr.length;i++){

              }
            }
            */
          }else{
            $("#inp-"+ui.item[0].id).remove();
            for(var i=0;i<facilityArr.length;i++){
              if(facilityArr[i] == ui.item[0].id){
                facilityArr.splice(i,1);
              }
            }
          }
        }
      }
    });
  });
});
var error =new Array;
$(function(){
	//バリデーション
	$("[name=name]").on("blur",function(){
		validEmpty("name","分類名");
	});
	$("#sub").on("click",function(){
		validEmpty("name","分類名");
		if(error.length >0){
			var str = "";
			str+= "入力に誤りがあります。下記の項目を修正して再度ボタンを押してください。\n";
			for(var i =0;i<error.length;i++){
				if(error[i] =="nameEmpty"){
					str+="「分類名」を入力してください。\n";
				}
			}
			alert(str);
		}else{
			if(window.confirm("会員分類の編集を行います。内容を変更される場合はキャンセルボタンを押してください。")){
				$("#form").submit();
			}
		}
	});
});
function getParam(){
  var result = {};
  if( 1 < window.location.search.length ){
    // 最初の1文字 (?記号) を除いた文字列を取得する
    var query = window.location.search.substring( 1 );
    // クエリの区切り記号 (&) で文字列を配列に分割する
    var parameters = query.split( '&' );
    for( var i = 0; i < parameters.length; i++ ){
      // パラメータ名とパラメータ値に分割する
      var element = parameters[ i ].split( '=' );
      var paramName = decodeURIComponent( element[0] );
      var paramValue = decodeURIComponent( element[1] );
      // パラメータ名をキーとして連想配列に追加する
      result[ paramName ] = paramValue;
    }
  }
  return result;
}
</script>
