<!--検索-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>受注を検索</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content" style="display:none;">
		<!--中身-->

            <form action="<?=BASEURL?>/admin/order/" method="get">
            	 <div class="row">
                   <p class="col-sm-2">キーワード：</p>
                   <p class="col-sm-4"><input type="text" name="keyword" value="<?=$_GET['keyword']?>" class="form-control"></p>

                   <p class="col-sm-2">表示件数：</p>
                   <p class="col-sm-4">
                   <select name="limit" class="form-control">
                   	<?php foreach(array(10=>"10件",25=>"25件",50=>"50件",75=>"75件",100=>"100件") as $k=>$v):?>
                    	<?php if($k == $_GET['limit']):?>
                        <option value="<?=$k?>" selected><?=$v?></option>
                        <?php else:?>
                        <option value="<?=$k?>"><?=$v?></option>
                        <?php endif;?>
                    <?php endforeach;?>
                    </select>
                    </p>
               </div>
            	 <div class="row">
                   <p class="col-sm-2">進捗未完了</p>
                   <p class="col-sm-10">
                    <label><input type="checkbox" name="resive" value="1"<?php if($_GET['resive']) echo" checked";?> />受付</label>　
                    <label><input type="checkbox" name="pay" value="1"<?php if($_GET['pay']) echo" checked";?> />入金</label>　
                    <label><input type="checkbox" name="shipping" value="1"<?php if($_GET['shipping']) echo" checked";?> />発送</label>　
                    <label><input type="checkbox" name="3dn" value="1"<?php if($_GET['3dn']) echo" checked";?> />4日後</label>　
                    <label><input type="checkbox" name="1mn" value="1"<?php if($_GET['1mn']) echo" checked";?> />1ヶ月後</label>　
                    <label><input type="checkbox" name="2mn" value="1"<?php if($_GET['2mn']) echo" checked";?> />2ヶ月後</label>　
                    <label><input type="checkbox" name="3mn" value="1"<?php if($_GET['3mn']) echo" checked";?> />3ヶ月後</label>　
                    <label><input type="checkbox" name="6mn" value="1"<?php if($_GET['6mn']) echo" checked";?> />6ヶ月後</label>
                   </p>
                </div>
            	 <div class="row">
                   <p class="col-sm-2">会員</p>
                   <p class="col-sm-4">
                   	<select class="form-control" name="membership">
                    	<?php foreach(array(0=>"指定なし",1=>"会員") as $k=>$v):?>
                        	<?php if($k == $_GET['membership']):?>
                            <option value="<?=$k?>" selected="selected"><?=$v?></option>
                            <?php else:?>
                            <option value="<?=$k?>"><?=$v?></option>
                            <?php endif;?>
                        <?php endforeach;?>
                    </select>
                   </p>
                   <p class="col-sm-2">性別</p>
                   <p class="col-sm-4">
                   	<select class="form-control" name="sex">
                    	<?php foreach(array(0=>"指定なし",1=>"女性",2=>"男性") as $k=>$v):?>
                        	<?php if($k == $_GET['sex']):?>
                            <option value="<?=$k?>" selected="selected"><?=$v?></option>
                            <?php else:?>
                            <option value="<?=$k?>"><?=$v?></option>
                            <?php endif;?>
                        <?php endforeach;?>
                    </select>
                   </p>
                </div>
            	 <div class="row">
                   <p class="col-sm-2">生月</p>
                   <p class="col-sm-4">
                   	<select class="form-control" name="birthM">
                    	<?php foreach(array(0=>"指定なし",1=>"1月",2=>"2月",3=>"3月",4=>"4月",5=>"5月",6=>"6月",7=>"7月",8=>"8月",9=>"9月",10=>"10月",11=>"11月",12=>"12月") as $k=>$v):?>
                        	<?php if($k == $_GET['birthM']):?>
                            <option value="<?=$k?>" selected="selected"><?=$v?></option>
                            <?php else:?>
                            <option value="<?=$k?>"><?=$v?></option>
                            <?php endif;?>
                        <?php endforeach;?>
                    </select>
                   </p>
                   <p class="col-sm-2">年代</p>
                   <p class="col-sm-4">
                   	<select class="form-control" name="gene">
                    	<?php foreach(array(0=>"指定なし",1=>"20代",2=>"30代",3=>"40代",4=>"50代",5=>"60代",6=>"70代",7=>"80代",8=>"90代",9=>"10代") as $k=>$v):?>
                        	<?php if($k == $_GET['gene']):?>
                            <option value="<?=$k?>" selected="selected"><?=$v?></option>
                            <?php else:?>
                            <option value="<?=$k?>"><?=$v?></option>
                            <?php endif;?>
                        <?php endforeach;?>
                    </select>
                   </p>
                </div>
            	 <div class="row">
                   <p class="col-sm-2">購入商品</p>
                   <p class="col-sm-4">
                   	<select class="form-control" name="item">
                    	<?php foreach($this->items as $v):?>
                        	<?php if($v['id'] == $_GET['item']):?>
                            <option value="<?=$v['id']?>" selected="selected"><?=$v['name']?></option>
                            <?php else:?>
                            <option value="<?=$v['id']?>"><?=$v['name']?></option>
                            <?php endif;?>
                        <?php endforeach;?>
                    </select>
                   </p>
                   <p class="col-sm-2">ポイント有効期限</p>
                   <p class="col-sm-4">
                   	<select class="form-control" name="point">
                    	<?php foreach(array(0=>"指定なし",1=>"1ヶ月前",2=>"3ヶ月前") as $k=>$v):?>
                        	<?php if($k == $_GET['point']):?>
                            <option value="<?=$k?>" selected="selected"><?=$v?></option>
                            <?php else:?>
                            <option value="<?=$k?>"><?=$v?></option>
                            <?php endif;?>
                        <?php endforeach;?>
                    </select>
                   </p>
                </div>

                <p class="text-center">
                <button type="reset" class="btn btn-danger">検索条件をリセット</button>
                <button type="submit" class="btn btn-warning">検索</button>
                </p>
            </form>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<!--リスト表示-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <div class="row">
            <p class="col-xs-6"><span style="font-size:18px;color:#71879B;">受注一覧</span></p>
            <p class="col-xs-6 text-right">
            	<a href="<?=BASEURL?>/admin/order/registrer/" class="btn btn-success">受注登録</a></p>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <p>※受注主が会員の場合は、<span class="label label-success">会員</span>がつきます。<span class="badge">1</span>は、受注主の累積購入回数です。</p>
        <?=$this->pager?>
        <div class="profile_title" style="margin-bottom:2em;">
            <p style="display:table-cell;vertical-align:middle;width:100%;padding:0.5em 1em 0;">
            	<button type="button" id="csvAll" style="float:right;" class="btn btn-warning">抽出データを全件取得</button>
    	        チェックしたものを
                <button class="btn btn-info mtsend" type="button" id="3dm">4日後</button>
                <button class="btn btn-primary mtsend" type="button" id="1mm">1ヶ月後</button>
                <button class="btn btn-success mtsend" type="button" id="2mm">2ヶ月後</button>
                <button class="btn btn-warning mtsend" type="button" id="3mm">3ヶ月後</button>
	            <button class="btn btn-danger mtsend" type="button" id="6mm">6ヶ月後</button>
            </p>
        </div>
        <table class="table table-striped responsive-utilities jambo_table bulk_action">
            <thead>
            <tr class="headings">
                <th><input type="checkbox" id="allcheck" style="margin-left:10px;margin-tpp:5px;-moz-transform-origin: right bottom; -moz-transform: scale( 2 , 2 ); -webkit-transform-origin: right bottom; -webkit-transform: scale( 2 , 2 );"></th>
                <th>受注日</th>
                <th>GMOオーダー番号</th>
                <th>受注主</th>
                <th>合計金額</th>
                <th class="hidden-xs">受付</th>
                <th class="hidden-xs">入金</th>
                <th class="hidden-xs">発送</th>
                <th class="hidden-xs">4日後</th>
                <th class="hidden-xs">1ヶ月後</th>
                <th class="hidden-xs">２ヶ月後</th>
                <th class="hidden-xs">3ヶ月後</th>
                <th class="hidden-xs">6ヶ月後</th>
                <th>詳細</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($this->users as $vv):?>
            <tr>
                <td><input type="checkbox" class="ck" name="ck[]" value="<?=$vv['id']?>" style="margin-left:10px;margin-tpp:10px;-moz-transform-origin: right bottom; -moz-transform: scale( 2 , 2 ); -webkit-transform-origin: right bottom; -webkit-transform: scale( 2 , 2 );"></td>
                <td><?=date('Y-m-d',strtotime($vv['orderDatetime']))?></td>
                <td style="word-break: break-all;"><?=$vv['GMOorder_id']?></td>
                <td><?=$vv['cus_name']?><?=$vv['cus_name2']?>様
				<?php if($vv['member_no']):?>
                <span class="label label-success">会員</span>
                <?php endif;?><span class="badge"><?=$vv['c']?></span><?php if($vv['GMOstatus'] == "審査中") echo "<br />※後払い与信審査中"?>
				<?php if($vv['cus_name'].$vv['cus_name2'] != $vv['delivery_name'].$vv['delivery_name2']):?>
                <span class="label label-warning">お届け先指定</span>
                <?php endif;?>
                </td>
                <td class="text-right"><?=number_format($vv['seikyu_cost'])?>円</td>
                <td class="hidden-xs"><span style="font-size:36px;"><?php if($vv['check_order'] != "") echo "■"?></span></td>
                <td class="hidden-xs"><span style="font-size:36px;"><?php if($vv['check_payment_end'] != "") echo "■"?></span></td>
                <td class="hidden-xs"><span style="font-size:36px;"><?php if($vv['check_delivery'] != "") echo "■"?></span></td>
                <td class="hidden-xs"><span style="font-size:36px;"><?php if($vv['check_follow_mail'] != "") echo "■"?></span></td>
                <td class="hidden-xs"><span style="font-size:36px;"><?php if($vv['check_3w'] != "") echo "■"?></span></td>
                <td class="hidden-xs"><span style="font-size:36px;"><?php if($vv['check_2m'] != "") echo "■"?></span></td>
                <td class="hidden-xs"><span style="font-size:36px;"><?php if($vv['check_3m'] != "") echo "■"?></span></td>
                <td class="hidden-xs"><span style="font-size:36px;"><?php if($vv['check_6m'] != "") echo "■"?></span></td>
                <td>
                	<a href="<?=BASEURL?>/admin/order/detail/?id=<?=$vv['id']?>" class="btn btn-primary">詳細</a>
                    <!--form action="<?=BASEURL?>/admin/order/detail/" method="get">
                        <input type="hidden" name="id" value="<?=$vv['id']?>">
                        <button type="submit" class="btn btn-primary">詳細</button>
                    </form-->
                </td>
            </tr>
            <?php endforeach;?>
            </tbody>
        </table>
        <div class="profile_title">
           <p style="display:table-cell;vertical-align:middle;">
           　チェックしたものを　
            <button class="btn btn-info" type="button" id="exportAll">CSV出力(e飛伝用)</button>
            <button class="btn btn-warning" type="button" id="picking">ピッキングリストを作成</button>
            <button class="btn btn-danger" type="button" id="deleteAll">削除</button></p>
            <button class="btn btn-info" type="button" id="exportAll2">CSV出力</button>
        </div>
        <?=$this->pager?>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<div id="overlay">
	<div class="overlay_inner">
    	<span id="overlay_msg"></span>
    </div>
</div>
<style>
#overlay {
	display:none;
	z-index:100000;
	background:rgba(0,0,0,0.7);
	position:fixed;
	top:0;
	left:0;
	width:100%;
	height:100%;
}
.overlay_inner {
	width:30%;
	height:100px;
	background:white;
	border-radius:20px;
	border:solid 1px #666;
	margin:200px auto 0;
	text-align:center;
	padding-top:41px;
}
#overlay_msg {
	font-weight:bold;
	color:#600;
	font-size:18px;
	line-height:18px;
}
</style>
<script>
	//2017.06.20 一括処理
	//抽出データを全県取得
	$("#csvAll").on("click",function(){
		var param = getUrlVars();
		delete param['p'];
		delete param['kind'];
		delete param['limit'];
		//送信用フォームを作成
		var form = $("<form>");
		form.attr("method","post");
		form.attr("target","_blank");
		form.attr("action","<?=BASEURL?>/admin/order/csv/");
		$("body").append(form);

		for(var k in param){
			var inp = $("<input>");
			inp.attr("type","hidden");
			inp.attr("name",k);
			inp.val(param[k]);
			form.append(inp);
		}
		form.submit()

	});
	//3日目メール送信
	$("#3dm").on("click",function(){
		var n = 3; //秒
		var ck = $('[class="ck"]:checked').map(function(){
			return $(this).val();
		}).get();
		var str = JSON.stringify(ck);

		if(ck.length == 0){
			alert("何もチェックされていません");
			console.log(ck.length);
		}else{
			msg = "受注完了メール送信開始";
			$("#overlay_msg").text(msg);
			$("#overlay").css("display","block");
			function Loop(maxCount, i) {
				if (i <= maxCount) {
					//1通ずつn秒ごとにメールを送信
					var url = "<?=BASEURL?>/api/order/m3d/?ids=[\""+ck[i]+"\"]";
					$.get(url,function(data){
						console.log(data);
						if(data == "OK"){
							//1件づつの完了時に処理を指せる場合はここ
							var c = i+1;
							msg = c+"/"+ck.length+"件のメールを送信完了";
							$("#overlay_msg").text(msg);
						}
					});
					setTimeout(function(){Loop(maxCount, ++i)}, n*1000);
				}else{
					//全ての処理が完了したらリロード
					location.reload();
				}
			}
			//開始
			Loop(ck.length, 0);
		}
	});
	//1ヶ月メール送信
	$("#1mm").on("click",function(){
		var n = 3; //秒
		var ck = $('[class="ck"]:checked').map(function(){
			return $(this).val();
		}).get();
		var str = JSON.stringify(ck);

		if(ck.length == 0){
			alert("何もチェックされていません");
		}else{
			msg = "受注完了メール送信開始";
			$("#overlay_msg").text(msg);
			$("#overlay").css("display","block");
			function Loop(maxCount, i) {
				if (i <= maxCount) {
					//1通ずつn秒ごとにメールを送信
					var url = "<?=BASEURL?>/api/order/m1m/?ids=[\""+ck[i]+"\"]";
					$.get(url,function(data){
						console.log(data);
						if(data == "OK"){
							//1件づつの完了時に処理を指せる場合はここ
							var c = i+1;
							msg = c+"/"+ck.length+"件のメールを送信完了";
							$("#overlay_msg").text(msg);
						}
					});
					setTimeout(function(){Loop(maxCount, ++i)}, n*1000);
				}else{
					//全ての処理が完了したらリロード
					location.reload();
				}
			}
			//開始
			Loop(ck.length, 0);
		}
	});
	//2ヶ月メール送信
	$("#2mm").on("click",function(){
		var n = 3; //秒
		var ck = $('[class="ck"]:checked').map(function(){
			return $(this).val();
		}).get();
		var str = JSON.stringify(ck);

		if(ck.length == 0){
			alert("何もチェックされていません");
		}else{
			msg = "受注完了メール送信開始";
			$("#overlay_msg").text(msg);
			$("#overlay").css("display","block");
			function Loop(maxCount, i) {
				if (i <= maxCount) {
					//1通ずつn秒ごとにメールを送信
					var url = "<?=BASEURL?>/api/order/m2m/?ids=[\""+ck[i]+"\"]";
					$.get(url,function(data){
						console.log(data);
						if(data == "OK"){
							//1件づつの完了時に処理を指せる場合はここ
							var c = i+1;
							msg = c+"/"+ck.length+"件のメールを送信完了";
							$("#overlay_msg").text(msg);
						}
					});
					setTimeout(function(){Loop(maxCount, ++i)}, n*1000);
				}else{
					//全ての処理が完了したらリロード
					location.reload();
				}
			}
			//開始
			Loop(ck.length, 0);
		}
	});
	//3ヶ月メール送信
	$("#3mm").on("click",function(){
		var n = 3; //秒
		var ck = $('[class="ck"]:checked').map(function(){
			return $(this).val();
		}).get();
		var str = JSON.stringify(ck);

		if(ck.length == 0){
			alert("何もチェックされていません");
		}else{
			msg = "受注完了メール送信開始";
			$("#overlay_msg").text(msg);
			$("#overlay").css("display","block");
			function Loop(maxCount, i) {
				if (i <= maxCount) {
					//1通ずつn秒ごとにメールを送信
					var url = "<?=BASEURL?>/api/order/m3m/?ids=[\""+ck[i]+"\"]";
					$.get(url,function(data){
						console.log(data);
						if(data == "OK"){
							//1件づつの完了時に処理を指せる場合はここ
							var c = i+1;
							msg = c+"/"+ck.length+"件のメールを送信完了";
							$("#overlay_msg").text(msg);
						}
					});
					setTimeout(function(){Loop(maxCount, ++i)}, n*1000);
				}else{
					//全ての処理が完了したらリロード
					location.reload();
				}
			}
			//開始
			Loop(ck.length, 0);
		}
	});
	//6ヶ月メール送信
	$("#6mm").on("click",function(){
		var n = 3; //秒
		var ck = $('[class="ck"]:checked').map(function(){
			return $(this).val();
		}).get();
		var str = JSON.stringify(ck);

		if(ck.length == 0){
			alert("何もチェックされていません");
		}else{
			msg = "受注完了メール送信開始";
			$("#overlay_msg").text(msg);
			$("#overlay").css("display","block");
			function Loop(maxCount, i) {
				if (i <= maxCount) {
					//1通ずつn秒ごとにメールを送信
					var url = "<?=BASEURL?>/api/order/m6m/?ids=[\""+ck[i]+"\"]";
					$.get(url,function(data){
						console.log(data);
						if(data == "OK"){
							//1件づつの完了時に処理を指せる場合はここ
							var c = i+1;
							msg = c+"/"+ck.length+"件のメールを送信完了";
							$("#overlay_msg").text(msg);
						}
					});
					setTimeout(function(){Loop(maxCount, ++i)}, n*1000);
				}else{
					//全ての処理が完了したらリロード
					location.reload();
				}
			}
			//開始
			Loop(ck.length, 0);
		}
	});

	$('input[type=checkbox]').click(function() {
	  var t = $(this).prop;
		if(t('checked'))
			t('checked', '');
		else
			t('checked', 'checked');
	});

	$('table tr').click(function() {
	  var c = $(this).children('td').children('input[type=checkbox]');
		if(c.prop('checked'))
			c.prop('checked', '');
		else
			c.prop('checked', 'checked');
	});
	//checkboxを全て同時に選択
	$("#allcheck").on("click",function(){
		if($(this).is(':checked')){
			$(".ck").prop('checked', true);
		}else{
			$(".ck").prop('checked', false);
		}
	});
	$("#deleteAll").on("click",function(){
		if(window.confirm("本当に削除してもいいですか？")){
			var ck = $('[class="ck"]:checked').map(function(){
				return $(this).val();
			}).get();
			var url = "<?=BASEURL?>/api/order/delete/";
			$.post(url,{ids:ck},function(data){
				console.log(data);
				if(data == "OK"){
					location.href = "<?=BASEURL?>/admin/order/";
				}
			});
		}
	});
	$("#exportAll").on("click",function(){
			var ck = $('[class="ck"]:checked').map(function(){
				return $(this).val();
			}).get();
			var str = JSON.stringify(ck);
				/*
				*/
			var url = "<?=BASEURL?>/api/order/export/?ids="+str;
			location.href = url;

	});
	$("#exportAll2").on("click",function(){
			var ck = $('[class="ck"]:checked').map(function(){
				return $(this).val();
			}).get();
			var str = JSON.stringify(ck);
				/*
				*/
			var url = "<?=BASEURL?>/api/order/export2/?ids="+str;
			location.href = url;

	});
	$("#picking").on("click",function(){
			var ck = $('[class="ck"]:checked').map(function(){
				return $(this).val();
			}).get();
			var str = JSON.stringify(ck);
				/*
				*/
			var url = "<?=BASEURL?>/api/order/picking/?ids="+str;
			window.open().location.href = url;

	});



	///GETパラメータの取得
function getUrlVars(){
    var vars = new Array();
    var param = location.search.substring(1).split('&');
    for(var i = 0; i < param.length; i++) {
        var keySearch = param[i].search(/=/);
        var key = '';
        if(keySearch != -1) key = param[i].slice(0, keySearch);
        var val = param[i].slice(param[i].indexOf('=', 0) + 1);
        if(key != '') vars[key] = decodeURI(val);
    }
    return vars;
}
</script>
