
<!--受注基本データ-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>受注情報詳細</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <p>下記の内容で受注登録を行いました。編集及び削除は、受注管理画面より行えます。</p>
        <p><a href="<?=BASEURL?>/admin/order/" class="btn btn-primary">受注管理画面へ進む</a></p>
        <p><a href="<?=BASEURL?>/admin/order/detail/?id=<?=$this->data['id']?>" class="btn btn-success">受注詳細へ進む</a></p>
        <p><a href="<?=BASEURL?>/admin/order/registrer" class="btn btn-warning">続けて受注を登録する</a></p>
        <br><br>
        <div class="data-table">
        <table class="table table-striped table-responcive">
        <tbody>
            <tr>
            <th>受注受注日</th>
            <td><?=$this->data['order_date']?>
            </td>
            </tr>
            <tr>
            <th>受注番号</th>
            <td><?=$this->data['order_id']?>
            </td>
            </tr>
            <tr>
            <th>受注種別</th>
            <td>
                    	<?php foreach(array(0=>"受注",1=>"見積もり") as $k=>$v):?>
                        <?php if($k == $this->data['order_kind']):?>
                        	<?=$v?>
                        <?php endif;?>
                        <?php endforeach;?>
            </td>
            </tr>
         </tbody>
        </table>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<!-- 受注商品-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>受注商品</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <!--選択商品を表示する-->
        <div id="row">
            <div class="col-sm-2 col-xs-3">画像</div>
            <div class="col-sm-4 col-xs-3">商品</div>
            <div class="col-xs-2 text-right">単価</div>
            <div class="col-xs-2 text-right">個数</div>
            <div class="col-xs-2 text-right">計</div>
        </div>
        <?php foreach($this->item as $v):?>
            <div class="row clearfix">
            	  <?php if($v['image']):?>
                	<div class="col-sm-2 col-xs-3"><a class="thumb bigger" style="background-image:url(<?=BASEURL."/".$v['image']?>)" href="<?=BASEURL."/".$v['image']?>" rel="lightbox[sample-group]"></a></div>
                <?php else:?>
                	<div class="col-sm-2 col-xs-3"><span class="thumb" style="background-image:url(<?=BASEURL."/noimage.jpg"?>)"></span></div>
                <?php endif;?>
                <div class="col-sm-4 col-xs-3">【<?=$v['number']?>】<?=$v['name']?></div>
                <div class="col-sm-2 col-xs-2 text-right"><?=number_format($v['price'])?>円</div>
                <div class="col-sm-2 col-xs-2 text-right"><?=number_format($v['quantity'])?><?=$v['unit']?></div>
                <div class="col-sm-2 col-xs-2 text-right"><?=number_format(($v['price']*$v['quantity']))?>円</div>
            </div>
        <?php endforeach;?>
            <div class="row">
                <div class="col-xs-9">小計</div>
                <div class="col-xs-3 text-right"><?=number_format($this->data['item_total'])?>円</div>
            </div>
            <div class="row">
                <div class="col-xs-9">消費税</div>
                <div class="col-xs-3 text-right"><?=number_format($this->data['tax_total'])?>円</div>
            </div>
            <div class="row">
                <div class="col-xs-9">送料</div>
                <div class="col-xs-3 text-right"><?=number_format($this->data['shipping_cost'])?>円</div>
            </div>
            <div class="row">
                <div class="col-xs-9">決済手数料</div>
                <div class="col-xs-3 text-right"><?=number_format($this->data['collect_cost'])?>円</div>
            </div>
            <div class="row">
                <div class="col-xs-9">割引</div>
                <div class="col-xs-3 text-right"><?=number_format($this->data['off_price'])?>円</div>
            </div>
            <div class="row">
                <div class="col-xs-9">ポイント使用</div>
                <div class="col-xs-3 text-right"><?=number_format($this->data['use_point'])?>円</div>
            </div>
            <div class="row">
                <div class="col-xs-9">合計</div>
                <div class="col-xs-3 text-right"><?=number_format($this->data['seikyu_cost'])?>円</div>
            </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--決済方法設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>決済方法設定</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="Accordion">
        		<?php foreach($this->setting['payment'] as $v):?>
               <?php if($this->data['payment_method'] == $v['id']):?>
                <div class="panelItem">
                    <input type="radio" name="Accordion" id="checkbox-<?=$v['id']?>" name="payment_method"/>
                    <label for="checkbox-<?=$v['id']?>">
                        <div class="AccordionItem"><?=$v['name']?></div>
                        <div class="AccordionPanel">
                            <div><?=$v['description']?></div>
                        </div>
                    </label>
                </div>
                <?php endif;?>
              <?php endforeach;?>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--受注主を選択-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>受注主情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="data-table">
        <table class="table table-striped table-responcive">
        <tbody>
                <tr>
                <th>お名前</th>
                <td><?=$this->data['cus_name']?> <?=$this->data['cus_name2']?></td>
                </tr>
                <tr>
                <th>フリガナ</th>
                <td><?=$this->data['cus_kana']?> <?=$this->data['cus_kana2']?></td>
                </tr>
                <tr>
                <th>メールアドレス</th>
                <td><?=$this->data['cus_mail']?></td>
                </tr>
                <tr>
                <th>電話番号</th>
                <td><?=$this->data['cus_tel']?>-<?=$this->data['cus_tel2']?>-<?=$this->data['cus_tel3']?></td>
                </tr>
                <tr>
                <th>携帯電話番号</th>
                <td><?=$this->data['cus_mtel']?>-<?=$this->data['cus_mtel2']?>-<?=$this->data['cus_mtel3']?></td>
                </tr>
                <tr>
                <th>性別</th>
                <td><?php
                foreach(array(1=>"女性",2=>"男性",3=>"その他",4=>"答えたくない") as $k=>$v){
						if($this->data['cus_sex'] ==$k){
							echo $v;
						}
					}
				?></td>
                </tr>
                <tr>
                <th>生年月日</th>
                <td><?=$this->data['cus_birthY']?>年<?=$this->data['cus_birthM']?>月<?=$this->data['cus_birthD']?>日</td>
                </tr>
                <tr>
                <th>住所</th>
                <td>〒<?=$this->data['cus_zip']?>-<?=$this->data['cus_zip2']?><br>
                   <?php foreach($this->pref as $v):?>
                   	<?php if($v['id'] == $this->data['cus_pref']):?>
                    		<?=$v['name']?>
                      <?php endif;?>
                   <?php endforeach;?>
				   <?=$this->data['cus_addr']?><br>
				   <?=$this->data['cus_addr2']?>
            </td>
            </tr>
         </tbody>
        </table>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--お届け先を選択-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>お届け先情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="data-table">
        <table class="table table-striped table-responcive">
        <tbody>
                <tr>
                <th>お名前</th>
                <td><?=$this->data['delivery_name']?> <?=$this->data['delivery_name2']?></td>
                </tr>
                <tr>
                <th>フリガナ</th>
                <td><?=$this->data['delivery_kana']?> <?=$this->data['delivery_kana2']?></td>
                <tr>
                <th>電話番号</th>
                <td><?=$this->data['delivery_tel']?>-<?=$this->data['delivery_tel2']?>-<?=$this->data['delivery_tel3']?></td>
                </tr>
                <tr>
                <th>住所</th>
                <td>〒<?=$this->data['delivery_zip']?>-<?=$this->data['delivery_zip2']?><br>
                   <?php foreach($this->pref as $v):?>
                   	<?php if($v['id'] == $this->data['delivery_pref']):?>
                    		<?=$v['name']?>
                      <?php endif;?>
                   <?php endforeach;?>
				   <?=$this->data['delivery_addr']?><br>
				   <?=$this->data['delivery_addr2']?>
            </td>
            </tr>
         </tbody>
        </table>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--お届け日時設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>お届け日時設定</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="data-table">
        <table class="table table-striped table-responcive">
        <tbody>
            <tr>
            <th>お届け日</th>
            <td><?=$this->data['delivery_date']?>
            </td>
            </tr>
            <tr>
            <th>お届け時間</th>
            <td><?=$this->data['delivery_time']?>
            </td>
            </tr>
         </tbody>
        </table>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>


<!--その他設定-->
<!--メッセージカード設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>その他、備考など</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <p><?=$this->data['order_comment']?></p>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>







            <div class="form-actions">
                    <!--編集用-->
                    <form action="<?=BASEURL?>/admin/order/update/" method="get">
                        <input type="hidden" name="id" value="<?=$this->data['id']?>">
                        <button type="submit" class="btn btn-large btn-block btn-primary">編集</button>
                    </form>
                    <!--削除用-->
                    <form action="<?=BASEURL?>/api/order/delete/" method="post">
                        <input type="hidden" name="ids" value="<?=$this->data['id']?>">
                        <button type="button" class="btn btn-large btn-block btn-danger" id="deleteAll">削除</button>
                    </form>
            </div>
    </div>
</div>

<script>
	$("#deleteAll").on("click",function(){
		if(window.confirm("本当に削除してもいいですか？")){
			var ck = $('input[name=ids]').val();
			var url = "<?=BASEURL?>/api/order/delete/";
			$.post(url,{ids:ck},function(data){
				if(data == "OK"){
					location.href = "<?=BASEURL?>/admin/order/";
				}
			});
		}
	});
	//HTMLを追加
	$("#htmlAdd").on("click",function(){
		if(window.confirm("記載された内容でHTMLを登録します。よろしいですか？")){
			$("form[name=html]").submit();
		}
	});
</script>
