<?php if($this->MsgStep):?>
	<div class="alert alert-success alert-fadeout">
    	<p><?=$this->MsgStep?></p>
    </div>
<?php endif;?>

<!--受注基本データ-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>受注情報詳細</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="data-table">
        <table class="table table-striped table-responcive">
            <tbody>
                <tr>
                <th>受注受注日</th>
                <td><?=$this->data['order_date']?></td>
                </tr>
                <tr>
                <th>受注番号</th>
                <td><?=$this->data['order_id']?></td>
                </tr>
                <tr>
                <th>受注種別</th>
                <td>
                    	<?php foreach(array(0=>"受注",1=>"見積もり") as $k=>$v):?>
                        <?php if($k == $this->data['order_kind']):?>
                        	<?=$v?>
                        <?php endif;?>
                        <?php endforeach;?>
                </td>
                </tr>
            </tbody>
        </table>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>




<!---商品情報-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>受注商品詳細</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="row hidden-xs">
            <div class="col-xs-3 col-sm-2">画像</div>
            <div class="col-xs-4">【商品番号】商品名</div>
            <div class="col-xs-2 text-right">単価</div>
            <div class="col-xs-1 col-sm-2 text-right">個数</div>
            <div class="col-xs-2 text-right">計</div>
        </div>
        <?php
		 foreach($this->item as $v):?>
            <div class="row clearfix">
            	  <?php if($v['image']):?>
                	<div class="col-xs-3 col-sm-2"><a class="thumb bigger" style="background-image:url(<?=BASEURL."/".$v['image']?>)" href="<?=BASEURL."/".$v['image']?>" rel="lightbox[sample-group]"></a></div>
                <?php else:?>
                	<div class="col-xs-3 col-sm-2"><span class="thumb" style="background-image:url(<?=BASEURL."/noimage.jpg"?>)"></span></div>
                <?php endif;?>
                <div class="col-xs-4">【<?=$v['number']?>】<?=$v['name']?></div>
                <div class="col-xs-2 text-right"><?php
				  $taxRatio = 1/100*$this->setting['tax']['ratio'];
					$price = $v['price'];
                echo number_format($price)?>円</div>
                <div class="col-xs-1 col-sm-2 text-right"><?=number_format($v['quantity'])?><?=$v['unit']?></div>
                <div class="col-xs-2 text-right"><?=number_format(($price*$v['quantity']))?>円</div>
            </div>
        <?php endforeach;?>
            <div class="row">
                <div class="col-xs-10">小計</div>
                <div class="col-xs-2 text-right"><?=number_format($this->data['item_total'])?>円</div>
            </div>
            <div class="row">
                <div class="col-xs-10">消費税</div>
                <div class="col-xs-2 text-right"><?=number_format($this->data['tax_total'])?>円</div>
            </div>
            <div class="row">
                <div class="col-xs-10">送料</div>
                <div class="col-xs-2 text-right"><?=number_format($this->data['shipping_cost'])?>円</div>
            </div>
            <div class="row">
                <div class="col-xs-10">割引</div>
                <div class="col-xs-2 text-right"><?=number_format($this->data['off_price'])?>円</div>
            </div>
            <div class="row">
                <div class="col-xs-10">ポイント使用</div>
                <div class="col-xs-2 text-right"><?=number_format($this->data['use_point'])?>円</div>
            </div>
            <div class="row">
                <div class="col-sm-10">合計</div>
                <div class="col-sm-2 text-right"><?=number_format($this->data['seikyu_cost'])?>円</div>
            </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>


<!--受注主を選択-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>受注主情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="data-table">
        	 <input type="hidden" name="member_no" value="<?=$this->data['member_no']?>">
        <table class="table table-striped table-responcive">
            <tbody>
                <tr>
                <th>お名前</th>
                <td><?=$this->data['cus_name']?> <?=$this->data['cus_name2']?></td>
                </tr>
                <tr>
                <th>フリガナ</th>
                <td><?=$this->data['cus_kana']?> <?=$this->data['cus_kana2']?></td>
                </tr>
                <tr>
                <th>メールアドレス</th>
                <td><?=$this->data['cus_mail']?></td>
                </tr>
                <tr>
                <th>電話番号</th>
                <td><?=$this->data['cus_tel']?>-<?=$this->data['cus_tel2']?>-<?=$this->data['cus_tel3']?></td>
                </tr>
                <tr>
                <th>携帯電話番号</th>
                <td><?=$this->data['cus_mtel']?>-<?=$this->data['cus_mtel2']?>-<?=$this->data['cus_mtel3']?></td>
                </tr>
                <tr>
                <th>性別</th>
                <td><?php
                foreach(array(1=>"女性",2=>"男性",3=>"その他",4=>"答えたくない") as $k=>$v){
						if($this->data['cus_sex'] ==$k){
							echo $v;
						}
					}
				?></td>
                </tr>
                <tr>
                <th>生年月日</th>
                <td><?=$this->data['cus_birthY']?>年<?=$this->data['cus_birthM']?>月<?=$this->data['cus_birthD']?>日</td>
                </tr>
                <tr>
                <th>住所</th>
                <td>〒<?=$this->data['cus_zip']?>-<?=$this->data['cus_zip2']?><br>
                   <?php foreach($this->pref as $v):?>
                   	<?php if($v['id'] == $this->data['cus_pref']):?>
                    		<?=$v['name']?>
                      <?php endif;?>
                   <?php endforeach;?>
				   <?=$this->data['cus_addr']?><br>
				   <?=$this->data['cus_addr2']?></td>
                </tr>
            </tbody>
        </table>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--お届け先を選択-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>お届け先情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="data-table">
        <table class="table table-striped table-responcive">
            <tbody>
                <tr>
                <th>お名前</th>
                <td><?=$this->data['delivery_name']?> <?=$this->data['delivery_name2']?></td>
                </tr>
                <tr>
                <th>フリガナ</th>
                <td><?=$this->data['delivery_kana']?> <?=$this->data['delivery_kana2']?></td>
                <tr>
                <th>電話番号</th>
                <td><?=$this->data['delivery_tel']?>-<?=$this->data['delivery_tel2']?>-<?=$this->data['delivery_tel3']?></td>
                </tr>
                <tr>
                <th>住所</th>
                <td>〒<?=$this->data['delivery_zip']?>-<?=$this->data['delivery_zip2']?><br>
                   <?php foreach($this->pref as $v):?>
                   	<?php if($v['id'] == $this->data['delivery_pref']):?>
                    		<?=$v['name']?>
                      <?php endif;?>
                   <?php endforeach;?>
				   <?=$this->data['delivery_addr']?><br>
				   <?=$this->data['delivery_addr2']?></td>
                </tr>
            </tbody>
        </table>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--お届け日時設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>お届け日時情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="data-table">
        <table class="table table-striped table-responcive">
            <tbody>
                <tr>
                <th>お届け日</th>
                <td><?=$this->data['delivery_date']?></td>
                </tr>
                <tr>
                <th>お届け時間</th>
                <td><?=$this->data['delivery_time']?></td>
                </tr>
            </tbody>
        </table>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--決済方法設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>決済方法設定</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="Accordion">
        		<?php foreach($this->setting['payment'] as $v):?>
               <?php if($this->data['payment_method'] == $v['id']):?>
                <div class="panelItem">
                    <input type="radio" name="Accordion" id="checkbox-<?=$v['id']?>" name="payment_method"/>
                    <label for="checkbox-<?=$v['id']?>">
                        <div class="AccordionItem"><?=$v['name']?></div>
                        <div class="AccordionPanel">
                            <div><?=$v['description']?></div>
                        </div>
                    </label>
                </div>
                <?php endif;?>
              <?php endforeach;?>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--その他設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>その他、備考など</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
           <p><?=$this->data['order_comment']?></p>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<div class="form-actions">
    <div class="row">
        <div class="col-sm-4">
        <!--編集用-->
            <form action="<?=BASEURL?>/admin/order/detail/" method="get">
                <input type="hidden" name="id" value="<?=$this->data['id']?>">
                <button type="submit" class="btn btn-large btn-block btn-primary">詳細へ</button>
            </form>
        </div>
        <div class="col-sm-4">
        <!--複製用-->
            <form action="<?=BASEURL?>/admin/order/update/" method="get">
                <input type="hidden" name="id" value="<?=$this->data['id']?>">
                <button type="submit" class="btn btn-large btn-block btn-warning">編集する</button>
            </form>
        </div>
        <div class="col-sm-4">
        <!--削除用-->
            <form action="<?=BASEURL?>/api/order/delete/" method="post">
                <input type="hidden" name="ids" value="<?=$this->data['id']?>">
                <button type="button" class="btn btn-large btn-block btn-danger" id="deleteAll">削除する</button>
            </form>
        </div>
    </div>
</div>
<script>
//削除用
$("#deleteAll").on("click",function(){
	if(window.confirm("本当に削除してもいいですか？")){
		var ck = $('input[name=ids]').val();
		var url = "<?=BASEURL?>/api/order/delete/";
		$.post(url,{ids:ck},function(data){
			if(data == "OK"){
				location.href = "<?=BASEURL?>/admin/order/";
			}
		});
	}
});
//HTMLを追加
$("#htmlAdd").on("click",function(){
	if(window.confirm("記載された内容でHTMLを登録します。よろしいですか？")){
		$("form[name=html]").submit();
	}
});

$(function(){
	//進捗情報変更
	$('#step').on('click',function(){
		if($('[name="check_order"]:checked').val()){
			var check_order = 1;
		}else{
			var check_order = 0;
		}
		if($('[name="check_payment_end"]:checked').val()){
			var check_payment_end = 1;
		}else{
			var check_payment_end = 0;
		}
		if($('[name="check_delivery"]:checked').val()){
			var check_delivery = 1;
		}else{
			var check_delivery = 0;
		}
		if($('[name="check_delivery_end"]:checked').val()){
			var check_delivery_end = 1;
		}else{
			var check_delivery_end = 0;
		}
		if($('[name="check_payment"]:checked').val()){
			var check_payment = 1;
		}else{
			var check_payment = 0;
		}
		if($('[name="check_follow_mail"]:checked').val()){
			var check_follow_mail = 1;
		}else{
			var check_follow_mail = 0;
		}
		var step = {
			'check_order':check_order,
			'check_payment_end':check_payment_end,
			'check_delivery':check_delivery,
			'check_delivery_end':check_delivery_end,
			'check_payment':check_payment,
			'check_follow_mail':check_follow_mail,
			'id':<?=$this->data['id']?>
		};
		$.post("<?=BASEURL?>/api/order/step",step,function(data){
			if(data == "OK"){
				$("#stepForm").submit();
			}else{
				console.log(data);
			}
		});
	});
	//アラート
	$(window).load(function(){
        window.setTimeout("$('.alert-fadeout').fadeOut()", 4000);
    });
});
</script>
