<!--商品選択部-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>商品情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->

        <!--カテゴリ選択部-->
        <p class="smallRow">↓カテゴリを選択してください。</p>
        <p class="smallRow text-right">横にスクロールします。→</p>
        <div class="max">
        <table>
        <tr>
        <td nowrap id="categorys"></td>
        </tr>
        </table>
        </div>

        <!--商品選択部-->
        <div class="max">
        <table>
        	<tr>
            <td nowrap id="itemlist"></td>
            </tr>
        </table>
        </div>

        <!--選択商品を表示する-->
        <div id="adding"></div>

    	</div>

  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<form action="<?=BASEURL?>/admin/order/updatefinish" method="post" id="form">


<!--受注基本データ-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>受注詳細情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="data-table">
        <table class="table table-striped table-responcive">
        <tbody>
            <tr>
            <th>受注受注日</th>
            <td>
                	　<select name="order_date" class="form-control">
                    	<?php
							$min = $this->setting['delivery']['shippingend']*-1;
							$max = $this->setting['delivery']['shippingend'];
							/*
							for($i=$min;$i<$max;$i++):
							*/
							for($i=-1100;$i<$max;$i++):
							?>
                        <?php if($i == $this->data['order_date'] || $i == 0):?>
                    			<option value="<?=date("Y-m-d",time()+60*60*24*$i)?>" selected><?=date("Y-m-d",time()+60*60*24*$i)?></option>
                        <?php else:?>
                    			<option value="<?=date("Y-m-d",time()+60*60*24*$i)?>"><?=date("Y-m-d",time()+60*60*24*$i)?></option>
                        <?php endif;?>
                      <?php endfor;?>
                    </select></td>
            </tr>
            <?php if($this->data['order_id']):?>
            <tr>
            <th>受注番号</th>
            <td>
                	<?=$this->data['order_id']?></td>
            </tr>
            <?php endif;?>
            <tr>
            <th>受注種別</th>
            <td>
                　<select name="order_kind" class="form-control">
                    <?php foreach(array(0=>"受注",1=>"見積もり") as $k=>$v):?>
                    <?php if($k == $this->data['order_kind']):?>
                            <option value="<?=$k?>" selected><?=$v?></option>
                    <?php else:?>
                            <option value="<?=$k?>"><?=$v?></option>
                    <?php endif;?>
                  <?php endforeach;?>
                </select>
            </td>
            </tr>
            <tr>
         </tbody>
        </table>
        </tr>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>


<!--受注主を選択-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>受注主情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <input type="hidden" name="member_no" value="<?=$this->data['member_no']?>">
        <div class="data-table">
        <table class="table table-striped table-responcive">
        <tbody>
            <tr>
            <th>お名前</th>
            <td class="form-inline">姓：<input type="text" name="cus_name" value="<?=$this->data['cus_name']?>" class="form-control">
            名：<input type="text" name="cus_name2" value="<?=$this->data['cus_name2']?>" class="form-control"></td>
            </tr>
            <tr>
            <th>フリガナ</th>
            <td class="form-inline">セイ：<input type="text" name="cus_kana" value="<?=$this->data['cus_kana']?>" class="form-control">
            メイ：<input type="text" name="cus_kana2" value="<?=$this->data['cus_kana2']?>" class="form-control"></td>
            </tr>
            <tr>
            <th>メールアドレス</th>
            <td><input type="text" name="cus_mail" value="<?=$this->data['cus_mail']?>" class="form-control"></td>
            </tr>
            <tr>
            <th>性別</th>
            <td>
            	<select name="cus_sex" class="form-control">
                <?php foreach(array(1=>"女性",2=>"男性",3=>"その他",4=>"答えたくない") as $k=>$v):?>
                <?php if($k == $this->data["cus_sex"]):?>
                	<option value="<?=$k?>" selected><?=$v?></option>
                <?php else:?>
                	<option value="<?=$k?>"><?=$v?></option>
                <?php endif;?>
                <?php endforeach;?>
              </select>
            </td>
            </tr>
            <tr>
            <th>生年月日</th>
            <td class="form-inline">
            	<input type="text" name="cus_birthY" value="<?=$this->data['cus_birthY']?>" class="form-control">年
            	<input type="text" name="cus_birthM" value="<?=$this->data['cus_birthM']?>" class="form-control">月
            	<input type="text" name="cus_birthD" value="<?=$this->data['cus_birthD']?>" class="form-control">日
            </td>
            </tr>
            <tr>
            <th>電話番号</th>
            <td class="form-inline">
            	<input type="text" name="cus_tel" value="<?=$this->data['cus_tel']?>" class="form-control">-
                <input type="text" name="cus_tel2" value="<?=$this->data['cus_tel2']?>" class="form-control">-
                <input type="text" name="cus_tel3" value="<?=$this->data['cus_tel3']?>" class="form-control">
            </td>
            </tr>
            <tr>
            <th>郵便番号</th>
            <td class="form-inline">
            	〒<input type="text" name="cus_zip" value="<?=$this->data['cus_zip']?>" class="form-control">-
                <input type="text" name="cus_zip2" value="<?=$this->data['cus_zip2']?>" class="form-control">
            </td>
            </tr>
            <tr>
            <th>住所</th>
            <td>
                <select name="cus_pref" class="form-control">
                	<option value="">選択</option>
                   <?php foreach($this->pref as $v):?>
                   	<?php if($v['id'] == $this->data['cus_pref']):?>
                		<option value="<?=$v['id']?>" selected><?=$v['name']?></option>
                      <?php else:?>
                		<option value="<?=$v['id']?>"><?=$v['name']?></option>
                      <?php endif;?>
                   <?php endforeach;?>
                </select><br>
                <input type="text" name="cus_addr" value="<?=$this->data['cus_addr']?>" class="form-control"><br>
                <input type="text" name="cus_addr2" value="<?=$this->data['cus_addr2']?>" class="form-control">
            </td>
            </tr>
         </tbody>
        </table>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--ポイント情報-->
<?php if($this->setting['point']['pointuse'] ==0):?>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2><?=$this->setting['point']['pointname']?>情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="data-table">
        <table class="table table-striped table-responcive">
        <tbody>
            <tr>
            <th>使用可能<?=$this->setting['point']['pointname']?>残高</th>
            <td><input type="text" id="point_balance" value="<?=$this->data['point']?>" disabled class="form-control"></td>
            </tr>
            <tr>
            <th>使用<?=$this->setting['point']['pointname']?></th>
            <td><input type="text" name="poinAmount" value="" class="form-control"><?=$this->setting['point']['pointname']?></td>
            </tr>
         </tbody>
        </table>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<?php endif;?>

<!--お届け先を選択-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>お届け先情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
		<p><label><input type="checkbox" id="samecus">お届け先がご受注主様と同じ場合はここをチェック</label></p>
        <div class="data-table">
        <table class="table table-striped table-responcive">
        <tbody>
            <tr>
            <th>お名前</th>
            <td class="form-inline">
            姓：<input type="text" name="delivery_name" value="<?=$this->data['delivery_name']?>" class="form-control">
           　名；<input type="text" name="delivery_name2" value="<?=$this->data['delivery_name2']?>" class="form-control">
            </td>
            </tr>
            <tr>
            <th>フリガナ</th>
            <td class="form-inline">
            セイ：<input type="text" name="delivery_kana" value="<?=$this->data['delivery_kana']?>" class="form-control">
            メイ：<input type="text" name="delivery_kana2" value="<?=$this->data['delivery_kana2']?>" class="form-control">
            </td>
            </tr>
            <tr>
            <th>電話番号</th>
            <td class="form-inline">
            	<input type="text" name="delivery_tel" value="<?=$this->data['delivery_tel']?>" class="form-control">-
            	<input type="text" name="delivery_tel2" value="<?=$this->data['delivery_tel2']?>" class="form-control">-
            	<input type="text" name="delivery_tel3" value="<?=$this->data['delivery_tel3']?>" class="form-control">
            </td>
            </tr>
            <tr>
            <th>郵便番号</th>
            <td class="form-inline">
            	〒<input type="text" name="delivery_zip" value="<?=$this->data['delivery_zip']?>" class="form-control">-
            	<input type="text" name="delivery_zip2" value="<?=$this->data['delivery_zip2']?>" class="form-control">
            </td>
            </tr>
            <tr>
            <th>住所</th>
            <td>
                <select name="delivery_pref" class="form-control">
                	<option value="">選択</option>
                   <?php foreach($this->pref as $v):?>
                   	<?php if($v['id'] == $this->data['delivery_pref']):?>
                		<option value="<?=$v['id']?>" selected><?=$v['name']?></option>
                      <?php else:?>
                		<option value="<?=$v['id']?>"><?=$v['name']?></option>
                      <?php endif;?>
                   <?php endforeach;?>
                </select><br>
                <input type="text" name="delivery_addr" value="<?=$this->data['delivery_addr']?>" class="form-control"><br>
                <input type="text" name="delivery_addr2" value="<?=$this->data['delivery_addr2']?>" class="form-control">
            </td>
            </tr>
         </tbody>
        </table>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--お届け日時設定-->>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>お届け日時設定</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="data-table">
        <table class="table table-striped table-responcive">
        <tbody>
            <tr>
            <th>お届け日</th>
            <td>
                	<select name="delivery_date" class="form-control">
                	<option value="">選択</option>
                 	<?php for($i=0;$i<60;$i++):?>
                    <?php if(date("Y-m-d",time()+60*60*24*$i) == $this->data['delivery_date']):?>
                  <option value="<?=date("Y-m-d",time()+60*60*24*$i)?>" selected><?=date("Y-m-d",time()+60*60*24*$i)?></option>
                  <?php else:?>
                  <option value="<?=date("Y-m-d",time()+60*60*24*$i)?>"><?=date("Y-m-d",time()+60*60*24*$i)?></option>
                  <?php endif;?>
                  <?php endfor;?>
                  </select>
            </td>
            </tr>
            <tr>
            <th>お届け時間</th>
            <td>
                	<select name="delivery_time" class="form-control">
                	<option value="">選択</option>
                 	<?php
                    	$timezonArr = explode("\n",str_replace("\r","",$this->setting['delivery']['shippingselection']));
					$timezonArr = str_replace("\n","",$timezonArr);
					for($i=0;$i<count($timezonArr);$i++):?>
                  <?php if($timezonArr[$i] == $this->data['delivery_time']):?>
                  <option value="<?=$timezonArr[$i]?>" selected><?=$timezonArr[$i]?></option>
                  <?php else:?>
                  <option value="<?=$timezonArr[$i]?>"><?=$timezonArr[$i]?></option>
                  <?php endif;?>
                  <?php endfor;?>
                  </select>
            </td>
            </tr>
         </tbody>
        </table>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--決済方法設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>決済方法設定</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="Accordion">
        		<?php foreach($this->setting['payment'] as $v):?>
                <div class="panelItem">
                	<?php if($v['id'] == $this->data['payment_method']):?>
                    <input type="radio" id="radio-<?=$v['id']?>" name="payment_method" value="<?=$v['id']?>" data-fee="<?=$v['fee']?>" checked>
                  <?php else:?>
                    <input type="radio" id="radio-<?=$v['id']?>" name="payment_method" value="<?=$v['id']?>" data-fee="<?=$v['fee']?>">
                  <?php endif;?>
                    <label for="radio-<?=$v['id']?>" style="display:block !important;">
                        <div class="AccordionItem"><?=$v['name']?></div>
                        <div class="AccordionPanel">
                            <div><?=str_replace("\n","<br>",$v['description'])?></div>
                        </div>
                    </label>
                </div>
              <?php endforeach;?>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>


<!--その他設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>その他、備考など</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->

        <p><textarea name="order_comment" rows="5" class="form-control"><?=$this->data['order_comment']?></textarea></p>

  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<input type="hidden" name="item" value="" id="items">
<input type="hidden" name="tax_total" value="" id="tax_total">
<input type="hidden" name="order_id" value="<?=$this->data['order_id']?>">
<input type="hidden" name="id" value="<?=$this->data['id']?>">

<!--ページ下部追従部-->
<div class="gfooter" id="gfooter">
<p class="clearfix"><a href="javascript:void(0)" id="calcdisp" class="hidden-sm hidden-md hidden-lg"><i class="fa fa-calculator"></i></a></p>
<div class="muted">
<ul id="calcration" class="row">
    <li class="col-sm-2">小計:<input type="text" name="item_total" class="form-control"readonly value="<?=$this->data['item_total']?>"></li>
    <li class="col-sm-2">送料:<input type="text" name="shipping_cost" class="form-control" readonly value="<?=$this->data['shipping_cost']?>"></li>
    <li class="col-sm-2">決済手数料:<input type="text" name="collect_cost" class="form-control" readonly value="<?=$this->data['collect_cost']?>"></li>
    <?php if($this->setting['discont']['discountUse'] ==0):?>
        <li class="col-sm-2">割引:<input type="text" name="off_price" class="form-control" value="<?=$this->data['off_price']?>"></li>
    <?php endif;?>
    <?php if($this->setting['point']['pointuse'] ==0):?>
        <li class="col-sm-2"><?=$this->setting['point']['pointname'] ?>:<input type="text" name="use_point" class="form-control" value="<?=$this->data['use_point']?>"></li>
    <?php endif;?>
    <li class="col-sm-2">合計:<input type="text" name="seikyu_cost" class="form-control"readonly value="<?=$this->data['seikyu_cost']?>"></li>
</ul>
</div>
</div>

</form>



            <div class="form-actions">
                <button class="btn btn-large btn-block btn-primary" id="sub">編集</button>
            </div>

<br><br><br><br><br><br><br>
<br><br><br><br><br><br><br>
    	</div>
    </div>
</div>
<script src="<?=BASEURL?>/js/help-validation.js"></script>
<script>
$(function(){
	$("#sub").on("click",function(){
		if(window.confirm("受注内容の編集を行ます。内容を変更される場合はキャンセルボタンを押してください。")){
			$("#form").submit();
		}
	});
});
</script>

<script>

<!-------###　　サジェスト部のスクリプト　　###------->
$(function(){
	//受注主会社名及び名前を入力した時
	$("[name=cus_campany] ,[name=cus_campany]").on("keyup",function(){
		var key = $(this);
		$.post("<?=BASEURL?>/api/user/getcustomer/",{"keyword":key.val()},function(data){
			if($("#searchBox")){
				$("#searchBox").remove();
			}
			//リスト収容用のboxを挿入
			var searchBox = $("<div>");
			searchBox.attr("id","searchBox");
			key.after(searchBox);

			var ul = $("<ul>");
			searchBox.append(ul);
			//$(document).click(function() {　$('#searchBox').hide();　});
			//リストを挿入
			var customers =  JSON.parse(data);
			if(customers[0].length >0 ){
				for(var i=0;i<customers[0].length;i++){
					var li =$("<li>");
					ul.append(li);
					var a = $("<a>");
					a.attr("href","javascript:void(0)");
					a.attr("id","cus_"+customers[0][i]['id']);
					a.addClass("cus");
					if(customers[0][i]['company']){
						a.text(customers[0][i]['company']+" "+customers[0][i]['name']);
					}else{
						a.text(customers[0][i]['name']);
					}
					li.append(a);
					var index = customers[0][i];
					a.on("click",function(){
						for(var j =0;j<customers[0].length;j++){
							if(customers[0][j]['id'] == $(this).attr("id").substr(4)){
								//クリックされたら値を挿入

								$("[name=cus_campany]").val(customers[0][j]['company']);
								$("[name=cus_div]").val(customers[0][j]['division']);
								$("[name=cus_fax]").val(customers[0][j]['fax']);
								$("[name=cus_name]").val(customers[0][j]['name']);
								$("[name=cus_kana]").val(customers[0][j]['kana']);
								$("[name=cus_tel]").val(customers[0][j]['tel']);
								$("[name=cus_zip]").val(customers[0][j]['zip']);
								$("[name=cus_pref]").val(customers[0][j]['pref']);
								$("[name=cus_addr]").val(customers[0][j]['addr']);
								$("[name=cus_addr2]").val(customers[0][j]['addr2']);
								$("[name=cus_mail]").val(customers[0][j]['mail']);
								$("[name=member_no]").val(customers[0][j]['id']);

								$("#point_balance").val(customers[0][j]['point']);

								$("[name=delivery_campay]").val(customers[0][j]['company']);
								$("[name=delivery_div]").val(customers[0][j]['division']);
								$("[name=delivery_name]").val(customers[0][j]['name']);
								$("[name=delivery_kana]").val(customers[0][j]['kana']);
								$("[name=delivery_tel]").val(customers[0][j]['tel']);
								$("[name=delivery_zip]").val(customers[0][j]['zip']);
								$("[name=delivery_pref]").val(customers[0][j]['pref']);
								$("[name=delivery_addr]").val(customers[0][j]['addr']);
								$("[name=delivery_addr2]").val(customers[0][j]['addr2']);

								//送料計算
								parseCart();

								//検索候補リストを削除
								$("#searchBox").remove();
								break;
							}
						}
					});
				}
			}
		});
	});
});
<!-------###　　以下は商品選択及び諸計算部のスクリプト　　###------->
//消費税の設定
var taxRatio =<?=$this->setting['tax']['ratio']?>;
var taxrule =<?=$this->setting['tax']['rule']?>;
//var taxkind =<?=$this->setting['tax']['knd']?>;
//var taxproduct =<?=$this->setting['tax']['product']?>;

//割引の設定
var discountUse = <?=$this->setting['discount']['discountUse']?>;
var discountShipping = <?=$this->setting['discount']['shippingDiscountUse']?>;
var shippingDiscountAmount = <?=$this->setting['discount']['shippingDiscountAmount']?>;

//送料の設定
var shippingList = JSON.parse('<?=json_encode($this->setting['shipping'])?>');
//商品リスト用配列
var cart =<?=$this->item?>;
//送料計算用配列
var doukonArr = [0];
var doukonfukaArr = [0];
<?php if($this->item):?>
for(var i = 0 ; i<cart.lentgth;i++){
	//最初の商品
	I:for(var j=0;j<shippingList.length;j++){
		if(cart[i]['data']["shipping"] == shippingList[j]['id']){
			for(var k in shippingList[j]){
				if("s"+$("[name=delivery_pref]").val() == k){
					if(cart[i]['data']["doukon"] ==0){
						//同梱可の場合
						doukonArr.push(( shippingList[j][k]*1));
					}else{
						//同梱不可の場合
						doukonfukaArr.push(( shippingList[j][k]*1));
					}
					break I;
				}
			}
		}
	}
}
<?php endif;?>

$(function(){
	//商品を展開
	parseCart();
	//ロード時に商品カテゴリリストを取得する
	$.post("<?=BASEURL?>/api/item/itemcategory",{merchant:<?=$this->user->id?>},function(data){
		var Categorys = JSON.parse(data);
		for(var i=0;i<Categorys.length;i++){
			//console.log(Categorys[i]['id']);
			var id =Categorys[i]['id'];
			var btn = $("<button>");
			btn.attr("id",id);
			btn.type = "button";
			btn.addClass("btn btn-warning");
			btn.text(Categorys[i]['name']);
			$("#categorys").append(btn);
			//商品カテゴリボタン押下時に商品リストをロードする。
			$(document).on("click","#"+id,function(){
				$.post(
					"<?=BASEURL?>/api/item/items",
					{
						"merchant":<?=$this->user->id?>,
						"category":$(this).attr("id")
					},
					function(data2){
						//console.log(JSON.parse(data2));
						itemAppend(JSON.parse(data2));
					}
				);
				 return false;
			});
		}
	});
	$('[name="off_price"]').on("change",function(){
		parseCart();
	});
	$('[name=delivery_pref]').on("change",function(){
		parseCart();
	});
	$('[name=poinAmount]').on("change",function(){
		$("[name=use_point]").val($(this).val());
		parseCart();
	});
});
//商品一覧を取得して値を挿入
function itemAppend(json){
	$("#itemlist").empty();
	var n =json.length *115;
	$("#itemlist").css("width",n+"px");
	for(var i =0;i<json.length;i++){
		//商品ごとの枠
		var div = $('<div class="pull-left">');
		div.css("margin-right","10px");
		$("#itemlist").append(div);
		//画像（サムネイル）
		var img = $('<a class="thumb">');
		if(json[i]["imagen"] == null){
			img.css("background-image","url(<?=BASEURL."/"?>/img/noimage.jpg)");
		}else{
			img.css("background-image","url(<?=BASEURL."/"?>"+json[i]["imagen"]+")");
			img.attr("href","<?=BASEURL."/"?>"+json[i]["imagen"]);
			img.attr("rel","lightbox[sample-group]");
			img.addClass("bigger");
		}
		div.append($('<p style="line-height:1em">').append(img));
		//価格
		div.append($('<p style="text-align:center;line-height:1em;font-weight:bold">').text(json[i]["price"]+"円"));
		//ボタン
		var btn2 = $("<button>");
		btn2.type = "button";
		btn2.addClass("btn btn-success");
		btn2.text(json[i]["number"]);
		btn2.attr("id",json[i]["number"]);
		div.append($('<p style="text-align:center;line-height:1em">').append(btn2));
		var id = json[i]["number"];
		$(document).on("click","#"+id,function(){
			addCart($(this).attr("id"));
		});
	}
}
function addCart(number){
	$.post(
		"<?=BASEURL?>/api/item/itemofnumber",
		{
			"merchant":<?=$this->user->id?>,
			"number":number
		},
		function(data2){
			var itemD = JSON.parse(data2);
			for(var i =0;i<cart.length;i++){
				if(cart[i]['data']['id'] == itemD['id']){
					cart[i]['q'] = cart[i]['q']*1 +1;
					var exists = true;
					break;
				}
			}
			if(!exists){
				addData = {'q':1,'data':itemD}
				cart.push(addData);
			}
			//表示用のスクリプトを記載
			parseCart();
		}
	);
	return false;
}
function delCart(number){
	for(var i =0;i<cart.length;i++){
		if(cart[i]['data']['number'] ==number){
			cart[i]['q'] = cart[i]['q']-1;
			if(cart[i]['q'] ==　0){
				//数量が０になった場合は、データ自体を削除
				cart.splice(i,1) ;
			}
			break;
		}
	}
	//表示用のスクリプトを記載
	parseCart();
	return false;
}
var collect_cost=0;

$('input[name="payment_method"]:radio').change( function() {
	parseCart();
});
function parseCart(){
	var shipping = 0;
	if(cart.length >0){
		//商品がカートに入っている場合
		var shoukei = 0;
		var adding = $("#adding");
		adding.empty();
		var divP = $('<div class="row heding">');
		adding.append(divP);
			var div6 = $('<div class="col-sm-2 col-xs-3">');
			var div7 = $('<div class="col-sm-4 col-xs-3">');
			var div8 = $('<div class="col-sm-2 col-xs-2 text-right">');
			var div9 = $('<div class="col-sm-2 col-xs-2 text-right">');
			var div10 = $('<div class="col-sm-2 col-xs-2 text-right">');
		div6.text("画像");
		div7.text("【商品番号】商品名");
		div8.text("単価");
		div9.text("数量");
		div10.text("価格");
		divP.append(div1).append(div2).append(div3).append(div4).append(div5);

		var via = 1/100*taxRatio;
		var zeiTotal = 0;
		for(var i = 0;i < cart.length;i++){
			var price = cart[i]['data']['price']*1;
			var kei = price*cart[i]['q'];
			shoukei = shoukei+kei;

			if(taxrule == 0){
				//四捨五入
				zeiTotal = Math.round((shoukei*(1+via))-shoukei);
			}else if(taxrule == 1){
				//切り上げ
				zeiTotal = Math.ceil((shoukei*(1+via))-shoukei);
			}else{
				//切り捨て
				zeiTotal = Math.floor((shoukei*(1+via))-shoukei);
			}

			//表示部分
			var divP2 = $('<div class="row">');
			adding.append(divP2);
			var div1 = $('<div class="col-sm-2 col-xs-3">');
			var div2 = $('<div class="col-sm-4 col-xs-3">');
			var div3 = $('<div class="col-sm-2 col-xs-2 text-right">');
			var div4 = $('<div class="col-sm-2 col-xs-2 text-right">');
			var div5 = $('<div class="col-sm-2 col-xs-2 text-right">');
			divP2.append(div1).append(div2).append(div3).append(div4).append(div5);
			var img2 = $('<a class="thumb">');
			if(cart[i]['data']["imagen"] == null){
				img2.css("background-image","url(<?=BASEURL."/"?>/img/noimage.jpg)");
			}else{
				img2.css("background-image","url(<?=BASEURL."/"?>"+cart[i]['data']["imagen"]+")");
				img2.attr("href","<?=BASEURL."/"?>"+cart[i]['data']["imagen"]);
				img2.attr("rel","lightbox[sample-group2]");
				img2.addClass("bigger");
			}
			div1.append(img2);
			div2.text("【"+cart[i]['data']["number"]+"】"+cart[i]['data']["name"]);
			if(cart[i]['data']['tax'] == 0){
				div3.text(commaSpred(price)+"円(外税)");
			}else{
				div3.text(commaSpred(price)+"円(内税)");
			}
			div4.text(cart[i]['q']+cart[i]['data']["unit"]);
			//数量の増減
			var btnP = $("<button>");
			btnP.addClass("btn btn-inverse plus");
			btnP.text("+");
			btnP.attr("id","p"+cart[i]['data']["number"]);
			var btnM = $("<button>");
			btnM.addClass("btn btn-inverse minus");
			btnM.text("-");
			btnM.attr("id","m"+cart[i]['data']["number"]);
			var id = "m"+cart[i]['data']["number"];
			div4.append(btnP).append(btnM);
			div5.text(commaSpred(kei)+"円");
			//送料計算用配列に追加

			I:for(var j=0;j<shippingList.length;j++){
				if(cart[i]['data']["shipping"] == shippingList[j]['id']){
					for(var k in shippingList[j]){
						if("s"+$("[name=delivery_pref]").val() == k){
							if(cart[i]['data']["doukon"] ==0){
								//同梱可の場合
								doukonArr.push(( shippingList[j][k]*1));
							}else{
								//同梱不可の場合
								doukonfukaArr.push(( shippingList[j][k]*1));
							}
							break I;
						}
					}
				}
			}
		}
		//決済手数料

		collect_cost = $('input[name="payment_method"]:checked').data("fee");

		if(taxrule == 0){
			//四捨五入(1+via)
			collect_cost = Math.round((collect_cost*(1+via)));
		}else if(taxrule == 1){
			//切り上げ
			collect_cost = Math.ceil((collect_cost*(1+via)));
		}else{
			//切り捨て
			collect_cost = Math.floor((collect_cost*(1+via)));
		}
		$("[name=collect_cost]").val(collect_cost);
		//送料計算
		if(doukonArr != []){
			shipping = Math.max.apply(null,doukonArr);
		}
		if(doukonfukaArr != []){
			for(var m in doukonfukaArr){
				shipping = shipping+doukonfukaArr[m];
			}
		}
		tax =zeiTotal;
		//合計欄
		var div11 = $('<div class="span10">');
		var div12 = $('<div class="span2 text-right">');
		var div13 = $('<div class="span10">');
		var div14 = $('<div class="span2 text-right">');
		/*
		var div15 = $('<div class="span10">');
		var div16 = $('<div class="span2 text-right">');
		*/
		div11.text("小計");
		div12.text(commaSpred(shoukei)+"円");
		var divP3 = $('<div class="row-fluid">');
		adding.append(divP3);
		divP3.append(div11).append(div12);

		div13.text("消費税");
		div14.text(commaSpred(tax)+"円");
		var divP4 = $('<div class="row-fluid">');
		adding.append(divP4);
		divP4.append(div13).append(div14);


		//ページ下部に値を挿入
		var pointAmount = $("[name=use_point]").val();
		if(discountShipping ==0 && shippingDiscountAmount <= shoukei){
			shipping = 0;
		}
		$('[name=shipping_cost]').val(shipping);
		<?php
		 if($this->setting['discont']['discountUse'] ==0){
			echo "var discount = $('[name=off_price]').val();";
			echo "goukei = shoukei+tax-discount+shipping+collect_cost-pointAmount;";
		}else{
			echo "goukei = shoukei+tax+shipping+collect_cost-pointAmount;";
		}
		?>
		$('[name="item_total"]').val(shoukei);
		$('[name="seikyu_cost"]').val(goukei);
		$('[name="tax_total"]').val(tax);

		//プラスボタン
		$(".plus").on("click",function(){
			addCart($(this).attr("id").substr(1));
		});
		//マイナスボタン
		$(".minus").on("click",function(){
			delCart($(this).attr("id").substr(1));
		});

		//商品情報をJsonに変換して非表示フィールドに挿入
		var itemData = JSON.stringify(cart);
		$("#items").val(itemData);

	}else{
		//商品がカートに入っていない場合
		$("#adding").text("商品が選択されていません");
	}
}

function commaSpred(num){
    return String(num).replace( /(\d)(?=(\d\d\d)+(?!\d))/g, '$1,');
}
</script>
