<?php if($this->paymentErr):
//GMO決済が完了出来なかった
?>
<div class="shopping">
<p class="titleBnr"><img src="<?=BASEURL?>/img/cart/shopping.png" alt="購入のお手続き"></p>


<div class="alert alert-danger">
            ご利用のカード情報で決済が出来ませんでした。再度カード情報を入力するか決済方法を変更してください。
</div>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>カートの中の商品</h2>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
			<!--中身-->
                <div class="incart">
                    <ul>
                    　<?php foreach($this->item as $v):?>
                        <li>
                            <div class="clearfix">
                                <?php if($v['image'][0]['url']):?>
                                    <img src="<?=BASEURL."/".$v['image'][0]['url']?>">
                                <?php endif;?>
                                <p>【<?=$v['number']?>】 <?=$v['name']?></p>
                                <p>単価：<?=number_format($v['price'])?>円</p>
                            </div>
    
                            <div class="clearfix updateDelete">
                               <span class="tq"><?=$v['q']?><?=$v['unit']?></span>
                            <div class="itotal">
                            	<span class="tt">計：<?=number_format(($v['price']*$v['q']))?>円</span>
                            </div>
                            </div>
                        </li>
                    <?php endforeach;?>
                    </ul>
           		 <div class="total clearfix"><span class="tq">商品点数：<?=$this->detail['c']?>点</span><span class="tt">小計：<?=number_format($this->detail['t'])?>円</span></div>
           		 <div class="total clearfix"><span class="tt">消費税：<?=number_format($this->detail['tax_total'])?>円</span></div>
                 	<?php if($this->setting['point']['pointuse']==0 && $this->detail['poinAmount'] > 0):?>
           		 <div class="total clearfix"><span class="tq">使用<?=$this->setting['point']['pointname']?></span><span class="tt">-<?=number_format($this->detail['poinAmount'])?>円</span></div>
                 	<?php endif;?>
           		 <div class="total clearfix"><span class="tq">送料</span><span class="tt"><?=number_format($this->detail['shipping'])?>円</span></div>
           		 <div class="total clearfix"><span class="tq">合計</span><span class="tt"><?=number_format($this->detail['total'])?>円</span></div>
                 </div>
			<!--中身-->
      </div>
    </div>
  </div>
</section>

<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>注文主様情報</h2>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
		<!--中身--><div class="formset">
        	<div class="line clearfix">
           	<div class="left"><label for="cus_name" class="required clearfix">お名前</label></div>
           	<div class="right"><?=$this->detail['cus_name']?> <?=$this->detail['cus_name2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_kana" class="required clearfix">フリガナ</label></div>
           	<div class="right"><?=$this->detail['cus_kana']?> <?=$this->detail['cus_kana2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="mail" class="required clearfix">メールアドレス</label></div>
           	<div class="right"><?=$this->detail['cus_mail']?><br>
                ※当社からのメールを受信できるよう<br>
                「@john-mary.com」のドメイン受信設定をお願いします。
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_sex" class="required clearfix">性別</label></div>
           	<div class="right">
                        <?php foreach(array(1=>"女性",2=>"男性") as $k=>$v):?>
                        <?php if($k== $this->detail['cus_sex']):?>
                        <?=$v?>
                        <?php endif;?>
                        <?php endforeach;?>
                    </select>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_birthY" class="required clearfix">生年月日</label></div>
           	<div class="right"><?=$this->detail['cus_birthY']?>年　<?=$this->detail['cus_birthM']?>月　 <?=$this->detail['cus_birthD']?>日
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_tel" class="required clearfix">電話番号（携帯可）</label></div>
           	<div class="right"><?=$this->detail['cus_tel']?>-<?=$this->detail['cus_tel2']?>-<?=$this->detail['cus_tel3']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_mtel" class="">緊急連絡先</label></div>
           	<div class="right"><?=$this->detail['cus_mtel']?>-<?=$this->detail['cus_mtel2']?>-<?=$this->detail['cus_mtel3']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_zip" class="required clearfix">郵便番号</label></div>
           	<div class="right"><?=$this->detail['cus_zip']?>-<?=$this->detail['cus_zip2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_pref" class="required clearfix">都道府県</label></div>
           	<div class="right">
                        <?php foreach($this->pref as $v):?>
                        <?php if($v['id'] == $this->detail['cus_pref']):?>
                        <?=$v['name']?>
                        <?php endif;?>
                        <?php endforeach;?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_addr" class="required clearfix">市区町村、番地</label></div>
           	<div class="right"><?=$this->detail['cus_addr']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_addr2" class="">ビル名・マンション名、号室</label></div>
           	<div class="right"><?=$this->detail['cus_addr2']?>
               </div>
           </div>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<!--お届け先を選択-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>お届け先情報</h2>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
		<!--中身--><div class="formset">
        	<div class="line clearfix">
           	<div class="left"><label for="cus_name" class="required clearfix">お名前</label></div>
           	<div class="right"><?=$this->detail['delivery_name']?> <?=$this->detail['delivery_name2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_name" class="required clearfix">フリガナ</label></div>
           	<div class="right"><?=$this->detail['delivery_kana']?> <?=$this->detail['delivery_kana2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_tel" class="required clearfix">電話番号（携帯可）</label></div>
           	<div class="right"><?=$this->detail['delivery_tel']?>-<?=$this->detail['delivery_tel2']?>-<?=$this->detail['delivery_tel3']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="delivery_zip" class="required clearfix">郵便番号</label></div>
           	<div class="right"><?=$this->detail['delivery_zip']?>-<?=$this->detail['delivery_zip2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="delivery_pref" class="required clearfix">都道府県</label></div>
           	<div class="right">
                        <?php foreach($this->pref as $v):?>
                        <?php if($v['id'] == $this->detail['delivery_pref']):?>
                        <?=$v['name']?>
                        <?php endif;?>
                        <?php endforeach;?>
                    </select>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="delivery_addr" class="required clearfix">市区町村、番地</label></div>
           	<div class="right"><?=$this->detail['delivery_addr']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="delivery_addr2" class="">ビル名・マンション名、号室</label></div>
           	<div class="right"><?=$this->detail['delivery_addr2']?>
               </div>
           </div>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<?php if($this->setting['delivery']['shippingdate'] ==0 || $this->setting['delivery']['shippingtime'] ==0):?>
<!--お届け日時設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h3>お届け日時設定</h3>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
		<!--中身-->
        
        <p>※お届け希望日、希望時間帯は、天候、天災、交通情勢の都合により、ご希望に添えない場合があります。</p>
        <div class="formset">
				<?php if($this->setting['delivery']['shippingdate'] ==0):?>
        	<div class="line clearfix">
                <div class="left"><label for="delivery_date">お届け希望日</label></div>
                <div class="right"><?=$this->detail['delivery_date']?>
                </div>
                </div>
                <?php endif;?>
				<?php if($this->setting['delivery']['shippingtime'] ==0):?>
                <div class="line clearfix">
                <div class="left"><label for="delivery_date">お届け希望時間帯</label></div>
                <div class="right"><?=$this->detail['delivery_time']?>
                </div>
                </div>
                <?php endif;?>
         </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<?php endif;?>
<!--決済方法設定-->
<form action="<?=BASEURL?>/order/finish" method="post" id="finish">
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2 id="payment_method">決済方法設定</h2><label class="required"></label>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
        <div class="alert alert-danger">
            ご利用のカード情報で決済が出来ませんでした。再度カード情報を入力するか決済方法を変更してください。
        </div>
		<!--中身-->
        <div class="formset">
        	<?php foreach($this->setting['payment'] as $v):?>
                <div class="line clearfix">
                    <div class="left">
                        <div class="form-group">
                        <label class="checkbox-inline">
                         <?php if($v['id'] == $this->detail['payment_method']):?>
                            <input type="radio" id="radio-<?=$v['id']?>" name="payment_method" value="<?=$v['id']?>" checked/>
                         <?php else:?>
                            <input type="radio" id="radio-<?=$v['id']?>" name="payment_method" value="<?=$v['id']?>"/>
                         <?php endif;?>
                        <?=$v['name']?>
                        </label>
                        </div>
                    </div>
                <div class="right">
                            <div><?=str_replace("\n","<br>",$v['description'])?>
                            	<?php if($v['gmoFlug'] == 1):?>
                                <p><img class="alignnone wp-image-437 size-full" src="http://www.john-mary.com/wp-content/themes/_jm/img/guide/cresit.png" alt="cresit" width="526" height="96"></p>
                                <p>ご注文完了と同時にクレジットカード決済が行われます。下記の項目にクレジットカード情報を入力してください。</p>
                                <div class="data-table">
                                    <table class="table table-striped table-responcive">
                                        <tbody>
                                            <tr>
                                            	<th>カード番号</th>
                                            	<td><input type="text" name="CardNo" class="form-control"></td>
                                            </tr>
                                            <tr>
                                            	<th>有効期限</th>
                                            	<td class="form-inline"><input type="text" name="ExpireMM" class="form-control">月<input type="text" name="ExpireYY" class="form-control">年</td>
                                            </tr>
                                            <tr>
                                            	<th>セキュリティコード</th>
                                            	<td><input type="text" name="SecurityCode" class="form-control"></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                <p><img src="<?=BASEURL?>/img/security.gif"><br>※セキュリティコードとは、カード裏面に記載（AmericanExpressは前面）に記載の３桁の数字です。<br>
                                </div>
                                 <?php elseif($v['gmoFlug'] == 2):?>
                                <p><br>
                	<img src="http://www.john-mary.com/wp-content/themes/_jm/img/guide/cvs/lowson.png" alt="ローソン" width="36" height="36">
                 	<img src="http://www.john-mary.com/wp-content/themes/_jm/img/guide/cvs/familymart.png" alt="ファミリーマート" width="36" height="36">
                  <img src="http://www.john-mary.com/wp-content/themes/_jm/img/guide/cvs/sanks.png" alt="サンクス" width="36" height="36">
                  <img src="http://www.john-mary.com/wp-content/themes/_jm/img/guide/cvs/cerclK.png" alt="サークル" width="36" height="36">
                  <img src="http://www.john-mary.com/wp-content/themes/_jm/img/guide/cvs/misistop.png" alt="ミニストップ" width="36" height="36">
                  <img src="http://www.john-mary.com/wp-content/themes/_jm/img/guide/cvs/dayly.png" alt="デイリーヤマザキ" width="36" height="36">
                  <img src="http://www.john-mary.com/wp-content/themes/_jm/img/guide/cvs/seikomart.png" alt="セイコーマート" width="36" height="36">
                  <img src="http://www.john-mary.com/wp-content/themes/_jm/img/guide/cvs/threeF.png" alt="スリーエフ" width="36" height="36"></p>
                                <p>下記のコンビニブランドよりご希望のものをお選びください。</p>
                                <div class="data-table">
                                    <table class="table table-striped table-responcive">
                                        <tbody>
                                            <tr>
                                            	<th>コンビニブランド</th>
                                            	<td>
                                               	<select name="Convenience" class="form-control">
                                                		<?php foreach(array(/*"00007"=>"セブンイレブン",*/"10001"=>"ローソン","10002"=>"ファミリーマート","00003"=>"サンクス","00004"=>"サークルK","10005"=>"ミニストップ","00006"=>"デイリーヤマザキ","00008"=>"セイコーマート","00009"=>"スリーエフ") as $k=>$vv):?>
                                                      <?php if($this->data['Convenience'] == $k):?>
                                                		<option value="<?=$k?>" selected><?=$vv?></option>
                                                      <?php else:?>
                                                		<option value="<?=$k?>"><?=$vv?></option>
                                                      <?php endif;?>
                                                      <?php endforeach;?>
                                                	</select> 
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                 
                                 <?php endif;?>
                </div>
            </div>
        </div>
              <?php endforeach;?>
          </div>
        
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--その他設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>その他、備考など</h2>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
		<!--中身-->
        
        <p><?=nl2br($this->detail['order_comment'])?></p>

  		<!--中身-->
        </div>
      </div>
    </div>
</section>
	<?php foreach($this->detail as $k=>$v):?>
    	<?php if($k == "payment_method"):?>
        <?php else:?>
    		<input type="hidden" name="<?=$k?>" value="<?=$v?>">
        <?php endif;?>
    <?php endforeach;?>
    <p class="text-center"><button type="submit" class="btn btn-success btn-lg">注文を確定する</button></p>
</form>
</div>



<?php else:?>
<script>
// eコマースプラグインの呼び出し
ga('require', 'ecommerce', 'ecommerce.js');

// ecommerce:addTransaction でトランザクションの出力
ga('ecommerce:addTransaction', {
  'id': '<?=$this->detail['order_id'] ?>',             // transaction ID（トランザクションID） - 必須
  'affiliation': 'JOHN & MARY',        // affiliation or store name（アフィリエーション or 店名）
  'revenue': '<?=$this->detail['seikyu_cost'] ?>',        // grand Total（総額）
  'shipping': '<?=$this->detail['shipping_cost'] ?>',           // shipping（送料）
  'tax': '<?=$this->detail['tax_total'] ?>'                 // tax（税額）
});
<?php foreach($this->item as $v):?>
// ecommerce:addItem で購入商品出力。購入商品ごとに出力されるようにする
ga('ecommerce:addItem', {
  'id': '<?=$this->detail['order_id'] ?>',             // transaction ID（トランザクションID） - 必須
  'name': '<?=$v['name']?>',  // product name（商品名） - 必須
  'sku': '<?=$v['number']?>',            // SKU/code（商品SKU）
  'category': '<?=$v['category']?>',         // category or variation（カテゴリーやバリエーション）
  'price': '<?=$v['price']?>',          // unit price（価格）
  'quantity': '<?=$v['q']?>'           // quantity（数量）
});
<?php endforeach;?>
// 確定したトランザクション情報をGoogleアナリティクスのサーバに送信
ga('ecommerce:send');
</script>
<div class="shopping">
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_content">
			<!--中身-->
            	<p style="font-size:24px">ご注文ありがとうございます。</p>
             <p><?=$this->detail['cus_mail']?>宛にご注文の控えを送信しています。もし、注文内容に変更などがありましたら、控えのメールに返信されるか、<?=$this->setting['global']['infoMail']?>宛に変更内容を送信してください。</p>
             <!---決済ASPを使用する場合-->
             <?php foreach($this->setting['payment'] as $v):
				if($v['id'] == $this->detail['payment_method'] && $v['url']):?>
                	<p class="text-center" style="font-size:18px;font-weight:bold;"><?=$v['name']?>を選択された方は、下のボタンより決済手続きを行ってください。</p>
					<form action="<?=$v['url']?>" method="<?=$v['method']?>" target="<?=$v['target']?>" enctype="<?=$v['enctype']?>">
                    <?php
							$patterns[0] = '/<!--seikyu_cost-->/';
							$patterns[1] = '/<!--cus_tel-->/';
							$patterns[2] = '/<!--cus_mail-->/';
							$patterns[3] = '/<!--c_id-->/';
							$replacements[0] = $this->detail['total'];
							$replacements[1] = $this->detail['cus_tel'];
							$replacements[2] = $this->detail['cus_mail'];
							$replacements[3] = $this->detail['member_no'];
							$v['pram'] = preg_replace($patterns, $replacements, htmlspecialchars_decode($v['pram']));
							$param = explode("\n",str_replace("\r","",$v['pram']));
							 foreach($param as $vv){
								 $pram2 = explode("=",$vv);
								 echo "<input type=\"hidden\" name=\"".$pram2[0]."\" value=\"".$pram2[1]."\">";
							}
						?>
                        <p class="text-center"><button type="submit" class="btn btn-success btn-lg"><?=$v['name']?>へ進む</button></p>
                  </form>
				<?php break; endif;	 
			endforeach;?>
            
            <?php if($this->memberRegist):?>
            	<p>会員を同時に行いました。次回以降は、ご登録頂いたメールアドレスとパスワードにて「<a href="<?=BASEURL?>/signin/">ログイン画面</a>」よりログインしていただけます。</p>
            <?php endif;?>
			<!--中身-->
      </div>
    </div>
  </div>
</section>

<p style="font-size:24px" class="text-center">以下は、ご注文内容です。</p>

<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>カートの中の商品</h2>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
			<!--中身-->
                <div class="incart">
                    <ul>
                    　<?php foreach($this->item as $v):?>
                        <li>
                            <div class="clearfix">
                                <?php if($v['image'][0]['url']):?>
                                    <img src="<?=BASEURL."/".$v['image'][0]['url']?>">
                                <?php endif;?>
                                <p>【<?=$v['number']?>】 <?=$v['name']?></p>
                                <p>単価：<?=number_format($v['price'])?>円</p>
                            </div>
    
                            <div class="clearfix updateDelete">
                                    <?=$v['q']?><?=$v['unit']?>
                            <div class="itotal">
                            	計：<?=number_format(($v['price']*$v['q']))?>円
                            </div>
                            </div>
                        </li>
                    <?php endforeach;?>
                    </ul>
           		 <div class="total clearfix"><span class="tq">商品点数：<?=$this->c?>点</span><span class="tt">小計：<?=number_format($this->detail['item_total'])?>円</span></div>
           		 <div class="total clearfix"><span class="tt">消費税：<?=number_format($this->detail['tax_total'])?>円</span></div>
                 	<?php if($this->setting['point']['pointuse']==0 && $this->detail['use_point'] > 0):?>
           		 <div class="total clearfix"><span class="tq">使用<?=$this->setting['point']['pointname']?></span><span class="tt">-<?=number_format($this->detail['use_point'])?>円</span></div>
                 	<?php endif;?>
           		 <div class="total clearfix"><span class="tq">送料</span><span class="tt"><?=number_format($this->detail['shipping_cost'])?>円</span></div>
           		 <div class="total clearfix"><span class="tq">合計</span><span class="tt"><?=number_format($this->detail['seikyu_cost'])?>円</span></div>
          </div>
			<!--中身-->
      </div>
    </div>
  </div>
</section>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>注文主様情報</h2>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
		<!--中身--><div class="formset">
        	<div class="line clearfix">
           	<div class="left"><label for="cus_name" class="required clearfix">お名前</label></div>
           	<div class="right"><?=$this->detail['cus_name']?> <?=$this->detail['cus_name2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_kana" class="required clearfix">フリガナ</label></div>
           	<div class="right"><?=$this->detail['cus_kana']?> <?=$this->detail['cus_kana2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="mail" class="required clearfix">メールアドレス</label></div>
           	<div class="right"><?=$this->detail['cus_mail']?><br>
                ※当社からのメールを受信できるよう<br>
                「@john-mary.com」のドメイン受信設定をお願いします。
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_sex" class="required clearfix">性別</label></div>
           	<div class="right">
                        <?php foreach(array(1=>"女性",2=>"男性") as $k=>$v):?>
                        <?php if($k== $this->detail['cus_sex']):?>
                        <?=$v?>
                        <?php endif;?>
                        <?php endforeach;?>
                    </select>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_birthY" class="required clearfix">生年月日</label></div>
           	<div class="right"><?=$this->detail['cus_birthY']?>年　<?=$this->detail['cus_birthM']?>月　 <?=$this->detail['cus_birthD']?>日
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_tel" class="required clearfix">電話番号</label></div>
           	<div class="right"><?=$this->detail['cus_tel']?>-<?=$this->detail['cus_tel2']?>-<?=$this->detail['cus_tel3']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_mtel" class="">携帯電話番号</label></div>
           	<div class="right"><?=$this->detail['cus_mtel']?>-<?=$this->detail['cus_mtel2']?>-<?=$this->detail['cus_mtel3']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_zip" class="required clearfix">郵便番号</label></div>
           	<div class="right"><?=$this->detail['cus_zip']?>-<?=$this->detail['cus_zip2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_pref" class="required clearfix">都道府県</label></div>
           	<div class="right">
                        <?php foreach($this->pref as $v):?>
                        <?php if($v['id'] == $this->detail['cus_pref']):?>
                        <?=$v['name']?>
                        <?php endif;?>
                        <?php endforeach;?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_addr" class="required clearfix">市区町村、番地</label></div>
           	<div class="right"><?=$this->detail['cus_addr']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_addr2" class="">ビル名・マンション名、号室</label></div>
           	<div class="right"><?=$this->detail['cus_addr2']?>
               </div>
           </div>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<!--お届け先を選択-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>お届け先情報</h2>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
		<!--中身--><div class="formset">
        	<div class="line clearfix">
           	<div class="left"><label for="cus_name" class="required clearfix">お名前</label></div>
           	<div class="right"><?=$this->detail['delivery_name']?> <?=$this->detail['delivery_name2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_name" class="required clearfix">フリガナ</label></div>
           	<div class="right"><?=$this->detail['delivery_kana']?> <?=$this->detail['delivery_kana2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="cus_tel" class="required clearfix">電話番号</label></div>
           	<div class="right"><?=$this->detail['delivery_tel']?>-<?=$this->detail['delivery_tel2']?>-<?=$this->detail['delivery_tel3']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="delivery_zip" class="required clearfix">郵便番号</label></div>
           	<div class="right"><?=$this->detail['delivery_zip']?>-<?=$this->detail['delivery_zip2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="delivery_pref" class="required clearfix">都道府県</label></div>
           	<div class="right">
                        <?php foreach($this->pref as $v):?>
                        <?php if($v['id'] == $this->detail['delivery_pref']):?>
                        <?=$v['name']?>
                        <?php endif;?>
                        <?php endforeach;?>
                    </select>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="delivery_addr" class="required clearfix">市区町村、番地</label></div>
           	<div class="right"><?=$this->detail['delivery_addr']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left"><label for="delivery_addr2" class="">ビル名・マンション名、号室</label></div>
           	<div class="right"><?=$this->detail['delivery_addr2']?>
               </div>
           </div>
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<?php if($this->setting['delivery']['shippingdate'] ==0 || $this->setting['delivery']['shippingtime'] ==0):?>
<!--お届け日時設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h3>お届け日時設定</h3>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
		<!--中身-->
        
        <p>※お届け希望日、希望時間帯は、天候、天災、交通情勢の都合により、ご希望に添えない場合があります。</p>
        <div class="formset">
				<?php if($this->setting['delivery']['shippingdate'] ==0):?>
        	<div class="line clearfix">
                <div class="left"><label for="delivery_date">お届け希望日</label></div>
                <div class="right"><?=$this->detail['delivery_date']?>
                </div>
                </div>
                <?php endif;?>
				<?php if($this->setting['delivery']['shippingtime'] ==0):?>
                <div class="line clearfix">
                <div class="left"><label for="delivery_date">お届け希望時間帯</label></div>
                <div class="right"><?=$this->detail['delivery_time']?>
                </div>
                </div>
                <?php endif;?>
         </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<?php endif;?>
<?php if($this->setting['global']['messageCardUse'] ==0):?>
<!--メッセージカード設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>メッセージカード設定</h2>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="data-table">      
        <table class="table table-striped table-responcive">
        <tbody>
            <tr>
            <th>用途</th>
            <td>
                 	<?php
					$youtoArr = $this->setting['youto'];
					for($i=0;$i<count($youtoArr);$i++):
					if($this->data['youto'] == $youtoArr[$i]['id']):?>
					<?=$youtoArr[$i]['name']?>
                    <?php break;
					endif;?>
                  <?php endfor;?>
            </td>
            </tr>
            <tr>
            <th>メッセージカード種類</th>
            <td>
                 	<?php
					$msgArr = explode("\n",str_replace("\r","",$this->setting['global']['messageCardKind']));
					$msgArr = str_replace("\n","",$msgArr);
					for($i=0;$i<count($msgArr);$i++):
					if($msgArr[$i] == $this->data['noshi_kind']):?>
					<?=$msgArr[$i]?>
                    <?php break;
					endif;?>
                  <?php endfor;?>
                  </select>
            </td>
            </tr>
            <tr>
            <th>メッセージカード内容</th>
            <td><?=$this->data['message']?>
            </td>
            </tr>
         </tbody>
        </table>        
        </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>
<?php endif;?>
<!--決済方法設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2 id="payment_method">決済方法設定</h2>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="formset">
        	<?php foreach($this->setting['payment'] as $v):
				if($v['id'] == $this->detail['payment_method']):?>
                <div class="line clearfix">
                    <div class="left">
                        <div class="form-group">
                        <label class="checkbox-inline">
                        <?=$v['name']?>
                        </label>
                        </div>
                    </div>
                <div class="right">
                            <div><?=str_replace("\n","<br>",$v['description'])?>
                </div>
            </div>
        </div>
              <?php endif; endforeach;?>
          </div>
  		<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--その他設定-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>その他、備考など</h2>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
		<!--中身-->
        
        <p><?=str_replace("\n","<br>\n",str_replace("\r","",$this->data['order_comment']))?></p>

  		<!--中身-->
        </div>
      </div>
    </div>
</section>
</div>
<?php endif;?>