<?php if(!empty($this->html[0]['html']) || !empty($this->html[0]['thumb']) || !empty($this->html[0]['thumb2'])):?>
        <?php if(!empty($this->html[0]['thumb'])):?>
            <div class="banner">
            <div class="hidden-xs">
            <p class="text-center"><img src="<?=BASEURL.$this->html[0]['thumb']?>" alt="<?=$this->html[0]['page']?>"></p>
            </div>
		<?php endif;?>
        <?php if(!empty($this->html[0]['thumb2'])):?>
            <div class="visible-xs">
            <p class="text-center"><img src="<?=BASEURL.$this->html[0]['thumb2']?>" alt="<?=$this->html[0]['page']?>"></p>
            </div>
            </div>
		<?php endif;?>
        <?=htmlspecialchars_decode($this->html[0]['html'])?>
<?php endif;?>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>本数指定で注文</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="row">
            <div class="col-sm-2">
            	<img src="<?=BASEURL?>/img/1676_20160420063650.jpg" alt="おまかせフラワーアレンジメント">
            </div>
            <div class="col-sm-4">
        		<h3>赤バラを本数指定で購入</h3>
                <form action="<?=BASEURL?>/order" method="post">
                <p class="form-inline">
                <input type="hidden" name="number" value="vs-rros">価格：400円</p>
                <p>8本以上でご購入いただけます</p>
                <p class="form-inline">
                <select name="quantity" class="form-control">
                <?php for($i=8;$i<101;$i++):?>
                <option value="<?=$i?>"><?=$i?></option>
                <?php endfor;?>
                </select>  個</p>
                <button type="submit" class="btn btn-success btn-lg">購入する</button>
                </form>
            </div>
            <div class="col-sm-2">
            	<img src="<?=BASEURL?>/img/1677_20160420063628.jpg" alt="おまかせフラワーアレンジメント">
            </div>
            <div class="col-sm-4">
        		<h3>ピンクバラを本数指定で購入</h3>
                <form action="<?=BASEURL?>/order" method="post">
                <p class="form-inline">
                <input type="hidden" name="number" value="vs-prose">価格：400円</p>
                <p>8本以上でご購入いただけます</p>
                <p class="form-inline">
                <select name="quantity" class="form-control">
                <?php for($i=8;$i<101;$i++):?>
                <option value="<?=$i?>"><?=$i?></option>
                <?php endfor;?>
                </select>  個</p>
                <button type="submit" class="btn btn-success btn-lg">購入する</button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
            	<img src="<?=BASEURL?>/img/1678_20160420063612.jpg" alt="おまかせフラワーアレンジメント">
            </div>
            <div class="col-sm-4">
        		<h3>黄バラを本数指定で購入</h3>
                <form action="<?=BASEURL?>/order" method="post">
                <p class="form-inline">
                <input type="hidden" name="number" value="vs-yrose">価格：400円</p>
                <p>8本以上でご購入いただけます</p>
                <p class="form-inline">
                <select name="quantity" class="form-control">
                <?php for($i=8;$i<101;$i++):?>
                <option value="<?=$i?>"><?=$i?></option>
                <?php endfor;?>
                </select>  個</p>
                <button type="submit" class="btn btn-success btn-lg">購入する</button>
                </form>
            </div>
        </div>
        
        
        <div class="row">
            <div class="col-sm-2">
            	<img src="<?=BASEURL?>/img/1675_20160420063712.jpg" alt="おまかせフラワーアレンジメント">
            </div>
            <div class="col-sm-4">
        		<h3>白オリエンタルユリを本数指定で購入</h3>
                <form action="<?=BASEURL?>/order" method="post">
                <p class="form-inline">
                <input type="hidden" name="number" value="vs-casab">価格：1000円＋（消費税）</p>
                <p>3本以上でご購入いただけます</p>
                <p class="form-inline">
                <select name="quantity" class="form-control">
                <?php for($i=3;$i<101;$i++):?>
                <option value="<?=$i?>"><?=$i?></option>
                <?php endfor;?>
                </select>  個</p>
                <button type="submit" class="btn btn-success btn-lg">購入する</button>
                </form>
            </div>
            <div class="col-sm-2">
            	<img src="<?=BASEURL?>/img/1679_20160420063557.jpg" alt="おまかせフラワーアレンジメント">
            </div>
            <div class="col-sm-4">
        		<h3>ピンクユリを本数指定で購入</h3>
                <form action="<?=BASEURL?>/order" method="post">
                <p class="form-inline">
                <input type="hidden" name="number" value="vs-pink-lillie">価格：1000円＋（消費税）</p>
                <p>3本以上でご購入いただけます</p>
                <p class="form-inline">
                <select name="quantity" class="form-control">
                <?php for($i=3;$i<101;$i++):?>
                <option value="<?=$i?>"><?=$i?></option>
                <?php endfor;?>
                </select>  個</p>
                <button type="submit" class="btn btn-success btn-lg">購入する</button>
                </form>
            </div>
        </div>
		<!--中身-->
        </div>
      </div>
    </div>
</section>