<!--リスト表示-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
            <h2 class="m">商品一覧</h2>
          <ul class="breadcrumb">
          	<?=$this->bread?>
          </ul>
        	<!--タイトルをH２で定義する"-->
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <div class="hidden-xs">
        <div class="row" style="padding-right:3px;">
        <?php $i=0; foreach($this->item as $vv): ?>
            <div class="col-sm-4 col-xs-6 itemDetail">
				<?PHP /*<p class="img"><a href="<?=BASEURL?>/item/detail/?id=<?=$vv['id']?>"><img src="<?=BASEURL?>/item/wakuimage/?url=<?=urlencode($vv['imagen'])?>" alt="<?=$vv['name']?>" style="width: 100%; display: block;"></a></p>*/?>
                <p class="img"><a href="<?=BASEURL?>/item/detail/?id=<?=$vv['id']?>" class="imageList"><img src="<?=BASEURL?>/<?=$vv['imagen']?>" alt="<?=$vv['name']?>" style="width: 100%; display: block;"></a></p>
                <p class="description"><a href="<?=BASEURL?>/item/detail/?id=<?=$vv['id']?>" class="lineDescription"><?=htmlspecialchars_decode($vv['lineDescription'])?></a></p>
                <p class="title"><a href="<?=BASEURL?>/item/detail/?id=<?=$vv['id']?>"><?=$vv['name']?><br><?=number_format($vv['price'])?>円</a></p>
                <p class="viewDetail"><a href="<?=BASEURL?>/item/detail/?id=<?=$vv['id']?>">＞詳細を見る</a></p>
            </div>
        <?php endforeach;?>
        </div>
        </div>
        <?=$this->pager?>
        
        <?=$this->pager?>
          
		<!--中身-->
        </div>
      </div>
    </div>
</section>