[production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1

resources.frontController.params.displayExceptions = 1
bootstrap.path = APPLICATION_PATH "/Bootstrap.php"
bootstrap.class = "Bootstrap"
;resources.frontController.controllerDirectory = APPLICATION_PATH "/controllers"

;Use modules
resources.frontController.moduleDirectory = APPLICATION_PATH "/modules"
resources.modules=""

; Helper
resources.view.helperPath.Nc_View_Helper = "Nc/View/Helper"

;Config database
resources.db.adapter = "Pdo_mysql"
resources.db.params.host = "mysql56"
resources.db.params.username = "touhiisdb"
resources.db.params.password = "kPhGDCNze"
resources.db.params.dbname = "touhiisdb"
resources.db.params.charset = "utf8"

autoloaderNamespaces[] = "ZEND_"
autoloaderNamespaces.extension[] = "Common_"

;autoloaderNamespaces[] = "REST_"
;autoloaderNamespaces[] = "NP"
;autoloaderNamespaces[] = "Nc"
;rest.default = "json"
;rest.formats[] = "json"

; ログ設定
resources.log.stream.writerName = "Stream"
resources.log.stream.writerParams.stream = ROOT_PATH "/log/log_" YYMMDD  ".log"
resources.log.stream.writerParams.mode = "a"
resources.log.stream.filterName = "Priority"
;4or7
resources.log.stream.filterParams.priority = 7
resources.log.backtrace = false
