<?php if($this->Msg):?>
  <div class="alert alert-success">
    <?=$this->Msg?>
  </div>
<?php endif;?>
<br>
<div class="" role="tabpanel" data-example-id="togglable-tabs">
  <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#tab_content1" role="tab" id="profile-tab1" data-toggle="tab" aria-expanded="true">会社設定</a>
    </li>
  </ul>
  <div id="myTabContent" class="tab-content">
    <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
      <form action="<?=BASEURL?>/editor/settings/company/" method="post" name="edit">
        <section>
          <div class="x_panel">
            <div class="x_title">
              <h2>会社設定</h2>
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <table class="table table-striped table-responcive">
                <tbody>
                  <tr>
                    <th style="width:25%;"><label for="name" class="required">会社名</label></th>
                    <td><input type="text" name="company" value="<?=$this->data['company']?>" class="form-control"></td>
                  </tr>
                  <tr>
                    <th>電話番号</th>
                    <td><input type="text" name="tel" value="<?=$this->data['tel']?>" class="form-control"></td>
                  </tr>
                  <tr>
                    <th>FAX番号</th>
                    <td><input type="text" name="fax" value="<?=$this->data['fax']?>" class="form-control"></td>
                  </tr>
                  <tr>
                    <th>住所</th>
                    <td>
                      <p class="form-inline">
                        <select name="pref" class="form-control">
                          <option value="">都道府県を選択してください</option>
                          <?php foreach($this->pref as $v):?>
                          <?php if($v['id']==$this->data['pref']):?>
                          <option value="<?=$v['id']?>" selected><?=$v['name']?></option>
                          <?php else:?>
                          <option value="<?=$v['id']?>"><?=$v['name']?></option>
                          <?php endif;?>
                          <?php endforeach;?>
                        </select>
												<!--
                        <select name="pref" class="chosen-select">
                          <option value="">都道府県を選択してください</option>
                          <?php foreach($this->pref as $v):?>
                          <?php if($v['id']==$this->data['pref']):?>
                          <option value="<?=$v['id']?>" selected><?=$v['name']?></option>
                          <?php else:?>
                          <option value="<?=$v['id']?>"><?=$v['name']?></option>
                          <?php endif;?>
                          <?php endforeach;?>
                        </select>
												-->
                      </p>
                      <p class="form-inline">〒<input type="text" name="zip" value="<?=$this->data['zip']?>" class="form-control"></p>
                      <p>
                        <input type="text" name="addr" value="<?=$this->data['addr']?>" placeholder="市区町村番地" class="form-control">
                      </p>
                      <p>
                        <input type="text" name="addr2" value="<?=$this->data['addr2']?>" placeholder="ビル・マンション名、号室など" class="form-control">
                      </p>
                    </td>
                  </tr>
                  <tr>
                    <th>メール</th>
                    <td><input type="text" name="mail" value="<?=$this->data['mail']?>" class="form-control"></td>
                  </tr>
                  <!--tr>
                    <th>印鑑</th>
                    <td>
                      <button type="button" class="btn btn-default" id="selectPicture"><i class="fa fa-picture-o"></i> 画像を選択</button>
                      <span id="preview">
                        <?php if($this->data['stamp']):?>
                          <img src="<?=BASEURL?><?=$this->data['stamp']?>" style="width:120px;height:auto;">
                        <?php endif;?>
                      </span>
                      <input type="text" name="stamp" value="<?=$this->data['stamp']?>" class="form-control">
                    </td>
                  </tr-->
                </tbody>
              </table>
          		<!--中身-->
            </div>
          </div>
        </section>
      </form>
      <form action="<?=BASEURL?>/editor/settings/upload" method="post" enctype="multipart/form-data" target="upload" id="imageupload" style="display:none;">
        <input type="file" name="userfile" id="userfile" style="width:12em;" />
      </form>
      <iframe name="upload" style="display:none;"></iframe>
      <div class="form-actions">
        <button type="button" class="btn btn-large btn-block btn-primary" id="submit">編集</button>
      </div>
    </div>
</div>
<script src="<?=BASEURL?>/theme2/js/colorpicker/bootstrap-colorpicker.min.js"></script>
<link href="<?=BASEURL?>/theme2/css/colorpicker/bootstrap-colorpicker.min.css" rel="stylesheet">
<script src="<?=BASEURL?>/theme2/js/colorpicker/docs.js"></script>
<script src="<?=BASEURL?>/js/chosen/chosen.jquery.js"></script>
<link href="<?=BASEURL?>/js/chosen/chosen.css" rel="stylesheet">
<style>

.delteRest, .delteHolyday,.delteColor {
    color: red;
    font-size: 24px;
    line-height: 32px;
    display: inline-block;
}
.chosen-container .chosen-results {
    width: 100%;
}
</style>
<script>
var cc;
$(function(){
  $("#selectPicture").on("click",function(){
    $('[name=userfile]').click();
  });
	$("#userfile").on("change",function(){
		//$("#imageupload").append($(this));
		$("#imageupload").submit();
	});

  $("#submit").on("click",function(){
    if(window.confirm("設定を変更します")){
      $("[name=edit]").submit();
    }
  });
});
</script>
