<section>
<div class="block">
    <div class="navbar navbar-inner block-header">
    	<div class="muted pull-left">ポイント情報</div>
    </div>
    <div class="block-content collapse in">
    <ul class="nav nav-list bs-docs-sidenav nav-collapse collapse">
        <li>
            <a href="<?=BASEURL?>/admin/settings/global">サイト設定</a>
        </li>
        <li>
            <a href="<?=BASEURL?>/admin/settings/point">ポイント・割引・特別料金設定</a>
        </li>
        <li>
            <a href="<?=BASEURL?>/admin/settings/delivery">配達日時設定</a>
        </li>
        <li>
            <a href="<?=BASEURL?>/admin/settings/payment">決済方法設定</a>
        </li>
        <li>
            <a href="<?=BASEURL?>/admin/settings/shipping">送料設定</a>
        </li>
    </ul>
    </div>
</div>
</section>