<!--会員情報編集フォーム-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>メール送信登録フォーム</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
          <div class="data-table">
            <form action="<?=BASEURL?>/editor/mail/registrerfinish/" method="post" id="form">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                  <th><label for="subject" class="required">件名</label></th>
                  <td class="form-inline">
                  	<input type="text" name="subject" value="<?=$this->detail['subject']?>" class=" form-control">
                  </td>
                </tr>
                <tr>
                  <th><label for="body" class="required">本文</label></th>
                  <td>
                    <textarea name="body" class="form-control" rows="20"><?=$this->detail['body']?></textarea>
                  </td>
                </tr>
                <tr>
                  <th><label for="body">添付ファイル</label></th>
                  <td>
                    <div id="filesize"></div>
                    <div id="tmp"></div>
                    <p><button type="button" class="btn btn-success" id="addTmp"><i class="fa fa-plus"></i> 添付ファイルを追加</button></p>
                    <div id="tmpData"></div>
                  </td>
                </tr>
                </tbody>
              </table>
              </form>
            </div>
            <div class="form-actions">
							<button class="btn btn-large btn-block btn-primary" id="sub">登録</button>
            </div>
			<!--中身-->
        </div>
      </div>
    </div>
</section>
<!--style="display:none;"-->
<form action="<?=BASEURL?>/editor/mail/upload" method="post" enctype="multipart/form-data" target="upload" id="imageupload"  style="display:none;">
  <input type="file" name="userfile" id="userfile" style="width:12em;" />
  <input type="hidden" name="filesize" value="0" />
</form>
<iframe name="upload" style="display:none;"></iframe>
<script src="<?=BASEURL?>/js/validation.js"></script>
<script>
//バリデーション
var error =new Array;
$(function(){

  $(document).on("click",".deleteFile",function(){
    var This = $(this);
    if(window.confirm("添付ファイルを削除してもいいですか？")){
      $.post("<?=BASEURL?>/api/mail/deletetmp/",{file:$(this).data("filename")},function(data){
        console.log(data);
        if(data == "OK"){
          This.parent().remove();
        }
      });
    }
  });


	$("#userfile").on("change",function(){
		//$("#imageupload").append($(this));
		$("#imageupload").submit();
	});
  $("#addTmp").on("click",function(){
    $('[name=userfile]').click()
  });






	$("[name=subject]").on("blur",function(){
		validEmpty("subject","件名");
	});
	$("[name=body]").on("blur",function(){
		validEmpty("body","本文");
	});
	$("#sub").on("click",function(){
		validEmpty("subject","件名");
		validEmpty("body","本文");
		if(error.length >0){
			var str = "";
			str+= "入力に誤りがあります。下記の項目を修正して再度ボタンを押してください。\n";
			for(var i =0;i<error.length;i++){
				if(error[i] =="subjectEmpty"){
					str+="「件名」を入力してください。\n";
				}
				if(error[i] =="bodyEmpty"){
					str+="「本文」を入力してください。\n";
				}
			}
			alert(str);
		}else{
			if(window.confirm("メール送信登録を行います。内容を変更される場合はキャンセルボタンを押してください。")){
				$("#form").submit();
			}
		}
	});
});
</script>
