<?php if($_GET['finish'] == 1):?>
  <div class="alert alert-warning">更新しました。</div>
<?php endif;?>
<!--部門情報編集フォーム-->
<p><a href="<?=BASEURL?>/editor/mail/" class="btn btn-success">メール送信一覧へ</a></p>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>メール送信編集フォーム</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
          <div class="data-table">
          	<form action="<?=BASEURL?>/editor/mail/updatefinish" method="post" id="form">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                  <th><label for="name" class="required">件名</label></th>
                  <td class="form-inline">
                  	<input type="text" name="subject" value="<?=$this->detail['subject']?>" class=" form-control">
                  </td>
                </tr>
                <tr>
                  <th><label for="name" class="required">本文</label></th>
                  <td>
                    <textarea name="body" class="form-control" rows="20"><?=$this->detail['body']?></textarea>
                  </td>
                </tr>
                <tr>
                  <th><label for="body">添付ファイル</label></th>
                  <td>
                    <div id="filesize"></div>
                    <div id="tmp">
                      <?php foreach($this->detail['tmp'] as $v):?>
                        <p>
                          <img src="<?=$v['icon']?>" style="width:30px;height:auto;"> <?=$v['file']?>
                          <a href="javascript:void(0)" class="btn btn-danger btn-sm deleteFile" style="border-radius:50%;padding:0 0.35em;" data-filename="<?=$v['file']?>"><i class="fa fa-times"></i></a>
                        </p>
                      <?php endforeach;?>
                    </div>
                    <p><button type="button" class="btn btn-success btn-sm" id="addTmp"><i class="fa fa-plus"></i> 添付ファイルを追加</button></p>
                    <div id="tmpData">
                      <?php foreach($this->detail['tmp'] as $v):?>
                        <input type="hidden" name="tmp[]" value="<?=$v['file']?>">
                      <?php endforeach;?>
                    </div>
                  </td>
                </tr>
                </tbody>
              </table>
              <input type="hidden" name="id" value="<?=$this->detail['id']?>">
              </form>
            </div>
            <div class="form-actions">
                <button class="btn btn-large btn-block btn-primary" id="sub">編集</button>
            </div>
			<!--中身-->
        </div>
      </div>
    </div>
</section>
<form action="<?=BASEURL?>/editor/mail/upload" method="post" enctype="multipart/form-data" target="upload" id="imageupload"  style="display:none;">
  <input type="file" name="userfile" id="userfile" style="width:12em;" />
  <input type="hidden" name="filesize" value="0" />
</form>
<iframe name="upload" style="display:none;"></iframe>
<script src="<?=BASEURL?>/js/validation.js"></script>
<script>
//バリデーション
var error =new Array;
$(function(){
  $(document).on("click",".deleteFile",function(){
    var This = $(this);
    var file = $(this).data("filename");
    if(window.confirm("添付ファイルを削除してもいいですか？")){
      $.post("<?=BASEURL?>/api/mail/deletetmp/",{file:file,id:$("[name='id']"),type:"mail".val()},function(data){
        console.log(data);
        if(data == "OK"){
          This.parent().remove();
          $('[name="tmp[]"][value="'+file+'"]').remove();
        }
      });
    }
  });




	$("#userfile").on("change",function(){
		//$("#imageupload").append($(this));
		$("#imageupload").submit();
	});
  $("#addTmp").on("click",function(){
    $('[name=userfile]').click()
  });


	$("[name=subject]").on("blur",function(){
		validEmpty("subject","件名");
	});
	$("[name=body]").on("blur",function(){
		validEmpty("body","本文");
	});

	$("#sub").on("click",function(){
		validEmpty("subject","件名");
  		validEmpty("body","本文");
		if(error.length >0){
			var str = "";
			str+= "入力に誤りがあります。下記の項目を修正して再度ボタンを押してください。\n";
			for(var i =0;i<error.length;i++){
				if(error[i] =="subjectEmpty"){
					str+="「件名」を入力してください。\n";
				}
				if(error[i] =="bodyEmpty"){
					str+="「本文」を入力してください。\n";
				}
			}
			alert(str);
		}else{
			if(window.confirm("メール送信登録を行います。内容を変更される場合はキャンセルボタンを押してください。")){
				$("#form").submit();
			}
		}
	});
});
</script>
