
<style>
#loading {
	position:fixed;
	width:100%;
	height:100%;
	top:0;
	left:0;
	background:rgba(0,0,0,0.5);
}
#loading p{
	position:absolute;
	background-color:white;
	padding:0.5em;
	top:50%;
	left:50%;
	border-radius:5px;
	margin-left:-71px;
	margin-top:-71px;
}
</style>
<!--商品情報編集フォーム-->
<?php if($this->msg):?>
<div class="alert alert-info">
	<p><?=$this->msg?></p>
</div>
<?php endif;?>
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          	<?php if($this->mode == "register"):?>
          		<h2><?=$this->ja?>登録</h2>
           	<?php elseif($this->mode == "detail"):?>
          		<h2><?=$this->data['name']?>詳細<?php if($this->data['active']==2):?>　<button type="button" id="activate" class="btn btn-warning" data-id="<?=$this->data['id']?>">承認する</button><?php endif;?></h2>
           	<?php else:?>
          		<h2><?=$this->data['name']?>編集</h2>
            <?php endif;?>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
          <?php /*登録・編集・詳細画面*/?>
          <div class="data-table">
          	<?php if($this->mode == "register"):?>
            <form action="<?=BASEURL?>/admin/<?=$this->controller?>/edit/?mode=register" method="post" id="form">
           	<?php else:?>
            <form action="<?=BASEURL?>/admin/<?=$this->controller?>/edit/?mode=update" method="post" id="form">
            <?php endif;?>
              <table class="table table-striped table-responcive">
                <tbody>
									<tr>
										<th>フォント名<span class="require">必須</span></th>
										<td><label class="form-inline"><input type="text" name="name" value="<?=$this->data['name']?>" class="form-control d">※全角・半角</label>
										</td>
									</tr>
										<tr>
											<th>表示名<span class="require">必須</span></th>
											<td><label class="form-inline"><input type="text" name="nickname" value="<?=$this->data['nickname']?>" class="form-control d">※全角・半角</label>
											</td>
										</tr>
									<tr>
										<th>フォントデータ<span class="require">必須</span></th>
										<td><label class="form-inline"><input type="text" name="path" value="<?=$this->data['path']?>" class="form-control d" />
										<button type="button" class="btn btn-primary im d" id="image1">選択</button>※TrueTypeフォントのみ対応</label>

										</td>
									</tr>
									<tr>
										<th>表示・非表示</th>
										<td>
											<label class="form-inline">
												<select name="active" class="form-control d" style="width:5em;">
													<?php foreach(array("1"=>"表示","2"=>"非表示") as $k=>$v):?>
													<?php if($k == $this->data['active']):?>
													<option value="<?=$k?>" selected="selected"><?=$v?></option>
													<?php else:?>
													<option value="<?=$k?>"><?=$v?></option>
													<?php endif;?>
													<?php endforeach;?>
												</select>
											</label>
										</td>
									</tr>
                </tbody>
              </table>
              <input type="hidden" name="id" value="<?=$this->data["id"]?>">
            </form>
          	</div>
            <div style="display:none">
                <iframe name="upload"></iframe>
                <form action="<?=BASEURL?>/admin/contest/upload3" method="post" enctype="multipart/form-data" target="upload" id="imageupload3">
                <input type="hidden" name="id" value="<?=$this->data['id']?>">
                </form>
                <form action="<?=BASEURL?>/admin/contest/upload" method="post" enctype="multipart/form-data" target="upload" id="imageupload">
                <input type="hidden" name="id" value="<?=$this->data['id']?>">
                </form>
                <form action="<?=BASEURL?>/admin/contest/upload2" method="post" enctype="multipart/form-data" target="upload" id="imageupload2">
                <input type="hidden" name="id" value="<?=$this->data['id']?>">
                </form>
            </div>
            <div class="form-actions">
          	<?php if($this->mode == "register"):?>
                <button class="btn btn-large btn-block btn-primary" id="sub">登録</button>
           	<?php elseif($this->mode == "update"):?>
                <button class="btn btn-large btn-block btn-primary" id="sub">編集</button>
           	<?php elseif($this->mode == "detail"):?>
            	<a href="<?=BASEURL?>/admin/<?=$this->controller?>/edit?mode=update&id=<?=$this->data['id']?>" class="btn btn-large btn-block btn-primary">編集</a>
                <form>
                    <input type="hidden" name="ids" value="<?=$this->data['id']?>">
                    <button type="button" class="btn btn-large btn-block btn-danger" id="deleteAll">削除</button>
                </form>
            <?php endif;?>
            </div>

		<!--中身-->
        </div>
      </div>
    </div>
</section>
<div style="display:none;">
<form action="<?=BASEURL?>/admin/font/upload" method="post" enctype="multipart/form-data" target="upload" id="imageupload">
    <input type="file" name="userfile" id="userfile" />
    <span id="imageID"></span>
</form>
</div>
<div id="loading" style="display:none;">
	<p><img src="<?=BASEURL?>/img/Preloader_1.gif" /></p>
</div>
<?php if($this->mode == "register" || $this->mode == "update"):?>
<script src="<?=BASEURL?>/js/validation.js"></script>
<script>
//画像アップロード
$(".im").on("click",function(){
	$("imageID").empty();
	var input = $("<input type=\"hidden\" name=\"id\">");
	input.val($(this).attr("id"));
	$("#imageID").append(input);
	$("#userfile").click();
	//待機画面を表示する
	$("#loading").css("display","block");
});
$("#userfile").on("change",function(){
	$("#imageupload").submit();
});
var error = new Array();
$(function(){
	//送信時アクション
	$("#sub").on("click",function(){
		//バリデーション
		validEmpty("name","<?=$this->ja?>名");


		if(error.length >0){
			var str = "下記の入力に誤りがあります。";

			for(var i =0;i<error.length;i++){
				if(error[i] =="nameEmpty"){
					str+="「<?=$this->ja?>名」を入力してください。\n";
				}
			}
			alert(str);
		}else{
          	<?php if($this->mode == "register"):?>
				if(window.confirm("<?=$this->ja?>登録を行います。内容を変更される場合はキャンセルボタンを押してください。")){
           	<?php else:?>
				if(window.confirm("<?=$this->ja?>編集を行います。内容を変更される場合はキャンセルボタンを押してください。")){
            <?php endif;?>
				$("#form").submit();
				}
		}
	});
});
</script>
<?php elseif($this->mode == "detail"):?>
<script>
	//
	$("#activate").on("click",function(){
		var id = $(this).data("id");
		$.post('<?=BASEURL?>/api/entry/activate/',{id:id},function(data){
			if(data = "OK"){
				location.reload();
			}
		});

	});
	//inputを無効化
	$(".d").attr("readonly",true);
	//削除
	$("#deleteAll").on("click",function(){
		if(window.confirm("本当に削除してもいいですか？")){
			var ck = $('input[name=ids]').val();
			var url = "<?=BASEURL?>/api/<?=$this->controller?>/delete/";
			$.post(url,{ids:ck},function(data){
				if(data = "OK"){
					location.href = "<?=BASEURL?>/admin/<?=$this->controller?>/";
				}
			});
		}
	});
</script>

<?php endif;?>
