<!--検索-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2><?=$this->ja?>を検索</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->

            <form action="<?=BASEURL?>/admin/<?=$this->controller?>/" method="get">
            	 <div class="row">
                   <p class="col-sm-2">キーワード：</p>
                   <p class="col-sm-4"><input type="text" name="keyword" value="<?=$_GET['keyword']?>" class="form-control"></p>
                   <p class="col-sm-2">表示件数：</p>
                   <p class="col-sm-4">
                   <select name="limit" class="form-control">
                        <!--option value="1">1件</option-->
                        <option value="10">10件</option>
                        <option value="25">25件</option>
                        <option value="50">50件</option>
                        <option value="75">75件</option>
                        <option value="100">100件</option>
                    </select>
                   </p>
                </div>
                <p class="text-center">
                <button type="reset" class="btn btn-danger">リセット</button>
                <button type="submit" class="btn btn-warning">検索</button>
                </p>
            </form>

			<!--中身-->
        </div>
      </div>
    </div>
</section>

<!--リスト表示-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2><?=$this->ja?>一覧</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
        <p><a href="<?=BASEURL?>/admin/<?=$this->controller?>/edit?mode=register" class="btn btn-success"><?=$this->ja?>登録</a></p>
        <?=$this->pager?>
        			<table class="table table-striped responsive-utilities jambo_table bulk_action">
                    <thead>
                      <tr class="headings">
                        <th>
                      		<input type="checkbox" id="allcheck" class="flat ck">
                        </th>
                        <th class="column-title"><?=$this->ja?>名 </th>
                        <th class="column-title">表示名 </th>
                        <th class="column-title">詳細 </th>
                      </tr>
                    </thead>
                    <tbody>
            			<?php foreach($this->users as $vv):?>
                      <tr class="even pointer">
                        <td class="a-center ">
                          <input type="checkbox" class="ck" name="ck[]" value="<?=$vv['id']?>">
                        </td>
                        <td class=" "><?=$vv['name']?></td>
                        <td class=" "><?=$vv['nickname']?></td>
                        <td class="">
                            <form action="<?=BASEURL?>/admin/<?=$this->controller?>/edit" method="get">
                                <input type="hidden" name="id" value="<?=$vv['id']?>">
                                <input type="hidden" name="mode" value="detail">
                                <button type="submit" class="btn btn-primary">詳細</button>
                            </form>
                        </td>
                      </tr>
            			<?php endforeach;?>
                    </tbody>
                  </table>
                <div class="profile_title">
                    <div class="row">
                            <div class="col-sm-12">
                            <button class="btn btn-danger" type="button" id="deleteAll">チェックしたものを削除</button>
                         </div>
                    </div>
              </div>
        		<?=$this->pager?>

		<!--中身-->
        </div>
      </div>
    </div>
</section>
<script>
$(function(){
	$('input[type=checkbox]').click(function() {
	  var t = $(this).prop;
		if(t('checked'))
			t('checked', '');
		else
			t('checked', 'checked');
	});

	$('table tr').click(function() {
	  var c = $(this).children('td').children('input[type=checkbox]');
		if(c.prop('checked'))
			c.prop('checked', '');
		else
			c.prop('checked', 'checked');
	});
	//checkboxを全て同時に選択
	$("#allcheck").on("click",function(){
		if($(this).is(':checked')){
			$(".ck").prop('checked', true);
		}else{
			$(".ck").prop('checked', false);
		}
	});
	$("#deleteAll").on("click",function(){
		if(window.confirm("本当に削除してもいいですか？")){
			var ck = $('[class="ck"]:checked').map(function(){
				return $(this).val();
			}).get();
			var url = "<?=BASEURL?>/api/<?=$this->controller?>/delete/";
			$.post(url,{ids:ck},function(data){
				if(data = "OK"){
					location.href = "<?=BASEURL?>/admin/<?=$this->controller?>/";
				}
			});
		}
	});
});
</script>
