<!--会員情報編集フォーム-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2><img src="<?=BASEURL?>/img/cart/new/editMembership.jpg" alt="会員編集フォーム" width="289">会員編集フォーム</h2>
        	<!--タイトルをH２で定義する"-->
        </div>
        <div class="x_content">
		<!--中身-->
        	<p>以下の内容で登録情報を更新します。よろしければ更新するボタンを押してください。</p>
        <div class="formset">
           <form action="<?=BASEURL?>/members/finish/" method="post" id="form">
        	<div class="line clearfix">
           	<div class="left">お名前</div>
           	<div class="right">
            		<?=$this->detail['name']?>　<?=$this->detail['name2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">フリガナ</div>
           	<div class="right"><?=$this->detail['kana']?>　<?=$this->detail['kana2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">メールアドレス</div>
           	<div class="right"><?=$this->detail['mail']?>
               </div>
           </div>
           
        	<div class="line clearfix">
           	<div class="left">性別</div>
           	<div class="right">
					<?php foreach(array(1=>"女性",2=>"男性") as $k=>$v):?>
                    <?php if($k == $this->detail['sex']):?>
                    <?=$v?>
                    <?php endif;?>
                    <?php endforeach;?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">生年月日</div>
           	<div class="right"><?=$this->detail['birthY']?>年<?=$this->detail['birthM']?>月<?=$this->detail['birthD']?>日
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">電話番号（携帯可）</div>
           	<div class="right"><?=$this->detail['tel']?>-<?=$this->detail['tel2']?>-<?=$this->detail['tel3']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">緊急連絡先</div>
           	<div class="right"><?=$this->detail['mtel']?>-<?=$this->detail['mtel2']?>-<?=$this->detail['mtel3']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">郵便番号</div>
           	<div class="right"><?=$this->detail['zip']?>-<?=$this->detail['zip2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">都道府県</div>
           	<div class="right">
                        <?php foreach($this->pref as $v):?>
                        <?php if($v['id'] == $this->detail['pref']):?>
                        <?=$v['name']?>
                        <?php endif;?>
                        <?php endforeach;?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">市区町村、番地</div>
           	<div class="right"><?=$this->detail['addr']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">ビル名・マンション名、号室</div>
           	<div class="right"><?=$this->detail['addr2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">パスワード</div>
           	<div class="right">
					<?php if($this->detail['pw']):?>
                    <?=$this->detail['pw']?>
                   <?php else:?>
                   	パスワードの編集は行いません。
                   <?php endif;?>
               </div>
           </div>
              <?php
             	foreach($this->detail as $k=>$v){
					echo "<input type=\"hidden\" name=\"{$k}\" value=\"{$v}\">";
				} 
			  ?>
        </form>
        <div class="form-actions">
        	<p class="text-center"><button id="subbtn" type="button"> 編集する</button></p>
        </div>
        </div>
			<!--中身-->
        </div>
      </div>
    </div>
</section>
<script>


jQuery(function(){
	$("#subbtn").on("click",function(){
		if(confirm("登録情報の更新を行います。よろしければOKボタンを押してください")){
			$("#form").submit();
		}
	});
});
</script>