<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2><img src="<?=BASEURL?>/img/cart/new/editMembership.jpg" alt="会員編集フォーム" width="289">会員編集フォーム</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
        </div>
        <div class="x_content">
		<!--中身-->
          <?php if($this->Msg):?>
          	<div class="alert alert-info">
            	<p><?=$this->Msg?></p>
            </div>
          <?php endif;?>
          <p><a href="<?=BASEURL?>/members">詳細ページに戻る</a></p>
        <div class="formset">
        	<div class="line clearfix">
           	<div class="left">お名前</div>
           	<div class="right">
            		<?=$this->detail['name']?>　<?=$this->detail['name2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">フリガナ</div>
           	<div class="right"><?=$this->detail['kana']?>　<?=$this->detail['kana2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">メールアドレス</div>
           	<div class="right"><?=$this->detail['mail']?>
               </div>
           </div>
           
        	<div class="line clearfix">
           	<div class="left">性別</div>
           	<div class="right">
					<?php foreach(array(1=>"女性",2=>"男性") as $k=>$v):?>
                    <?php if($k == $this->detail['sex']):?>
                    <?=$v?>
                    <?php endif;?>
                    <?php endforeach;?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">生年月日</div>
           	<div class="right"><?=$this->detail['birthY']?>年<?=$this->detail['birthM']?>月<?=$this->detail['birthD']?>日
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">電話番号（携帯可）</div>
           	<div class="right"><?=$this->detail['tel']?>-<?=$this->detail['tel2']?>-<?=$this->detail['tel3']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">緊急連絡先</div>
           	<div class="right"><?=$this->detail['mtel']?>-<?=$this->detail['mtel2']?>-<?=$this->detail['mtel3']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">郵便番号</div>
           	<div class="right"><?=$this->detail['zip']?>-<?=$this->detail['zip2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">都道府県</div>
           	<div class="right">
                        <?php foreach($this->pref as $v):?>
                        <?php if($v['id'] == $this->detail['pref']):?>
                        <?=$v['name']?>
                        <?php endif;?>
                        <?php endforeach;?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">市区町村、番地</div>
           	<div class="right"><?=$this->detail['addr']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">ビル名・マンション名、号室</div>
           	<div class="right"><?=$this->detail['addr2']?>
               </div>
           </div>
        	<div class="line clearfix">
           	<div class="left">パスワード</div>
           	<div class="right">ご登録いただいたパスワード（セキュリティのため非表示）
               </div>
           </div>
        </div>
		<!--中身-->
        </div>
      </div>
    </div>
</section>