
<!--スタッフ情報-->
<section class="row">
    <div class="col-xs-12">
      <div class="x_panel">
        <div class="x_title">
        	<!--タイトルをH２で定義する"-->
          <h2>会員情報</h2>
        	<!--タイトルをH２で定義する"-->
          <ul class="nav navbar-right panel_toolbox">
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
            <li><a class="close-link"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
		<!--中身-->
          <!--p class="text-right"><a href="<?=BASEURL?>/editor/editor/gantt2/?id=<?=$this->data['id']?>" class="btn btn-warning">ガントチャート</a></p-->
          <div class="data-table">
              <table class="table table-striped table-responcive">
                <tbody>
                <tr>
                  <th>医療機関名</th>
                  <td><?=$this->data['name']?></td>
                </tr>
                <tr>
                  <th>フリガナ</th>
                  <td><?=$this->data['kana']?></td>
                </tr>
                <tr>
                  <th>メール</th>
                  <td><?=$this->data['mail']?></td>
                </tr>
                <tr>
                  <th>電話番号</th>
                  <td><?=$this->data['tel']?>-<?=$this->data['tel2']?>-<?=$this->data['tel3']?></td>
                </tr>
                <tr>
                  <th>FAX電話</th>
                  <td><?=$this->data['mtel']?>-<?=$this->data['mtel2']?>-<?=$this->data['mtel3']?></td>
                </tr>
                <tr>
                  <th>住所</th>
                  <td>〒<?=$this->data['zip']?>-<?=$this->data['zip2']?><br><?=$this->data['prefName']?><?=$this->data['addr']?><br><?=$this->data['addr2']?>
                  </td>
                </tr>
                </tbody>
              </table>
            </div>
            <div class="form-actions">
              <a href="<?=BASEURL?>/editor/user/update/?id=<?=$this->data['id']?>" class="btn btn-large btn-block btn-primary">編集</a>
              <input type="hidden" name="ids" value="<?=$this->data['id']?>">
              <button type="button" class="btn btn-large btn-block btn-danger" id="deleteAll">削除</button>
            </div>
			<!--中身-->
        </div>
      </div>
    </div>
</section>
<script>
$("#deleteAll").on("click",function(){
	if(window.confirm("本当に削除してもいいですか？")){
		var ck = $('input[name=ids]').val();
		var url = "<?=BASEURL?>/api/user/delete/";
		$.post(url,{ids:ck},function(data){
			if(data = "OK"){
				location.href = "<?=BASEURL?>/editor/user/";
			}
		});
	}
});
</script>
