<!-- Form section -->
<div class="section">
	<div class="container margin-bottom-40">
    <div class="padding-30 border-radius-05 margin-bottom-30 border-all">
	    <p class="mb-5">パスワードを忘れた方は、下記の項目にご登録のメールアドレスを入力してください。該当するメールアドレス宛にパスワードの再設定様のURLが送信されます。</p>
			<?php if($this->Msg):?>
				<div class="alert alert-<?=$this->Msg['color']?>"><?=$this->Msg['message']?></div>
			<?php endif;?>
	    <form action="<?=BASEURL?>/signin/pass<?php if($this->m) echo "?m=".$this->m?>" method="post">
	      <label>メールアドレス</label>
	      <input type="email" name="mail" placeholder="example@touhi.co.jp" required>
	      <div class="text-center mt-2">
	      	<button type="submit" class="button button-lg button-radius button-dark">URLを送信</button>
	      </div>
	    </form>
	    <div class="text-center mt-4">
	    	<h6><i class="fas fa-arrow-circle-left"></i> <a class="button-text-1" href="<?=BASEURL?>/signin/<?php if($this->m) echo "?m=".$this->m?>">ログイン画面へ戻る</a></h6>
	    </div>
    </div>
	</div>
	<!-- end container -->
</div>
<!-- end Form section -->
